In [1]:
import json
import pandas as pd
import requests

In [ ]:
cliente = "XXXXX"

nombre_artista = ['Five For Fighting', 'The Smashing Pumpkins', 'The Beatles', 'Deftones'] 
#prueba con artistas aleatorios

url_api = "http://ws.audioscrobbler.com/2.0/"

lista_artistas = []

def llamar_lastfm_api(method, artist_name, cliente):
        params = {'method': method,'artist': artist_name,'api_key': cliente,'format': 'json'}
        response = requests.get(url_api, params=params)
        if response.status_code == 200:
            return response.json()
        else:
            print(f"Error {response.status_code}: No se pudo obtener la información para el método {method}")
            return

print(f"Obteniendo detalles de: {nombre_artista}")

Obteniendo detalles de: ['Five For Fighting', 'The Smashing Pumpkins', 'The Beatles', 'Deftones']

In [ ]:
artistas_a_consultar = ["Gigi D'Agostino", "Pink Floyd", "Led Zeppelin", "Queen", "The Beatles"] 
#prueba con artistas aleatorios

lista_artistas = []

for nombre_artista in artistas_a_consultar:
    print(f"--- Consultando: {nombre_artista} ---")
    datos_artista = llamar_lastfm_api('artist.getinfo', nombre_artista, cliente)

    if datos_artista and 'artist' in datos_artista:
        artista_data = datos_artista['artist']
        oyentes = artista_data.get('stats', {}).get('listeners', 'arista no encontrado')
        reproducciones = artista_data.get('stats', {}).get('playcount', 'N/D')
        bio_content = artista_data.get('bio', {}).get('content', '')

        if not bio_content or bio_content.strip() == "":
            bio_resumen = 'biografia no encontrada'

        else:
            bio_resumen = artista_data.get('bio', {}).get('summary')

        lista_artistas_dict = {'artista': artista_data.get('name', nombre_artista),'oyentes': oyentes, 'reproducciones': reproducciones, 'bio_resumen': bio_resumen}
        lista_artistas.append(lista_artistas_dict)
        print(f"Datos de {nombre_artista} procesados y guardados.")

    else:
        print(f"No se pudo obtener información de {nombre_artista}")

--- Consultando: Gigi D'Agostino ---
Datos de Gigi D'Agostino procesados y guardados.
--- Consultando: Pink Floyd ---
Datos de Pink Floyd procesados y guardados.
--- Consultando: Led Zeppelin ---
Datos de Led Zeppelin procesados y guardados.
--- Consultando: Queen ---
Datos de Queen procesados y guardados.
--- Consultando: The Beatles ---
Datos de The Beatles procesados y guardados.

In [4]:
lista_artistas

[{'artista': "Gigi D'Agostino",
  'oyentes': '972313',
  'reproducciones': '14268462',
  'bio_resumen': 'Luigino Celestino di Agostino (born 17 December 1967), known professionally as Gigi D\'Agostino, is an Italian DJ and music producer. He began his career in 1986 as a DJ specialising in Italo disco. His most successful releases include "Bla Bla Bla," "Another Way," his cover of Nik Kershaw\'s "The Riddle," "La Passion," "Super," and "L\'Amour Toujours," all released between 1999 and 2000. The melody of "L\'Amour Toujours" was later used in the 2018 remix and mashup "In My Mind." <a href="https://www.last.fm/music/Gigi+D%27Agostino">Read more on Last.fm</a>'},
 {'artista': 'Pink Floyd',
  'oyentes': '5343132',
  'reproducciones': '583216164',
  'bio_resumen': 'Pink Floyd was an English rock band formed in London in 1965. Gaining an early following as one of the first British psychedelic groups, they were distinguished by their extended compositions, sonic experimentation, philosophical lyrics and elaborate live shows. They became a leading band of the progressive rock genre, cited by some as the greatest progressive rock band of all time.\n\nPink Floyd were founded in 1965 by Syd Barrett (guitar, lead vocals) <a href="https://www.last.fm/music/Pink+Floyd">Read more on Last.fm</a>'},
 {'artista': 'Led Zeppelin',
  'oyentes': '4795677',
  'reproducciones': '330406949',
  'bio_resumen': 'Led Zeppelin was a hard rock band formed in London in 1968. The group comprised vocalist Robert Plant, guitarist Jimmy Page, bassist and keyboardist John Paul Jones, and drummer John Bonham. With a heavy, guitar-driven sound, they are cited as one of the progenitors of hard rock and heavy metal, although their style drew from a variety of influences, including blues and folk music. Led Zeppelin have been credited as significantly impacting the nature of the music industry <a href="https://www.last.fm/music/Led+Zeppelin">Read more on Last.fm</a>'},
 {'artista': 'Queen',
  'oyentes': '6982904',
  'reproducciones': '406272634',
  'bio_resumen': 'Queen is a British rock band formed in London in 1970 by Freddie Mercury (lead vocals, piano), Brian May (guitar, vocals), and Roger Taylor (drums, vocals), later joined by John Deacon (bass). Their earliest works were influenced by progressive rock, hard rock, and heavy metal, but the band gradually ventured into more conventional and radio-friendly styles by incorporating elements of arena rock and pop rock.\n\nBefore forming Queen, May and Taylor had played together in the band Smile. <a href="https://www.last.fm/music/Queen">Read more on Last.fm</a>'},
 {'artista': 'The Beatles',
  'oyentes': '6292167',
  'reproducciones': '1045796051',
  'bio_resumen': 'The Beatles was an English rock band formed in Liverpool, Lancashire in 1960. With the line-up comprising John Lennon, Paul McCartney,  George Harrison, and Ringo Starr, they are regarded as the most popular and influential band of all time. The group were integral to the development of 1960s counterculture and popular music\'s recognition as an art form. Rooted in skiffle, beat and 1950s rock and roll, their sound incorporated elements of classical <a href="https://www.last.fm/music/The+Beatles">Read more on Last.fm</a>'}]

In [ ]:
# Código funciona. Ahora, pasamos nuestra lista de artistas de spotify a una lista de artistas únicos (no repetidos):

In [6]:
df = pd.read_csv("df_electronica.csv")

In [7]:
df

,Artista,Género,Tipo,Nombre,Año,ID
0,Gigi D'Agostino,electronic,track,L'Amour Toujours (Tanzen Vision RMX),2000,0Cjl6YCM4JQSgdg3xaFPxk
1,A Touch Of Class,electronic,track,My Heart Beats Like A Drum (Dam Dam Dam) - Rad...,2000,0hRFDhaHRJt6cz69n78G3f
2,Morcheeba,electronic,track,Rome Wasn't Built in a Day,2000,6lsumzVFKP9SnfKcuGwqVp
3,Air,electronic,track,Highschool Lover,2000,6JBDPZ0DOmc5mBJprphQc8
4,Vengaboys,electronic,track,Kiss (When The Sun Don't Shine),2000,0CZWUolHfpM91zjjH6sJBN
...,...,...,...,...,...,...
745,DJ KRUSH,electronic,track,Beyond Raging Waves,2004,0vsgbzsEf6AkJoUxxrO1fg
746,ATB,electronic,track,Collides with Beauty,2004,1qFSEJG7buRP2sn6fEaM7N
747,Boom Bip,electronic,track,Last Walk Around Mirror Lake - Boards of Canad...,2004,4agMFZlZVMPvXcpLewP2tS
748,Nathan Fake,electronic,track,The Sky Was Pink - Holden Remix,2004,2oeEq7M17OE5rqcYYYHZet
749,Scooter,electronic,track,One (Always Hardcore),2004,04frI4TPBnmvaYXHeqELQL

In [8]:
df['Artista']

0       Gigi D'Agostino
1      A Touch Of Class
2             Morcheeba
3                   Air
4             Vengaboys
             ...
745            DJ KRUSH
746                 ATB
747            Boom Bip
748         Nathan Fake
749             Scooter
Name: Artista, Length: 750, dtype: object

In [9]:
artista = df['Artista']

In [10]:
artistas_unicos = set(artista)

In [11]:
artistas_unicos

{'2 Eivissa',
 '666',
 '9 Lazy 9',
 'A Touch Of Class',
 'ATB',
 'AYA',
 'Ai-Ai delas Alas',
 'Aim',
 'Air',
 'Alcazar',
 'Alex C.',
 'Alice Deejay',
 'Alison Crockett',
 'Amon Tobin',
 'Amp Fiddler',
 'Andreid',
 'Andrew E.',
 'Ann Lee',
 'Aphex Twin',
 'Aqua',
 'Aquarious',
 'Archive',
 'Bambee',
 'Barcode Brothers',
 'Bayani Agbayani',
 "Beauty's Confusion",
 'Benny Benassi',
 'Beth Gibbons',
 'Beverlei Brown',
 'Big Muff',
 'Björk',
 'Blockhead',
 'Blue Foundation',
 'Blue States',
 'Blur',
 'Boards of Canada',
 'Bob Baldwin',
 "Bomfunk MC's",
 'Bonobo',
 'Boom Bip',
 'Boozoo Bajou',
 'Bowery Electric',
 'C21',
 'Calibre',
 'Caramell',
 'Casino Versus Japan',
 'Catrien',
 'Celldweller',
 'Charanjit Singh',
 'Chateau Flight',
 'Clara Hill',
 'Clazziquai',
 'Club des Belugas',
 'Clubringer',
 'Conjure One',
 "D'Sound",
 'DJ Aligator',
 'DJ BoBo',
 'DJ Cam',
 'DJ Encore',
 'DJ KRUSH',
 'DJ Lhasa',
 'DJ Marky',
 'DJ Nu-Mark',
 'DJ Sammy',
 'DJ Satomi',
 'DJ Shadow',
 'DJ Toxic',
 'DJ Volume',
 'DJs@Work',
 'DVS1',
 'Da Hool',
 'Daddy DJ',
 'Daft Punk',
 'Danzel',
 'Darude',
 'De-Phazz',
 'Death In Vegas',
 'Delerium',
 'Devics',
 'Divinorum',
 'Dizzee Rascal',
 'Doctor Rockit',
 'Dzihan & Kamien',
 'E-Type',
 'Eddy Wata',
 'Eiffel 65',
 'Elsa',
 'Enigma',
 'Eric Prydz',
 'Erika',
 'Erykah Badu',
 'Etro Anime',
 'FC Kahuna',
 'Faithless',
 'Fantasy Project feat. NDA',
 'Fatboy Slim',
 'Fila Brazillia',
 'Fingathing',
 'Fischerspooner',
 'Floorfilla',
 'Flunk',
 'Four Tet',
 'French Affair',
 'Frou Frou',
 'Funki Porcini',
 'GAS',
 'Gabin',
 'Gabry Ponte',
 'Gaya Band',
 'Georg Levin',
 'Gerardo Frisina',
 "Gigi D'Agostino",
 'Gladys and the Boxers',
 'Goldfrapp',
 'Gorillaz',
 'Gotan Project',
 'Greyboy',
 'Groove Armada',
 'Groove Collective',
 'Groove Coverage',
 'Günther',
 'Haddaway',
 'Handsome Boy Modeling School',
 'Harry Corpuz',
 'Herbert',
 'Highland',
 'Hird',
 'Hooverphonic',
 'Hybrid',
 'Ian Brown',
 'Idris Muhammad',
 'In-Grid',
 'Incognito',
 'Infernal',
 'Infinity',
 'J-Walk',
 'James',
 'Jamiroquai',
 'Jan Jelinek',
 'Jan Wayne',
 'Jazzamor',
 'Jazzanova',
 'Jazztronik',
 'Joachim Garraud',
 'John The Whistler',
 'Jolina Magdangal',
 'Jon Kennedy',
 'Kate Ryan',
 'Kim Lukas',
 'Klubbhoppers',
 'Koop',
 'Kraftwerk',
 'Kylie Minogue',
 'Kyoto Jazz Massive',
 'LFO',
 'LTJ Bukem',
 'La Bouche',
 'Labelle',
 'Lamb',
 'Lasgo',
 'Lemon Jelly',
 'Lewis Taylor',
 'Llorca',
 'Lollipop',
 'Lou Bega',
 'Louie Austen',
 'Mandalay',
 'Mariah Carey',
 'Marilyn Manson',
 'Mark Rae',
 'Martina Topley-Bird',
 'Masculados',
 'Massive Attack',
 'Micatone',
 'Missing Heart',
 "Mo' Horizons",
 'Moby',
 'Mocean Worker',
 'Modjo',
 'Mondo Grosso',
 'Morcheeba',
 'Morrissey',
 'Nathan Fake',
 'Nathaniel Merriweather',
 'New Order',
 'Nicola Conte',
 'Nightmares On Wax',
 'Nils Petter Molvær',
 'Nina Simone',
 'Nine Inch Nails',
 'Novaspace',
 'O-Zone',
 'Oasis',
 'Ocean Colour Scene',
 'Ochre',
 'Omar',
 'Opto',
 'Orbital',
 'Orgy',
 'Oscar G & Ralph Falcon',
 'Paffendorf',
 'Paul Kalkbrenner',
 'Paul Oakenfold',
 'Paul van Dyk',
 'Pauline London',
 'Peaches',
 'Pet Shop Boys',
 'Plaid',
 'Povo',
 'Praise Cats',
 'Prefuse 73',
 'Prezioso',
 'Quantic',
 'RJD2',
 'Radioactive Man',
 'Reflekt',
 'Richard Hall',
 'Rimini Project',
 'Rollergirl',
 'Roni Size',
 'Ronny Jordan',
 'Rouge Rouge',
 'Roxie',
 'Röyksopp',
 'S-Tone Inc',
 'SMiLE.dk',
 'Safri Duo',
 'Saint Privat',
 'Sandee Chan',
 'Sasha',
 'Scatman John',
 'Schmoov!',
 'Scooter',
 'ScubaZ',
 'Seek',
 'Sexbomb Girls',
 'Shakedown',
 'Shazz',
 'Skalpel',
 'Soel',
 'Solid Base',
 'Solsonics',
 'Soulsearcher',
 'Soulstice',
 'Special D.',
 'Squarepusher',
 'St Germain',
 'Static-X',
 'Summer Love',
 'Sweet Trip',
 'TM Juke',
 'Takkyu Ishino',
 'Telefon Tel Aviv',
 'The Chemical Brothers',
 'The Cinematic Orchestra',
 'The Crystal Method',
 'The Dining Rooms',
 'The Karminsky Experience Inc.',
 'The Mighty Bop',
 'The Prodigy',
 'The RH Factor',
 'The Underdog Project',
 'Thievery Corporation',
 'Tiësto',
 'Tom & Joy',
 'Tortured Soul',
 'Tosca',
 'Twinset',
 'Two Lone Swordsmen',
 'Télépopmusik',
 'UNKLE',
 'Underworld',
 'Urbs & Cutex',
 'Us3',
 'Variety Lab',
 'Vengaboys',
 'Vhen Bautista',
 'Vhong Navarro',
 'Visage',
 'Wagon Christ',
 'Wax Poetic',
 'Way Out West',
 'Yonderboi',
 'Zero 7',
 '[re:jazz]',
 'alva noto',
 'edIT',
 'm.o.v.e',
 'noonday underground',
 'paris match',
 'sora',
 'weirdo girl'}

In [12]:
len(artistas_unicos)

293

In [13]:
df_electronica_3 = pd.DataFrame(artistas_unicos)

df_electronica_3

                  0
0        Sweet Trip
1          DJs@Work
2    Marilyn Manson
3         Divinorum
4            Zero 7
..              ...
288         Herbert
289          Enigma
290             Air
291         Da Hool
292      St Germain

[293 rows x 1 columns]

In [14]:
df_electronica_3.to_csv('artistas_electronica.csv', index=False, encoding="utf-8")

In [15]:
artistas_a_consultar = artistas_unicos #comprobamos que funciona
lista_artistas = []
for nombre_artista in artistas_a_consultar:
    
    datos_artista = llamar_lastfm_api('artist.getinfo', nombre_artista, cliente)
    if datos_artista and 'artist' in datos_artista:
        artista_data = datos_artista['artist']
        oyentes = artista_data.get('stats', {}).get('listeners', 'arista no encontrado')
        reproducciones = artista_data.get('stats', {}).get('playcount', 'N/D')
        bio_content = artista_data.get('bio', {}).get('content', '')
        if not bio_content or bio_content.strip() == "":
            bio_resumen = 'biografia no encontrada'
        else:
            bio_resumen = artista_data.get('bio', {}).get('summary')
        lista_artistas_dict = {'artista': artista_data.get('name', nombre_artista),'oyentes': oyentes, 'reproducciones': reproducciones, 'bio_resumen': bio_resumen}
        lista_artistas.append(lista_artistas_dict)
       
    else:
        print(f"No se pudo obtener información de {nombre_artista}")

In [ ]:
#dataframe de la lista final extraida de lastfm
df_electronica_2 = pd.DataFrame(lista_artistas)

df_electronica_2

,artista,oyentes,reproducciones,bio_resumen
0,Sweet Trip,737261,38365288,Sweet Trip was an American glitch pop and expe...
1,DJs@Work,14546,80420,biografia no encontrada
2,Marilyn Manson,3105873,192589529,Marilyn Manson is an American rock band formed...
3,Divinorum,6491,59073,"1.Divinorum produces big, lush, full-on trance..."
4,Zero 7,1779114,51943861,"Zero 7 is a London, UK downtempo duo, consisti..."
...,...,...,...,...
288,Herbert,265633,3600347,Matthew Herbert is an electronic music produce...
289,Enigma,1376849,51142179,There is more than one artist with the name En...
290,Air,3088535,132206585,"Air is a French music duo from Versailles, con..."
291,Da Hool,225755,1227866,"Frank Tomiczek (born 30 December 1968), known ..."
292,St Germain,312147,4283653,St. Germain is the stage name of Ludovic Navar...