In [1]:
import requests
import json
import pandas as pd

In [ ]:
cliente = "micliente"
secreto = "misecreto"

In [3]:
url_api = "http://ws.audioscrobbler.com/2.0/"

In [4]:
def llamar_lastfm_api(method, artist_name, cliente):

        params = {'method': method,'artist': artist_name,'api_key': cliente,'format': 'json'}

        response = requests.get(url_api, params=params)


        if response.status_code == 200:
            return response.json()
        else:
            print(f"Error {response.status_code}: No se pudo obtener la información para el método {method}")
            return

In [5]:
artistas_a_consultar_prueba = ["Greg Brown", "James Intveld", "Joe Bonamassa", "Sean Costello",  "Eric Clapton"]
lista_artistas_prueba = []


for nombre_artista in artistas_a_consultar_prueba:
    print(f"--- Consultando: {nombre_artista} ---")
    
    datos_artista = llamar_lastfm_api('artist.getinfo', nombre_artista, cliente)  
    
    
    if datos_artista and 'artist' in datos_artista:
        
        artista_data = datos_artista['artist']
        
        
        oyentes = artista_data.get('stats', {}).get('listeners', 'arista no encontrado') 
        reproducciones = artista_data.get('stats', {}).get('playcount', 'N/D')
        
        bio_content = artista_data.get('bio', {}).get('content', '')
        
        if not bio_content or bio_content.strip() == "":
            bio_resumen = 'biografia no encontrada'
        else:
            bio_resumen = artista_data.get('bio', {}).get('summary')
        
        lista_artistas_dict = {'artista': artista_data.get('name', nombre_artista),'oyentes': oyentes, 'reproducciones': reproducciones, 'bio_resumen': bio_resumen}
        lista_artistas_prueba.append(lista_artistas_dict)
        
        print(f"Datos de {nombre_artista} procesados y guardados.")
           
    else:
        print(f"No se pudo obtener información de {nombre_artista}")

--- Consultando: Greg Brown ---
Datos de Greg Brown procesados y guardados.
--- Consultando: James Intveld ---
Datos de James Intveld procesados y guardados.
--- Consultando: Joe Bonamassa ---
Datos de Joe Bonamassa procesados y guardados.
--- Consultando: Sean Costello ---
Datos de Sean Costello procesados y guardados.
--- Consultando: Eric Clapton ---
Datos de Eric Clapton procesados y guardados.

In [6]:
lista_artistas_prueba

[{'artista': 'Greg Brown',
  'oyentes': '91255',
  'reproducciones': '1141017',
  'bio_resumen': 'Greg Brown is a folk musician from Iowa, USA. His "Iowa Waltz" has been (unsuccessfully) proposed to replace the state song of Iowa.\n\nDuring the 1980s, his reputation was established through frequent touring and recurring performances on A Prairie Home Companion. Subsequently, his work has been nominated for Grammy awards. He also founded his own record label and named it Red House Records after a home he lived in in Iowa.  Red House Records is an independent record label specializing in folk music, based in St. <a href="https://www.last.fm/music/Greg+Brown">Read more on Last.fm</a>'},
 {'artista': 'James Intveld',
  'oyentes': '20989',
  'reproducciones': '192278',
  'bio_resumen': '\nA native of Los Angeles, he started his career at an early age listening and singing along to his parents\' recordings of Hank Williams, Sr., Dean Martin, Lefty Frizzell, and Elvis. By high school he was playing in cover bands and was soon a regular sitting in with the house band at the legendary Palomino Club.\n\nInitially, Intveld worked with his younger brother Ricky and friend Pat Woodward in a band known as the Rockin\' Shadows. The group dissolved <a href="https://www.last.fm/music/James+Intveld">Read more on Last.fm</a>'},
 {'artista': 'Joe Bonamassa',
  'oyentes': '475577',
  'reproducciones': '13852116',
  'bio_resumen': 'Joe Bonamassa (born May 8, 1977) is an American blues rock  guitarist, singer and songwriter.\n\nBonamassa was born in Utica, New York. He started playing guitar at age four, encouraged by his father, who was an avid music fan and exposed him to British blues rock records by Eric Clapton and Jeff Beck, greatly inspiring him. At 11 years old Joe was mentored and trained by American guitar legend, Danny Gatton. When he was 12 years old, he had his own band called Smokin\' Joe Bonamassa <a href="https://www.last.fm/music/Joe+Bonamassa">Read more on Last.fm</a>'},
 {'artista': 'Sean Costello',
  'oyentes': '12642',
  'reproducciones': '155294',
  'bio_resumen': 'April 16, 1979-April 15, 2008\n\nBorn in Philadelphia, Costello began playing guitar at age nine, about the time his family moved to Atlanta. He came of age early, appearing regularly in clubs before he could drive, much less gain legal admission, to them. At age 14, his winning performance in the finals of the Memphis Blues Society’s talent competition had career-changing effects. First, it netted him studio time to record his debut album, Call The Cops, a collection of 1940s and 1950s-style Chicago blues. <a href="https://www.last.fm/music/Sean+Costello">Read more on Last.fm</a>'},
 {'artista': 'Eric Clapton',
  'oyentes': '3345918',
  'reproducciones': '79870206',
  'bio_resumen': 'Eric Patrick Clapton CBE (born 30 March 1945) is an English rock and blues guitarist, singer, and songwriter. He is regarded as one of the most successful and influential guitarists in rock music. He ranked second in Rolling Stone\'s list of the "100 Greatest Guitarists of All Time" and fourth in Gibson\'s "Top 50 Guitarists of All Time". In 2023, Rolling Stone named Clapton the 35th best guitarist of all time. He was also named number five in Time magazine\'s list of "The 10 Best Electric Guitar Players" in 2009. <a href="https://www.last.fm/music/Eric+Clapton">Read more on Last.fm</a>'}]

In [7]:
datos_artista.keys()

dict_keys(['artist'])

In [8]:
datos_artista['artist'].keys()

dict_keys(['name', 'mbid', 'url', 'image', 'streamable', 'ontour', 'stats', 'similar', 'tags', 'bio'])

In [10]:
datos_artista['artist']['bio']

{'links': {'link': {'#text': '',
   'rel': 'original',
   'href': 'https://last.fm/music/Eric+Clapton/+wiki'}},
 'published': '11 Feb 2006, 05:06',
 'summary': 'Eric Patrick Clapton CBE (born 30 March 1945) is an English rock and blues guitarist, singer, and songwriter. He is regarded as one of the most successful and influential guitarists in rock music. He ranked second in Rolling Stone\'s list of the "100 Greatest Guitarists of All Time" and fourth in Gibson\'s "Top 50 Guitarists of All Time". In 2023, Rolling Stone named Clapton the 35th best guitarist of all time. He was also named number five in Time magazine\'s list of "The 10 Best Electric Guitar Players" in 2009. <a href="https://www.last.fm/music/Eric+Clapton">Read more on Last.fm</a>',
 'content': 'Eric Patrick Clapton CBE (born 30 March 1945) is an English rock and blues guitarist, singer, and songwriter. He is regarded as one of the most successful and influential guitarists in rock music. He ranked second in Rolling Stone\'s list of the "100 Greatest Guitarists of All Time" and fourth in Gibson\'s "Top 50 Guitarists of All Time". In 2023, Rolling Stone named Clapton the 35th best guitarist of all time. He was also named number five in Time magazine\'s list of "The 10 Best Electric Guitar Players" in 2009.\n\nAfter playing in a number of different local bands, Clapton joined the Yardbirds from 1963 to 1965, and John Mayall & the Bluesbreakers from 1965 to 1966. After leaving Mayall, he formed the power trio Cream with drummer Ginger Baker and bassist/vocalist Jack Bruce, in which Clapton played sustained blues improvisations and "arty, blues-based psychedelic pop". After four successful albums, Cream broke up in November 1968. Clapton then formed the blues rock band Blind Faith with Baker, Steve Winwood, and Ric Grech, recording one album and performing on one tour before they broke up. Clapton then toured with Delaney & Bonnie and recorded his first solo album in 1970, before forming Derek and the Dominos with Bobby Whitlock, Carl Radle and Jim Gordon. Like Blind Faith, the band only lasted one album, Layla and Other Assorted Love Songs, which includes "Layla", one of Clapton\'s signature songs.\n\nClapton continued to record a number of successful solo albums and songs over the next several decades, including a 1974 cover of Bob Marley\'s "I Shot the Sheriff" (which helped reggae reach a mass market), the country-infused Slowhand album (1977) and the pop rock of 1986\'s August. Following the death of his son Conor in 1991, Clapton\'s grief was expressed in the song "Tears in Heaven", which appeared on his Unplugged album. In 1996 he had another top-40 hit with the R&B crossover "Change the World". In 1998, he released the Grammy award-winning "My Father\'s Eyes". Since 1999, he has recorded a number of traditional blues and blues rock albums and hosted the periodic Crossroads Guitar Festival. His most recent studio album is Happy Xmas (2018).\n\nClapton has received 18 Grammy Awards as well as the Brit Award for Outstanding Contribution to Music. In 2004, he was awarded a CBE for services to music. He has received four Ivor Novello Awards from the British Academy of Songwriters, Composers and Authors, including the Lifetime Achievement Award. He is the only three-time inductee to the Rock and Roll Hall of Fame: once as a solo artist, and separately as a member of the Yardbirds and of Cream. In his solo career, he has sold more than 280 million records worldwide, making him one of the best-selling musicians of all time. In 1998, Clapton, a recovering alcoholic and drug addict, founded the Crossroads Centre on Antigua, a medical facility for those recovering from substance abuse. <a href="https://www.last.fm/music/Eric+Clapton">Read more on Last.fm</a>. User-contributed text is available under the Creative Commons By-SA License; additional terms may apply.'}

In [11]:
datos_artista['artist']['bio']['content']

'Eric Patrick Clapton CBE (born 30 March 1945) is an English rock and blues guitarist, singer, and songwriter. He is regarded as one of the most successful and influential guitarists in rock music. He ranked second in Rolling Stone\'s list of the "100 Greatest Guitarists of All Time" and fourth in Gibson\'s "Top 50 Guitarists of All Time". In 2023, Rolling Stone named Clapton the 35th best guitarist of all time. He was also named number five in Time magazine\'s list of "The 10 Best Electric Guitar Players" in 2009.\n\nAfter playing in a number of different local bands, Clapton joined the Yardbirds from 1963 to 1965, and John Mayall & the Bluesbreakers from 1965 to 1966. After leaving Mayall, he formed the power trio Cream with drummer Ginger Baker and bassist/vocalist Jack Bruce, in which Clapton played sustained blues improvisations and "arty, blues-based psychedelic pop". After four successful albums, Cream broke up in November 1968. Clapton then formed the blues rock band Blind Faith with Baker, Steve Winwood, and Ric Grech, recording one album and performing on one tour before they broke up. Clapton then toured with Delaney & Bonnie and recorded his first solo album in 1970, before forming Derek and the Dominos with Bobby Whitlock, Carl Radle and Jim Gordon. Like Blind Faith, the band only lasted one album, Layla and Other Assorted Love Songs, which includes "Layla", one of Clapton\'s signature songs.\n\nClapton continued to record a number of successful solo albums and songs over the next several decades, including a 1974 cover of Bob Marley\'s "I Shot the Sheriff" (which helped reggae reach a mass market), the country-infused Slowhand album (1977) and the pop rock of 1986\'s August. Following the death of his son Conor in 1991, Clapton\'s grief was expressed in the song "Tears in Heaven", which appeared on his Unplugged album. In 1996 he had another top-40 hit with the R&B crossover "Change the World". In 1998, he released the Grammy award-winning "My Father\'s Eyes". Since 1999, he has recorded a number of traditional blues and blues rock albums and hosted the periodic Crossroads Guitar Festival. His most recent studio album is Happy Xmas (2018).\n\nClapton has received 18 Grammy Awards as well as the Brit Award for Outstanding Contribution to Music. In 2004, he was awarded a CBE for services to music. He has received four Ivor Novello Awards from the British Academy of Songwriters, Composers and Authors, including the Lifetime Achievement Award. He is the only three-time inductee to the Rock and Roll Hall of Fame: once as a solo artist, and separately as a member of the Yardbirds and of Cream. In his solo career, he has sold more than 280 million records worldwide, making him one of the best-selling musicians of all time. In 1998, Clapton, a recovering alcoholic and drug addict, founded the Crossroads Centre on Antigua, a medical facility for those recovering from substance abuse. <a href="https://www.last.fm/music/Eric+Clapton">Read more on Last.fm</a>. User-contributed text is available under the Creative Commons By-SA License; additional terms may apply.'

In [12]:
df = pd.read_csv("df_blues.csv")

In [13]:
df

,Artista,Género,Tipo,Nombre,Año,ID
0,Greg Brown,blues,track,Blue Car,2000,3gIRDIOGmLc1WBhlcv35O5
1,James Intveld,blues,track,Love Calls,2000,3x5EuJxLpjk0vIV5iMpd1i
2,Murali Coryell,blues,track,Softly Let Me Kiss Your Lips,2000,5cDIbJtehjhImG8eytKwGw
3,Joe Bonamassa,blues,track,"Miss You, Hate You",2000,270fcAQl6cPF3S3ZQiPNon
4,Sean Costello,blues,track,Double Trouble,2000,0DeGKiRiCK6Hv8ivuojSdH
...,...,...,...,...,...,...
745,Mark Knopfler,blues,track,Song For Sonny Liston,2004,7CEB9EWKgL5kC1HTO8Oru7
746,Muddy Waters Blues Band,blues,track,Everything Gonna Be Alright,2004,5VK783FVcaNdsx5iN0O7dN
747,Carl Weathersby,blues,track,Hold On,2004,6hvJliJvOMHiKSXjPyUoZf
748,Albert Cummings,blues,track,Blues Makes Me Feel So Good,2004,5T1sj4W2NIUlbmZMdZmAI3
749,Jools Holland,blues,track,St. James' Infirmary Blues,2004,6TSgebnc69Ndnw52rffHJV

In [14]:
df['Artista']

0                   Greg Brown
1                James Intveld
2               Murali Coryell
3                Joe Bonamassa
4                Sean Costello
                ...
745              Mark Knopfler
746    Muddy Waters Blues Band
747            Carl Weathersby
748            Albert Cummings
749              Jools Holland
Name: Artista, Length: 750, dtype: object

In [15]:
artista = df['Artista']

In [16]:
artista_unico = set(artista)

In [17]:
artista_unico

{'Aerosmith',
 'Alabama 3',
 'Albert Cummings',
 "Albert Lee & Hogan's Heroes",
 'Alicia Keys',
 'Allman Brothers Band',
 'Alvin Lee',
 'Amy Winehouse',
 'Ana Popovic',
 'Andy Lee Lang',
 'Ann Nesby',
 'Art Blakey & The Jazz Messengers',
 'Arthur "Big Boy" Crudup',
 'B.B. King',
 'Barbra Streisand',
 'Ben B. Beckendorf',
 'Benny Neyman',
 'Bessie Smith',
 'Big Bill Broonzy',
 'Big Mama Thornton',
 "Bill Wyman's Rhythm Kings",
 'Billie Holiday',
 'Blue Stew',
 'Blues Company',
 'Bobby Wayne',
 'Bonnie Raitt',
 'Brad Paisley',
 'Buddaheads',
 'Buddy Guy',
 'Byther Smith',
 'C.C. Adcock',
 'CHRISTIAN PADOVAN',
 'Calvin Russell',
 'Carl Weathersby',
 'Cave Catt Sammy',
 'Champion Jack Dupree',
 'Charlie Parker',
 'Chet Atkins',
 'Chick Willis',
 'Chris Smither',
 'Chris Thomas King',
 'Clarence "Gatemouth" Brown',
 'Coco Montoya',
 'Coen Wolters Band',
 'Dany Brillant',
 'David "Honeyboy" Edwards',
 'David Gogo',
 'De-Phazz',
 'Debbie Davies',
 'Deborah Coleman',
 'Delbert McClinton',
 'Denise LaSalle',
 'Dick Brave & The Backbeats',
 'Don Vilanova Botafogo',
 'Doyle Bramhall',
 'Doyle Bramhall II',
 'Dr. Feelgood',
 'Dr. John',
 'Earl King',
 'Eddie Hope',
 'Eddy Wilsons Blues Band',
 'Ellis Hall',
 'Elmore James',
 'Elvis Presley',
 'Eric Bibb',
 'Eric Burdon',
 'Eric Clapton',
 'Eric Sardinas',
 'Esther Phillips',
 'Etta James',
 'Freddie King',
 'Free',
 'Gary Moore',
 'George Thorogood & The Destroyers',
 'Gomez',
 "Gov't Mule",
 'Grant Green',
 'Greg Brown',
 'Guitar Shorty',
 'Guru',
 'Guy Davis',
 'Hanne Boel',
 'Heaven & Earth',
 'Heidi Hauge',
 'Horace Silver',
 "Howlin' Wolf",
 'Ivory Joe Hunter',
 'J. B. Hutto',
 'J.B. Lenoir',
 'James Intveld',
 'Jamie Cullum',
 'Jeffrey Foucault',
 'Jimmie Vaughan',
 'Jimmy "T99" Nelson',
 'Jimmy LaFave',
 'Jimmy Rogers',
 'Jimmy Smith',
 'Jimmy Thackery',
 'Jimmy Thackery And The Drivers',
 'Joe Bonamassa',
 'Joe Cocker',
 'Joe Dassin',
 'John Hammond',
 'John Littlejohn',
 'John Mayall',
 'John Mayall & The Bluesbreakers',
 'Johnny & The Jailbirds',
 'Johnny Boyd',
 "Johnny Burnette & The Rock 'N' Roll Trio",
 'Johnny Nicholas',
 'Johnny Winter',
 'Jools Holland',
 'Juicy Lucy',
 'Julian Sas',
 'Junior Wells',
 "Keb' Mo'",
 'Keith Urban',
 'Kieran Kane',
 'Kirk Fletcher',
 'Koko Taylor',
 'La Mississippi',
 'Lead Belly',
 'Lee Rocker',
 'Lighthouse Family',
 "Lightnin' Hopkins",
 'Lil Ed & The Blues Imperials',
 'Little Milton',
 'Lonnie Brooks',
 'Los DelTonos',
 'Los Lonely Boys',
 'Lucille Bogan',
 'Lucky Lloyd',
 'Lucky Peterson',
 'Luther Allison',
 'Luther Johnson',
 'Magic Sam',
 'Magic Slim',
 'Magic Slim & The Teardrops',
 'Marc Broussard',
 'Marcia Ball',
 'Mario Bradley',
 'Mark Knopfler',
 'Mark Selby',
 'Mem Shannon',
 'Memphis La Blusera',
 'Michael Bublé',
 'Michael Burks',
 'Mighty Mo Rodgers',
 'Mighty Sam McClain',
 'Mike Sanchez',
 'Mississippi John Hurt',
 'Mitch Woods and His Rocket 88‘S',
 'Mojo Blues Band',
 'Monkey Beat',
 'Mr. Airplane Man',
 'Ms. Lauryn Hill',
 'Muddy Waters',
 'Muddy Waters Blues Band',
 'Murali Coryell',
 'Nappy Brown',
 'Nick Moss & The Flip Tops',
 'Nina Simone',
 'Nitty Gritty Dirt Band',
 'Norah Jones',
 'Otis Taylor',
 'Patrick Yandall',
 'Peter Green Splinter Group',
 'Popa Chubby',
 'R.L. Burnside',
 'RJD2',
 'Randy Crawford',
 'Rascal Flatts',
 'Ray Bonneville',
 'Ray Charles',
 "Ray Collins' Hot Club",
 'Red Stick Ramblers',
 'Rob Tognoni',
 'Robben Ford',
 'Robert Belfour',
 'Robert Cray',
 'Robert Johnson',
 'Robert Randolph & The Family Band',
 'Rod Stewart',
 'Rory Gallagher',
 'Rusty Zinn',
 'Ruth Brown',
 'SEATBELTS',
 'Saffire-The Uppity Blues Women',
 'Sam Cooke',
 'Sam Myers',
 'Sammy Price',
 'Santana',
 'Sean Costello',
 'Shemekia Copeland',
 'Simon Crashly & The Roadmasters',
 'Sista Monica',
 'Sister Rosetta Tharpe',
 'Sister Swing',
 'Slim Harpo',
 'Snowy White',
 'Soledad Brothers',
 'Solomon Burke',
 'Son House',
 'Son Seals',
 'Sonny Boy Williamson I',
 'Sonny Rollins',
 'Stan Webb',
 'Status Quo',
 'Steve Vaus',
 'Stevie Ray Vaughan',
 'Sue Foley',
 'Susan Tedeschi',
 'Tab Benoit',
 'Tadg Galleran',
 'Ten Years After',
 'The Band',
 'The Beat Daddys',
 'The Bel-Aires',
 'The Bellfuries',
 'The Black Keys',
 'The Blues Brothers',
 'The Brian Setzer Orchestra',
 'The Crew Cuts',
 'The Derek Trucks Band',
 'The Ditty Bops',
 'The Holmes Brothers',
 'The Hoodoo Kings',
 'The Inmates',
 'The Limp Twins',
 'The Nimmo Brothers',
 'The Notorious Cherry Bombs',
 'The Quantic Soul Orchestra',
 'The Refreshments',
 'The Robert Cray Band',
 'The Rolling Stones',
 'The White Stripes',
 'Tom Waits',
 'Tommy Castro',
 'Tommy Johnson',
 'Tony Bennett',
 'Twelve Bar Blues Band',
 'Uriah Heep',
 'Vargas Blues Band',
 'W.C. Clark',
 'Walter Trout and The Free Radicals',
 'Wes Montgomery',
 'Wynonie Harris',
 'Xavier Rudd',
 'ZZ Top',
 'Zucchero'}

In [18]:
len(artista_unico)

250

In [19]:
artistas_a_consultar = artista_unico
lista_artistas = []


for nombre_artista in artistas_a_consultar:
    
    datos_artista = llamar_lastfm_api('artist.getinfo', nombre_artista, cliente)  
    
    
    if datos_artista and 'artist' in datos_artista:
        
        artista_data = datos_artista['artist']
        
        
        oyentes = artista_data.get('stats', {}).get('listeners', 'arista no encontrado') 
        reproducciones = artista_data.get('stats', {}).get('playcount', 'N/D')
        
        bio_content = artista_data.get('bio', {}).get('content', '')
        
        if not bio_content or bio_content.strip() == "":
            bio_resumen = 'biografia no encontrada'
        else:
            bio_resumen = artista_data.get('bio', {}).get('summary')
        
        lista_artistas_dict = {'artista': artista_data.get('name', nombre_artista),'oyentes': oyentes, 'reproducciones': reproducciones, 'bio_resumen': bio_resumen}
        lista_artistas.append(lista_artistas_dict)
        
    
           
    else:
        print(f"No se pudo obtener información de {nombre_artista}")

In [20]:
# --- 1. DICCIONARIO BASE (PAÍS: GENTILICIO) ---
# Usamos el diccionario que generamos previamente:
PAIS_A_GENTILICIO = {
    "Afghanistan": "Afghan",
    "Albania": "Albanian",
    "Algeria": "Algerian",
    "Argentina": "Argentinian",
    "Australia": "Australian",
    "Austria": "Austrian",
    "Belgium": "Belgian",
    "Bolivia": "Bolivian",
    "Brazil": "Brazilian",
    "Canada": "Canadian",
    "Chile": "Chilean",
    "China": "Chinese",
    "Colombia": "Colombian",
    "Costa Rica": "Costa Rican",
    "Cuba": "Cuban",
    "Denmark": "Dane",
    "Egypt": "Egyptian",
    "France": "French",
    "Germany": "German",
    "Greece": "Greek",
    "India": "Indian",
    "Indonesia": "Indonesian",
    "Ireland": "Irish",
    "Italy": "Italian",
    "Jamaica": "Jamaican",
    "Japan": "Japanese",
    "Mexico": "Mexican",
    "Netherlands": "Dutch",
    "New Zealand": "New Zealander",
    "Nigeria": "Nigerian",
    "Norway": "Norwegian",
    "Peru": "Peruvian",
    "Poland": "Pole",
    "Portugal": "Portuguese",
    "Russia": "Russian",
    "South Korea": "South Korean",
    "Spain": "Spaniard",
    "Sweden": "Swede",
    "Turkey": "Turk",
    "Ukraine": "Ukrainian",
    "United Kingdom": "Briton",
    "United States": "American",
    "United States_adj": "American",
    "United Kingdom_adj": "British",
    "France_adj": "French",
    "Germany_adj": "German",
    "Spain_adj": "Spanish"}
# --- 2. DICCIONARIO INVERTIDO PARA BÚSQUEDA EFICIENTE ---
# Clave: Gentilicio (lo que busco en la bio), Valor: País
GENTILICIO_A_PAIS = {gentilicio.lower(): pais.replace('_adj', '')
    for pais, gentilicio in PAIS_A_GENTILICIO.items()}

In [21]:
def extraer_pais_de_biografia(bio_resumen, gentilicio_a_pais_map):
    bio_normalizada = bio_resumen.lower()
    for gentilicio, pais in gentilicio_a_pais_map.items():
        # Usamos ' ' + gentilicio + ' ' para buscar la palabra completa y evitar coincidencias parciales
        if f' {gentilicio} ' in bio_normalizada or bio_normalizada.startswith(f'{gentilicio} '):
            return pais
        # Caso especial para "is an American rock band" (no tiene espacio antes)
        if bio_normalizada.endswith(gentilicio):
             return pais
    return 'Unknown'

In [22]:
for artista_data in lista_artistas:
    bio = artista_data['bio_resumen']
    pais_encontrado = extraer_pais_de_biografia(bio, GENTILICIO_A_PAIS)
    artista_data['pais'] = pais_encontrado #aqui agregamos la clave pais en nuestro diccionario

In [23]:
lista_artistas

[{'artista': 'W.C. Clark',
  'oyentes': '9252',
  'reproducciones': '41127',
  'bio_resumen': 'W.C. Clark (born Wesley Curley Clark in Austin, TX, on 16 November 1939; died 2 March 2024) was an American blues musician remembered as the "Godfather of Austin Blues" for his influence on the Austin, TX, blues scene since the late 1960s. \n\nIn the late 1960s, Clark joined the Joe Tex band. After forming several bands with various names, Clark formed the W.C. Clark Blues Revue in 1975. \n\n“Modern Texas blues at its best…impeccable, soothing soul and flashy <a href="https://www.last.fm/music/W.C.+Clark">Read more on Last.fm</a>',
  'pais': 'United States'},
 {'artista': 'Chet Atkins',
  'oyentes': '293379',
  'reproducciones': '3200761',
  'bio_resumen': 'Chester Burton Atkins born 20 June 1924 - Died 30 June 2001 in Nashville, Tennessee, United States (1942–1996) . was an American guitarist and record producer. Together with Owen Bradley, Atkins created the smoother country music style known as the Nashville sound, which expanded country music\'s appeal to include adult pop music fans as well. His virtuoso picking style - inspired by Merle Travis, Django Reinhardt, George Barnes and Les Paul - brought him admirers both within and outside the country scene. <a href="https://www.last.fm/music/Chet+Atkins">Read more on Last.fm</a>',
  'pais': 'United States'},
 {'artista': 'Sue Foley',
  'oyentes': '36605',
  'reproducciones': '313880',
  'bio_resumen': 'Sue Foley (born March 29, 1968, Ottawa, Ontario, Canada) is a Canadian blues singer and guitarist. She has also recorded as Peter Karp & Sue Foley. \n\nSince her first album in 1992  Foley has recorded a string of albums, for both Antone\'s Records and Shanachie Records. She has spent many years on the road as a bandleader, lead vocalist, guitarist and manager of her own band. In addition to her own touring, she has also shared the stage with blues musicians such as Back Alley John, B. B. King, Buddy Guy and John Lee Hooker.  <a href="https://www.last.fm/music/Sue+Foley">Read more on Last.fm</a>',
  'pais': 'Canada'},
 {'artista': 'Ellis Hall',
  'oyentes': '5471',
  'reproducciones': '24534',
  'bio_resumen': 'Ellis Hall Jr. (born May 10, 1951 in Savannah, Georgia) known professionally as Ellis Hall is an American singer-songwriter, multi-instrumentalist, actor and composer. He was described as "The Ambassador of Soul" by conductor, Jeff Tyzik. Hall has been blind since the age of 18. Citing Ray Charles as his inspiration, Hall has written over 4000 soul, gospel, blues and pop songs,[1] and has performed with Stevie Wonder, James Taylor, Natalie Cole, Patti LaBelle <a href="https://www.last.fm/music/Ellis+Hall">Read more on Last.fm</a>',
  'pais': 'United States'},
 {'artista': 'The Limp Twins',
  'oyentes': '136255',
  'reproducciones': '998008',
  'bio_resumen': 'The Limp Twins are Will Holland (a.k.a quantic) and Russell Porter, who created their album tales from beyond the groove (TRUCD057, 2003) in their bedrooms (according to the cd cover). The record is a funky offering somewhere in between the sound of Will Holland\'s other projects, quantic and the quantic soul orchestra, but is definately more laid back. \n\nFor more information on this project, check out quantic\'s website: about The Limp Twins. <a href="https://www.last.fm/music/The+Limp+Twins">Read more on Last.fm</a>',
  'pais': 'Unknown'},
 {'artista': 'Jimmy Thackery And The Drivers',
  'oyentes': '17489',
  'reproducciones': '124417',
  'bio_resumen': 'Known for his gritty, blue-collar approach and marathon live shows, Thackery was for many years part of The Nighthawks. The Nighthawks were known as one of the hardest-working blues bar bands in North America.[citation needed] Since the late 1980s, Thackery has been touring under his own name, and has found a wide audience. His hard-edged, tough-as-nails approach to guitar playing and his trio\'s driving rhythm section holds appeal for fans of both traditional blues and roots rock. <a href="https://www.last.fm/music/Jimmy+Thackery+And+The+Drivers">Read more on Last.fm</a>',
  'pais': 'Unknown'},
 {'artista': 'The Holmes Brothers',
  'oyentes': '34197',
  'reproducciones': '197057',
  'bio_resumen': 'The Holmes Brothers were an American musical trio originally from Christchurch, Virginia.\nMixing sounds from blues, soul, gospel, country, and rhythm & blues, they have released twelve studio albums, with three reaching the top 5 on the Billboard Blues Albums chart. They have gained a following by playing regularly at summer folk, blues, gospel, and jazz festivals. They have recorded with Van Morrison, Peter Gabriel, Odetta, Phoebe Snow, Willie Nelson <a href="https://www.last.fm/music/The+Holmes+Brothers">Read more on Last.fm</a>',
  'pais': 'United States'},
 {'artista': 'The Rolling Stones',
  'oyentes': '5674210',
  'reproducciones': '264639939',
  'bio_resumen': 'The Rolling Stones is an English rock band formed in London in 1962. Active for six decades, they are one of the most popular and enduring bands of the rock era. In the early 1960s, the Rolling Stones pioneered the gritty, rhythmically driven sound that came to define hard rock. Their first stable line-up consisted of vocalist Mick Jagger, multi-instrumentalist Brian Jones, guitarist Keith Richards, bassist Bill Wyman, and drummer Charlie Watts. During their formative years <a href="https://www.last.fm/music/The+Rolling+Stones">Read more on Last.fm</a>',
  'pais': 'Unknown'},
 {'artista': 'Jimmy Smith',
  'oyentes': '426313',
  'reproducciones': '3706936',
  'bio_resumen': 'Jimmy Smith (1925–2005) was a jazz musician whose instrument was the Hammond B-3 electric organ.\n\nBorn James Oscar Smith on 8th December 1925 in Norristown, Pennsylvania, USA. Smith was influenced by both gospel and blues. He first achieved prominence in the 1950s where his recordings became popular on jukeboxes before there were commonly used terms to describe his unique musical flavor. In the sixties and seventies he helped create the jazz style known as soul jazz. <a href="https://www.last.fm/music/Jimmy+Smith">Read more on Last.fm</a>',
  'pais': 'Unknown'},
 {'artista': 'Elvis Presley',
  'oyentes': '4315393',
  'reproducciones': '144903841',
  'bio_resumen': 'Elvis Aaron Presley (January 8, 1935 – August 16, 1977) was an American singer and actor. Regarded as one of the most significant cultural icons of the 20th century, he is often referred to as the "King of Rock and Roll" or simply "the King".\n\nPresley was born in Tupelo, Mississippi, and relocated to Memphis, Tennessee, with his family when he was 13 years old. His music career began there in 1954, recording at Sun Records with producer Sam Phillips, who wanted to bring the sound of African American music to a wider audience. <a href="https://www.last.fm/music/Elvis+Presley">Read more on Last.fm</a>',
  'pais': 'United States'},
 {'artista': 'J.B. Lenoir',
  'oyentes': '105961',
  'reproducciones': '663645',
  'bio_resumen': 'J. B. Lenoir /ləˈnɔːr/ (Monticello, Mississippi, March 5, 1929  – Urbana, Illinois, April 29, 1967) was an African American blues guitarist and singer-songwriter, active in the 1950s and 1960s Chicago blues scene.\nLenoir\'s guitar-playing father introduced him to the music of Blind Lemon Jefferson, whose music became a major influence. During the early 1940s, Lenoir worked with blues artists Sonny Boy Williamson II and Elmore James in New Orleans. Lenoir would eventually find musical influence in Arthur Crudup and Lightnin\' Hopkins. <a href="https://www.last.fm/music/J.B.+Lenoir">Read more on Last.fm</a>',
  'pais': 'United States'},
 {'artista': "Bill Wyman's Rhythm Kings",
  'oyentes': '9937',
  'reproducciones': '216487',
  'bio_resumen': 'Bill Wyman\'s Rhythm Kings are a blues-rock band founded in 1997 and led by the Rolling Stones\' bass guitarist Bill Wyman. Together with his lifelong musical partner Terry Taylor. This "Dirty Boys" duo produce, arrange and compose original material for the award-winning band. Members of the band, eithering touring or as studio guests, has included such stars as Peter Frampton, Albert Lee, Gary Brooker, Georgie Fame, Andy Fairweather-Low, Mark Knopfler and Martin Taylor. <a href="https://www.last.fm/music/Bill+Wyman%27s+Rhythm+Kings">Read more on Last.fm</a>',
  'pais': 'Unknown'},
 {'artista': 'Vargas Blues Band',
  'oyentes': '22103',
  'reproducciones': '264146',
  'bio_resumen': '”Javier Vargas was born in Madrid. When he was nine years old, he and his family moved to Argentina, where his parents had lived during the Spanish Civil War. They lived in Mendoza, San Luis, Buenos Aires and also in Mar del Plata, where he started playing the guitar with young musicians in places such as garages. He took guitar lessons, and he also used to go clubs to listen to groups playing blues live.\n\nThe first guitar Vargas had, present from his father, it was a Spanish guitar with naylon strings. <a href="https://www.last.fm/music/Vargas+Blues+Band">Read more on Last.fm</a>',
  'pais': 'Spain'},
 {'artista': 'Lighthouse Family',
  'oyentes': '565149',
  'reproducciones': '6540576',
  'bio_resumen': 'Lighthouse Family was a British pop-soul duo formed in 1993 that rose to prominence in the mid-1990s and initially remained active until 2003. The duo reformed during 2010 to 2011 and again from 2019 before splitting in 2022. \n\nThe duo comprised vocalist Tunde Baiyewu (born in London on 25 November 1968) and keyboard player Paul Tucker, (born in London on 12 August 1968) and formed in 1993 in Newcastle upon Tyne, England after meeting at college. Their 1995 debut album "Ocean Drive" sold more than 1. <a href="https://www.last.fm/music/Lighthouse+Family">Read more on Last.fm</a>',
  'pais': 'United Kingdom'},
 {'artista': 'Dick Brave & The Backbeats',
  'oyentes': '54014',
  'reproducciones': '805885',
  'bio_resumen': 'Dick Brave & The Backbeats is a rockabilly cover band from germany best known for their electrifing 50s-style performances of pop/rock classics such as Depeche Mode\'s "I Just Can\'t Get Enough", Green Day\'s "American Idiot" or the Queens Of The Stone Age\'s "No One Knows". \n\nThough band leader Dick Brave claims to be canadian, the project actually marks the unlikely evolution of german pop singer Sasha - a frequent guest in the pop charts during the 1990s with hits like I Feel Lonely, If You Believe or Young Deenay\'s Walk On By. <a href="https://www.last.fm/music/Dick+Brave+&+The+Backbeats">Read more on Last.fm</a>',
  'pais': 'Germany'},
 {'artista': 'Ms. Lauryn Hill',
  'oyentes': '1326796',
  'reproducciones': '35386645',
  'bio_resumen': 'Lauryn Noelle Hill (born May 26, 1975) is an American rapper, singer, songwriter, record producer, and actress. She is celebrated as one of the most influential musical artists of her generation. Hill is credited with breaking barriers for female rappers, contributing to the mainstream success of both hip-hop and neo soul, and blending rap with melodic vocals. She has been honored as one of the 50 Great Voices by NPR, and one of the 200 Greatest Singers of All Time by Rolling Stone. <a href="https://www.last.fm/music/Ms.+Lauryn+Hill">Read more on Last.fm</a>',
  'pais': 'United States'},
 {'artista': 'Joe Dassin',
  'oyentes': '523163',
  'reproducciones': '7352775',
  'bio_resumen': 'Joseph Ira Dassin (November 5, 1938 - August 20, 1980) was a French-speaking American folk, pop and rock musician.\n\nDassin was born in New York City to Jules Dassin (Yiddish actor and film noir director) and Béatrice Launer. He began his childhood first in New York and Los Angeles, California. However after his father became a victim of the anti-communist policies of Senator Joseph McCarthy, he and his family moved from place to place across Europe. <a href="https://www.last.fm/music/Joe+Dassin">Read more on Last.fm</a>',
  'pais': 'United States'},
 {'artista': 'Ann Nesby',
  'oyentes': '20294',
  'reproducciones': '152725',
  'bio_resumen': 'Formerly the lead vocalist for the 30-piece gospel choir Sounds of Blackness, Ann Nesby struck out on her own in 1996 with an album for the Perspective label, Ann Nesby 1996. With the help of super-producers Jam & Lewis, the R&B-oriented LP scored a hit with "I\'m Here for You." Nesby has contributed to several soundtracks (Batman, Mo\' Money, Demolition Man) and tribute albums (to Curtis Mayfield, Marvin Gaye, John Lennon). She has also won two Grammy awards: one as part of Sounds of Blackness for the 1991 album Evolution of Gospel <a href="https://www.last.fm/music/Ann+Nesby">Read more on Last.fm</a>',
  'pais': 'Unknown'},
 {'artista': "Johnny Burnette & The Rock 'n' Roll Trio",
  'oyentes': '48709',
  'reproducciones': '292140',
  'bio_resumen': 'Johnny Burnette & The Rock \'n\' Roll Trio was an American rockabilly group formed in Memphis, Tennessee, during the 1950s. Later recordings were attributed to The Johnny Burnette Trio. The members of the Trio were Dorsey Burnette, his younger brother Johnny Burnette, and a friend Paul Burlison. Dorsey and Johnny Burnette were both natives of Memphis, having been born there in 1932 and 1934 respectively. Paul Burlison was born in Brownsville, Tennessee in 1929, but moved to Memphis with his family in 1937. <a href="https://www.last.fm/music/Johnny+Burnette+&+The+Rock+%27n%27+Roll+Trio">Read more on Last.fm</a>',
  'pais': 'United States'},
 {'artista': "Gov't Mule",
  'oyentes': '297117',
  'reproducciones': '5745334',
  'bio_resumen': 'Gov\'t Mule is a southern rock/jam band formed in 1994 as a side project to The Allman Brothers Band, but has taken on a life of its own. Like many jam bands, Gov\'t Mule does not get much radio airplay but is popular due to constant touring and intense fan loyalty. \n\nWhen the Allman Brothers Band reformed in 1989 in response to the popularity of the Dreams box set, Warren Haynes was added on lead guitar and Allen Woody on bass. The two shared a love for \'60s power trios, like Cream, Jimi Hendrix Experience, and James Gang. <a href="https://www.last.fm/music/Gov%27t+Mule">Read more on Last.fm</a>',
  'pais': 'Unknown'},
 {'artista': 'Patrick Yandall',
  'oyentes': '11358',
  'reproducciones': '80845',
  'bio_resumen': 'Patrick Yandall. Contemporary and smooth jazz guitarist with 14 international releases. He has been featured in Jazziz, Smooth Jazz News, Jazz Times, Guitar Player, and many other print and internet media. A producer and session guitarist based in San Diego, CA. His music has been used in feature film, Television, commercials, Internet media, The Weather Channel, Music Choice, and more! Producer and session musician. Influenced by Larry Carlton, George Benson <a href="https://www.last.fm/music/Patrick+Yandall">Read more on Last.fm</a>',
  'pais': 'Unknown'},
 {'artista': 'Sista Monica',
  'oyentes': '1603',
  'reproducciones': '7736',
  'bio_resumen': 'Sista Monica Parker, aka the “Lioness of the Blues,” is an award-winning blues, soul, and gospel singer, songwriter, producer, public speaker, director and minister of music. A captivating, dynamic performer, today she is one of the most admired women on the international music and festival scene. \n\nSista Monica started singing as a young girl in the church choir in the Midwest between Chicago, Illinois, Gary, Indiana (her home town) and Detroit, Michigan. <a href="https://www.last.fm/music/Sista+Monica">Read more on Last.fm</a>',
  'pais': 'Unknown'},
 {'artista': 'Christian Padovan',
  'oyentes': '4648',
  'reproducciones': '19259',
  'bio_resumen': 'biografia no encontrada',
  'pais': 'Unknown'},
 {'artista': 'Eric Bibb',
  'oyentes': '120830',
  'reproducciones': '1454411',
  'bio_resumen': 'Eric Bibb (b. 1951) is an American blues singer and guitarist, based in London, England, who has made his career largely in Europe.\n\nBibb was born on 16th August 1951 in New York into a musical family. His  father, Leon Bibb, is a trained singer who sang in musical theatre and made a name for himself as part of the 1960s New York folk scene. His uncle was the world-famous jazz pianist and composer John Lewis, of the Modern Jazz Quartet. Family friends included Pete Seeger, Odetta, and actor/singer/activist Paul Robeson, Bibb\'sgodfather. <a href="https://www.last.fm/music/Eric+Bibb">Read more on Last.fm</a>',
  'pais': 'United States'},
 {'artista': 'The Brian Setzer Orchestra',
  'oyentes': '320671',
  'reproducciones': '3873256',
  'bio_resumen': 'Brian Setzer (born April 10, 1959 in New York) is an American guitarist, singer and songwriter whose popular big band orchestra is most appreciated commercially for their swinging take on Christmas holiday classics.\n\nEarly in his career Setzer was a member of the NYC band Bloodless Pharaohs, and later fronted the popular rockabilly revival band, Stray Cats. The Stray Cats particularly caught America\'s attention with the 1982 album Built for Speed <a href="https://www.last.fm/music/The+Brian+Setzer+Orchestra">Read more on Last.fm</a>',
  'pais': 'United States'},
 {'artista': 'Slim Harpo',
  'oyentes': '179297',
  'reproducciones': '1149560',
  'bio_resumen': 'Slim Harpo (11 January 1924 – 31 January 1970) was a blues musician.\n\nBorn James Moore in Lobdel, Louisiana, the eldest in an orphaned family, Moore worked as a longshoreman and building worker during the late 1930s and early 1940s. One of the foremost proponents of post-war rural blues, he began performing in Baton Rouge bars under the name Harmonica Slim. He later accompanied Lightning Slim, his brother-in-law, both live and in the studio, before commencing his own recording career in 1957. <a href="https://www.last.fm/music/Slim+Harpo">Read more on Last.fm</a>',
  'pais': 'Unknown'},
 {'artista': 'Los Lonely Boys',
  'oyentes': '233722',
  'reproducciones': '2133412',
  'bio_resumen': 'Los Lonely Boys is an American Chicano rock power trio from San Angelo, Texas. The band formed in 1996 and plays a style of music they call "Texican Rock n\' Roll," combining elements of rock and roll, Texas blues, brown-eyed soul, country, and Tejano. The band consists of three brothers: Henry Garza (guitar, vocals), Jojo Garza (bass, vocals), and Ringo Garza (drums, vocals).\n\nThe three brothers emerged as a group in Nashville in the 1990s. After moving back to their home state of Texas they recorded their debut album in 2003. <a href="https://www.last.fm/music/Los+Lonely+Boys">Read more on Last.fm</a>',
  'pais': 'United States'},
 {'artista': 'Seatbelts',
  'oyentes': '528836',
  'reproducciones': '13148882',
  'bio_resumen': '\n\nシートベルツ (Seatbelts), the name of the band, according to the fictional description given in the anime series Cowboy Bebop, derives from how the performers wear seatbelts to be safe while they play hardcore jam sessions.\n\nThe band performed the whole soundtrack of the anime series Cowboy Bebop and produced a total of seven albums and one live DVD. Their style is very diverse and ranges from straightforward big band jazz, blues, acoustic ballads, hard rock, country, funk to electronic, hip-hop and experimental compositions/elements. <a href="https://www.last.fm/music/+noredirect/Seatbelts">Read more on Last.fm</a>',
  'pais': 'Unknown'},
 {'artista': 'Stevie Ray Vaughan',
  'oyentes': '1137189',
  'reproducciones': '17905282',
  'bio_resumen': 'Stephen ("Stevie") Ray Vaughan, born in Dallas, Texas (October 3, 1954 – August 27, 1990) was an American blues guitar legend, and is known as one of the most influential blues musicians in history.\n\nStevie Ray had been in numerous bands before joining blues rock combo Stevie Ray Vaughan and Double Trouble in the late 1970\'s.\n \nStevie Ray Vaughan and Double Trouble\'s debut album was released in 1983. The critically acclaimed Texas Flood (1983) featured the top-20 hit Pride and Joy and sold well in both blues and rock circles.  <a href="https://www.last.fm/music/Stevie+Ray+Vaughan">Read more on Last.fm</a>',

In [24]:
#dataframe de la lista final extraida de lastfm (con paises)
df_blues_2 = pd.DataFrame(lista_artistas)

df_blues_2

,artista,oyentes,reproducciones,bio_resumen,pais
0,W.C. Clark,9252,41127,W.C. Clark (born Wesley Curley Clark in Austin...,United States
1,Chet Atkins,293379,3200761,Chester Burton Atkins born 20 June 1924 - Died...,United States
2,Sue Foley,36605,313880,"Sue Foley (born March 29, 1968, Ottawa, Ontari...",Canada
3,Ellis Hall,5471,24534,"Ellis Hall Jr. (born May 10, 1951 in Savannah,...",United States
4,The Limp Twins,136255,998008,The Limp Twins are Will Holland (a.k.a quantic...,Unknown
...,...,...,...,...,...
245,Sam Cooke,1791994,30721445,"Samuel Cooke (born January 22, 1931 in Clarksd...",United States
246,Marc Broussard,284616,2654398,"Marc Broussard (born January 14, 1982) is an A...",United States
247,Ben B. Beckendorf,2006,5275,biografia no encontrada,Unknown
248,Chris Smither,87444,844828,"Chris Smither (born November 11, 1944 in Miami...",United States
249,Chick Willis,4231,17483,"Robert ""Chick"" Willis (September 24, 1934 – De...",Unknown

In [27]:
df_blues_2.to_csv('artistas_blues.csv', index=False, encoding="utf-8")