In [48]:
import requests

from PIL import Image
from io import BytesIO
import matplotlib.pyplot as plt
import pandas as pd
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

import json

import time

In [ ]:

cliente = '######'

In [10]:
# Información que Devuelve artist.getinfo: 
# 1. **Biografía:** en el campo bio. 
# 2. **Popularidad y Estadísticas:** campos listeners (oyentes únicos) y playcount (número total de reproducciones). 
# 3. **Artistas Similares:** Se encuentran en una lista bajo el campo similar.

In [11]:
cliente

genero = 'latin pop' #--> separandolo solo hay que modificar esta variable, es un codigo más limpio que podemos usar todas

limite = 50

parametros = {'method':'tag.getTopArtists', 'tag':genero, 'api_key': cliente,'format':'json', 'limit':limite, 'page':1}

In [12]:
URL = 'http://ws.audioscrobbler.com/2.0/'

respuesta = requests.get(URL, params=parametros)

In [13]:
datos_last_fm = respuesta.json()

In [14]:
len(datos_last_fm['topartists'])

2

In [15]:
claves_top = datos_last_fm['topartists']

In [16]:
claves_top.keys() #attr contiene los metadatos (atributos) de la solicitud, incluyendo la  page.

dict_keys(['artist', '@attr'])

In [17]:
nombre_artista = ['Shakira', 'Morat']
url_api = "http://ws.audioscrobbler.com/2.0/"
lista_artistas = []

In [18]:
def llamar_lastfm_api(method, artist_name, cliente):
        params = {'method': method,'artist': artist_name,'api_key': cliente,'format': 'json'}
        response = requests.get(url_api, params=params)
        if response.status_code == 200:
            return response.json()
        else:
            print(f"Error {response.status_code}: No se pudo obtener la información para el método {method}")
            return
print(f"Obteniendo detalles de: {nombre_artista}")

Obteniendo detalles de: ['Shakira', 'Morat']

In [19]:
artistas_a_consultar = ["Shakira", "Morat"]
lista_artistas = []
for nombre_artista in artistas_a_consultar:
    print(f"--- Consultando: {nombre_artista} ---")
    datos_artista = llamar_lastfm_api('artist.getinfo', nombre_artista, cliente)
    if datos_artista and 'artist' in datos_artista:
        artista_data = datos_artista['artist']
        oyentes = artista_data.get('stats', {}).get('listeners', 'arista no encontrado')
        reproducciones = artista_data.get('stats', {}).get('playcount', 'N/D')
        bio_content = artista_data.get('bio', {}).get('content', '')
        if not bio_content or bio_content.strip() == "":
            bio_resumen = 'biografia no encontrada'
        else:
            bio_resumen = artista_data.get('bio', {}).get('summary')
        lista_artistas_dict = {'artista': artista_data.get('name', nombre_artista),'oyentes': oyentes, 'reproducciones': reproducciones, 'bio_resumen': bio_resumen}
        lista_artistas.append(lista_artistas_dict)
        print(f"Datos de {nombre_artista} procesados y guardados.")
    else:
        print(f"No se pudo obtener información de {nombre_artista}")

--- Consultando: Shakira ---
Datos de Shakira procesados y guardados.
--- Consultando: Morat ---
Datos de Morat procesados y guardados.

In [20]:
lista_artistas

[{'artista': 'Shakira',
  'oyentes': '4640737',
  'reproducciones': '168412816',
  'bio_resumen': 'Shakira Isabel Mebarak Ripoll is a Colombian singer. Born and raised in Barranquilla, She made her recording debut with Sony Music Colombia at the age of 13. Following the commercial failure of her first two albums, Magia (1991) and Peligro (1993), she rose to prominence in Hispanic countries with her next albums, Pies Descalzos (1995) and Dónde Están los Ladrones? (1998). She entered the English-language market with her fifth album, Laundry Service (2001), which sold over 13 million copies worldwide. <a href="https://www.last.fm/music/Shakira">Read more on Last.fm</a>'},
 {'artista': 'Morat',
  'oyentes': '287335',
  'reproducciones': '20750056',
  'bio_resumen': 'Morat is a Colombian band formed in the country\'s capital city, Bogotá. The band is formed by Juan Pablo Isaza (guitars and vocals), Juan Pablo Villamil (banjo and vocals) and the brothers Simón Vargas (bass and choruses) and Martín Vargas (percussion and choirs). Previously, until the end of 2016, drummer Alejandro Posada had been in the band, but the percussionist had to leave the project, being subsequently replaced by Martín Vargas.\n\nThey began to stand out internationally in 2015 <a href="https://www.last.fm/music/Morat">Read more on Last.fm</a>'}]

In [21]:
## quiero traer mi archivo json y leerlo aquí (load)

In [22]:
ruta_json = 'artistas_latin_pop.json'

In [23]:
with open(ruta_json, 'r', encoding='utf-8') as archivo:
        artistas_a_consultar = json.load(archivo)
        print(f"Lista de artistas: {artistas_a_consultar}")

Lista de artistas: ['La Oreja de Van Gogh', 'Ricky Martin', 'Rodrigo', 'Thalia', 'Rodrigo', 'Los Tucanes De Tijuana', 'Paulina Rubio', 'Chayanne', 'Celia Cruz', 'Rodrigo', 'Rodrigo', 'Juanes', 'Chayanne', 'Thalia', 'Chayanne', 'Laura Pausini', 'Ana Torroja', 'La Oreja de Van Gogh', 'Alejandro Sanz', 'Rodrigo', 'Chayanne', 'Armando Manzanero', 'Donato Y Estefano', 'Paulina Rubio', 'Alejandro Sanz', 'Alejandro Sanz', 'La Oreja de Van Gogh', 'Paulina Rubio', 'Thalia', 'Christina Aguilera', 'Ana Torroja', 'Eros Ramazzotti', 'La Oreja de Van Gogh', 'Eros Ramazzotti', 'La Oreja de Van Gogh', 'Celia Cruz', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'Alejandro Sanz', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'Gloria Estefan', 'Paulina Rubio', 'Christina Aguilera', 'Chayanne', 'Paulina Rubio', 'Alejandro Sanz', 'Alejandro Sanz', 'El Cuarteto De Nos', 'Paulina Rubio', 'Ricardo Arjona', 'El Cuarteto De Nos', 'Celia Cruz', 'Los Tucanes De Tijuana', 'Alejandro Sanz', 'Los Tucanes De Tijuana', 'Nek', 'Beto Quintanilla', 'Walter Olmos', 'Rodrigo', 'Banda XXI', 'Rodrigo', 'Rodrigo', 'Luis Alberto Posada', 'Fey', 'Walter Olmos', 'Rodrigo', 'Thalia', 'Luis Miguel', 'El Cuarteto De Nos', 'Alejandro Sanz', 'Ana Torroja', 'Celia Cruz', 'Ana Torroja', 'El Cuarteto De Nos', 'Ana Torroja', 'Ana Torroja', 'Paulina Rubio', 'Jean Carlos', 'Debelah Morgan', 'Jennifer Lopez', 'Ana Torroja', 'Ana Torroja', 'Rey Ruiz', 'Monica Naranjo', 'Luis Miguel', 'Bertin Osborne', 'Chayanne', 'Alejandro Sanz', 'Alejandro Sanz', 'Alejandro Sanz', 'La Retrocumbia', 'La Retrocumbia', 'La Gran Banda', 'La Retrocumbia', 'Luis Alberto Posada', 'La Retrocumbia', 'La Retrocumbia', 'Walter Olmos', 'Walter Olmos', 'Beto Quintanilla', 'Walter Olmos', 'Tru La La', 'Walter Olmos', 'Julio Iglesias', 'Donato Y Estefano', 'La Oreja de Van Gogh', 'Ana Torroja', 'Luisito Muñoz', 'Jean Carlos', 'Chayanne', 'Ana Torroja', 'Donato Y Estefano', 'Jimmy Bosch', 'Ana Torroja', 'Rodrigo', 'Ricky Martin', 'Juanes', 'Banda XXI', 'Shakira', 'Walter Olmos', 'Donato Y Estefano', 'Alejandro Sanz', 'Donato Y Estefano', 'Luis Alberto Posada', 'Luis Alberto Posada', 'Donato Y Estefano', 'Polo Montañez', 'Ana Torroja', 'Ana Torroja', 'Celia Cruz', 'Issac Delgado', 'Ana Torroja', 'Ana Torroja', 'Thalia', 'Walter Olmos', 'Alejandro Sanz', 'Ana Torroja', 'Nek', 'Julieta Venegas', 'Ana Torroja', 'La Mosca', 'Juanes', 'Ana Torroja', 'El Cuarteto De Nos', 'Rodrigo', 'Luis Alberto Posada', "Los Chaque's", 'Sabroso', 'José José', 'Jean Carlos', 'Shakira', 'Aleks Syntek', 'Diego Torres', 'Shakira', 'Shakira', 'Carlos Vives', 'Laura Pausini', 'Shakira', 'Jennifer Lopez', 'Andrés Cepeda', 'Marc Anthony', 'Shakira', 'Rios De Gloria', 'Bacilos', 'Carlos Vives', 'Guaraná', 'Monica Naranjo', 'Shakira', 'Miguel Bosé', 'Diego Torres', 'Bacilos', 'Marc Anthony', 'Carlos Vives', 'Luis Miguel', 'Miguel Bosé', 'Miguel Bosé', 'Miguel Bosé', 'Alejandro Sanz', 'Raulin Rodriguez', 'Alejandro Sanz', 'Shakira', 'Bacilos', 'Carlos Vives', 'Carlos Vives', 'Miguel Bosé', 'Sin Bandera', 'Enrique Iglesias', 'Sin Bandera', 'Enrique Iglesias', 'Shakira', 'Diego Torres', 'Shakira', 'Shakira', 'Sin Bandera', 'Sin Bandera', 'Cristian Castro', 'Cristian Castro', 'Los Tigres Del Norte', 'Cristian Castro', 'Aleks Syntek', 'Sabroso', 'Los Razos', 'Beto Quintanilla', 'Lemon', 'Jean Carlos', "Mo' Horizons", 'Benny', 'Rodrigo', 'Shakira', 'Bacilos', 'Miguel Bosé', 'Carlos Vives', 'Diego Torres', 'Marc Anthony', 'Marc Anthony', 'Beny Moré', 'Shakira', 'Shakira', 'Enrique Iglesias', 'Shakira', 'Marc Anthony', 'Jennifer Lopez', 'Shakira', 'Laura Pausini', 'Shakira', 'Alejandro Parreño', 'Shakira', 'Jimmy Gutierrez', 'Enrique Iglesias', 'Shakira', 'Shakira', 'Jennifer Lopez', 'Joaquín Sabina', 'Enrique Iglesias', 'Carlos Vives', 'Shakira', 'Rios De Gloria', 'Carlos Vives', 'Miguel Bosé', 'Diego Torres', 'Orquesta Tabaco Y Ron', 'Diego Torres', 'Jennifer Lopez', 'Malú', 'Bacilos', 'Skeewiff', 'Miguel Bosé', 'Los Originales De San Juan', 'Aleks Syntek', 'Glup!', 'Los Cachorros de Juan Villarreal', 'Los Legendarios', 'Miguel Bosé', 'Walter Olmos', 'Tru La La', 'Enrique Iglesias', 'Laura Miller', 'Beto Quintanilla', 'Marc Anthony', 'Sin Bandera', 'Carlos Vives', 'Marc Anthony', 'Walter Olmos', 'Malú', 'Enrique Iglesias', 'Jean Carlos', 'Rodrigo', 'Thalia', 'Alejandra Guzman', 'Huey Dunbar', 'Enrique Iglesias', 'Sin Bandera', 'Ricardo Montaner', 'Sin Bandera', 'Carlos Vives', 'Carlos Vives', 'Diego Torres', 'Clave Cubana', 'La Mona Jimenez', 'Tommy Torres', 'Sabroso', 'Miguel Bosé', 'Chayanne', 'Alejandra Guzman', 'Tru La La', 'Walter Olmos', 'Beto Quintanilla', 'La Barra', 'Beto Quintanilla', 'Enrique Iglesias', 'Diego Torres', 'Clave Cubana', 'Jon Secada', 'Alejandra Guzman', 'Andrés Cepeda', 'Enrique Iglesias', 'Draco Rosa', 'Chayanne', 'Alejandra Guzman', 'Thalia', 'Ricardo Arjona', 'Enrique Iglesias', 'Francisco Céspedes', 'Marc Anthony', 'Cabas', 'Marc Anthony', 'Thalia', 'Bacilos', 'Natalia Lafourcade', 'Monica Naranjo', 'Chayanne', 'David Bisbal', 'Shakira', 'La Quinta Estacion', 'Shakira', 'Alejandro Fernández', 'Ricardo Arjona', 'Enrique Iglesias', 'Alejandro Fernández', 'Marc Anthony', 'David Bisbal', 'David Bisbal', 'Paulina Rubio', 'Juanes', 'La Gran Banda', 'Enrique Iglesias', 'Paulina Rubio', 'Thalia', 'Cristian Castro', 'Paulina Rubio', 'Chayanne', 'Shakira', 'Juanes', 'David Bisbal', 'David Bisbal', 'Ricardo Arjona', 'Juanes', 'Ricardo Arjona', 'Enrique Iglesias', 'Cristian Castro', 'Bacilos', 'Shakira', 'Bacilos', 'Juanes', 'Juanes', 'Chayanne', 'Chayanne', 'Ricardo Arjona', 'Paulina Rubio', 'La Mona Jimenez', 'Juanes', 'Thalia', 'Juanes', 'Shakira', 'Marc Anthony', 'Chayanne', 'David Bisbal', 'Ricardo Arjona', 'Paulina Rubio', 'Chayanne', 'Ricardo Arjona', 'Shakira', 'Thalia', 'Ricardo Arjona', 'Thalia', 'Enrique Iglesias', 'Shakira', 'Chayanne', 'Chayanne', 'David Bisbal', 'Chayanne', 'Bacilos', 'Juanes', 'La Barra', 'Chayanne', 'Juanes', 'Shakira', 'Shakira', 'Chayanne', 'Ricardo Arjona', 'David Bisbal', 'Cubismo', 'Alejandro Fernández', 'Shakira', 'Ricardo Arjona', 'Marc Anthony', 'Edwin Bonilla', 'Nek', 'Shakira', 'Alejandro Fernández', 'Ricardo Arjona', 'La Quinta Estacion', 'Chayanne', 'Los Fachero´s', 'Alejandro Fernández', 'Raulin Rodriguez', 'Los Fachero´s', 'Sabroso', 'Los Playeros', 'Los Playeros', 'Los Incomparables De Tijuana', 'Shakira', 'Andrés Cepeda', 'La Mona Jimenez', 'Bacilos', 'Juanes', 'Sandy e Junior', 'Chayanne', 'Juanes', 'Enrique Iglesias', 'Marc Anthony', 'Banda XXI', 'Los Playeros', 'Juanes', 'Eydie Gormé', 'Luis Miguel', 'Chayanne', 'Enrique Iglesias', 'Ricardo Arjona', 'Los Playeros', 'Juanes', 'Chayanne', 'David Bisbal', 'Chayanne', 'Enrique Iglesias', 'Aleks Syntek', 'Víctor Manuelle', 'Murga Contrafarsa', 'Andy Aguilera', 'La Quinta Estacion', 'Bacilos', 'Enrique Iglesias', 'Banda XXI', 'La Quinta Estacion', 'Ricardo Montaner', 'Shakira', 'La Quinta Estacion', 'Chayanne', 'Carlos Ponce', 'La Quinta Estacion', 'Alejandra Guzman', 'Shakira', 'Banda XXI', 'Ricardo Arjona', 'Juanes', 'Chayanne', 'Juan Formell y Los Van Van', 'Ricky Martin', 'Belinda', 'Ricky Martin', 'Salsa Celtica', 'Sebastian', 'Julieta Venegas', 'Ha*Ash', 'Los Tucanes De Tijuana', 'Yahir', 'Chayanne', 'Sin Bandera', 'Mauricio & PalodeAgua', 'La Oreja de Van Gogh', 'Julieta Venegas', 'Belinda', 'Ricky Martin', 'Julieta Venegas', 'Ha*Ash', 'Luis Miguel', 'Willie Bobo', 'Jimmy Sabater', 'Chayanne', 'Luis Miguel', 'Chayanne', 'Sin Bandera', 'Jarabe De Palo', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'Luis Miguel', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'Luis Miguel', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'Ricky Martin', 'Sin Bandera', 'La Oreja de Van Gogh', 'Sin Bandera', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'David Bisbal', 'Sin Bandera', 'Julieta Venegas', 'Michael Bublé', 'Julieta Venegas', 'Gloria Estefan', 'Grupo Exterminador', 'La Barra', 'Tru La La', 'Tranzas', 'Grupo Exterminador', 'Latin Dreams', 'Banda XXI', 'Sin Bandera', 'Mauricio & PalodeAgua', 'Danni Ubeda', 'Belinda', 'Rey Ruiz', 'Luis Fonsi', 'Sin Bandera', 'Jennifer Lopez', 'Noelia', 'Sin Bandera', 'Ana Torroja', 'Alexandre Pires', 'OBK', 'Tiziano Ferro', 'Chayanne', 'Bacanos', 'Nika', 'Patricia Manterola', 'Ha*Ash', 'Ha*Ash', 'David Calzado y su Charanga Habanera', 'Tru La La', 'Moises Angulo', 'Enrique Iglesias', 'Danni Ubeda', 'Luis Miguel', 'Beto Quintanilla', 'Ana Torroja', 'Sin Bandera', 'Mauricio & PalodeAgua', 'Danni Ubeda', 'Belinda', 'Ha*Ash', 'Raul Paz', 'Sin Bandera', 'Beto Quintanilla', 'Los Tucanes De Tijuana', 'Tiziano Ferro', 'Beto Quintanilla', 'Pepe Aguilar', 'Grupo Aliados', 'Julieta Venegas', 'Wakal', 'Beto Quintanilla', 'Geno', 'Los Playeros', 'Ana Torroja', 'Jennifer Lopez', 'Enrique Iglesias', 'Shalim', 'Obie Bermudez', 'Thalia', 'Sebastian', 'La Mona Jimenez', 'Chic Savanna', 'Thalia', 'Julieta Venegas', 'Banda XXI', 'Ricardo Montaner', 'Mauricio & PalodeAgua', 'Wakal', 'Ana Torroja', 'Wakal', 'Jean Carlos', 'Chayanne', 'Luis Fonsi', 'Julieta Venegas', 'La Barra', 'Julieta Venegas', 'Qarto Aparte', 'Beto Quintanilla', 'Andrés Cepeda', 'Grupo Escuela del Amor', 'Carlos Jean', 'Chayanne', 'Tiziano Ferro', 'Cabas', 'Paco Pineda y Su Grupo Tex Mex', 'Chayanne', 'Los Playeros', 'Wakal', 'Ricky Martin', 'Julieta Venegas', 'Christina Aguilera', 'Banda XXI', 'Sin Bandera', 'Grupo Exterminador', 'Thalia', 'Melody', 'La Fiesta', 'Ricky Martin', 'Papá Levante', 'Paco Pineda y Su Grupo Tex Mex', 'Miguel Bosé', 'RBD', 'El Cuarteto De Nos', 'LU', 'El Cuarteto De Nos', 'Bacilos', 'Marc Anthony', 'Juanes', 'Juanes', 'Alejandro Sanz', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'RBD', 'Diego Torres', 'La Oreja de Van Gogh', 'Paulina Rubio', 'Alejandro Sanz', 'Bacilos', 'Alejandro Sanz', 'Ricardo Arjona', 'La Oreja de Van Gogh', 'Laura Pausini', 'Alejandro Sanz', 'RBD', 'La Quinta Estacion', 'RBD', 'Ricardo Arjona', 'Alejandro Fernández', 'La Quinta Estacion', 'La Oreja de Van Gogh', 'Gloria Estefan', 'Juanes', 'David Bisbal', 'Juanes', 'Franco De Vita', 'David Bisbal', 'RBD', 'La Oreja de Van Gogh', 'Alejandro Fernández', 'Juanes', 'Franco De Vita', 'La Oreja de Van Gogh', 'David Bisbal', 'RBD', 'La Quinta Estacion', 'Alejandro Sanz', 'Juanes', 'La Oreja de Van Gogh', 'Aleks Syntek', 'Alejandro Sanz', 'RBD', 'RBD', 'Benny', 'Marc Anthony', 'RBD', 'Ricardo Arjona', 'Aleks Syntek', 'Diego Torres', 'Alejandro Sanz', 'RBD', 'Alejandro Sanz', 'La Oreja de Van Gogh', 'Alejandro Sanz', 'David Bisbal', 'Marc Anthony', 'Carlos Vives', 'La Quinta Estacion', 'David Bisbal', 'Juanes', 'La Oreja de Van Gogh', 'La Quinta Estacion', 'Juanes', 'David Bisbal', 'Alejandro Sanz', 'La-33', 'Alejandro Sanz', 'Alejandro Sanz', 'La Oreja de Van Gogh', 'Alejandro Sanz', 'El Cuarteto De Nos', 'Alejandro Sanz', 'Thalia', 'Diego Torres', 'Alejandro Sanz', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'Alejandro Sanz', 'Miranda!', 'Marc Anthony', 'La Oreja de Van Gogh', 'Marc Anthony', 'Alejandro Sanz', 'Marc Anthony', 'La Oreja de Van Gogh', 'Marc Anthony', 'Alejandro Sanz', 'Lucas Arnau', 'Alejandro Sanz', 'Alejandro Sanz', 'La Oreja de Van Gogh', 'El Cuarteto De Nos', 'Yahir', 'Yahir', 'Gloria Trevi', 'Alejandro Sanz', 'El Cuarteto De Nos', 'Thalia', 'Marc Anthony', 'LU', 'Nek', 'Thalia', 'Diego Torres', 'Miranda!', 'Ricardo Arjona', 'Juanes', 'Paulina Rubio', 'La Oreja de Van Gogh', 'La Quinta Estacion', 'Alejandro Sanz', 'Alejandro Sanz', 'KEMA', 'Alejandro Sanz', 'Obie Bermudez', 'Los Palmeras', 'Alejandro Sanz', 'Miranda!', 'El Cuarteto De Nos', 'Marc Anthony', 'Miranda!', 'Juanes', 'La Oreja de Van Gogh', 'Marc Anthony', 'La Oreja de Van Gogh', 'Alejandro Sanz', 'Alejandro Sanz', 'La Oreja de Van Gogh', 'Damas Gratis', 'Alejandro Sanz', 'La Oreja de Van Gogh', 'Lucas Arnau', 'Carlos Vives', 'Paulina Rubio', 'Miranda!', 'Lucas Arnau', 'Diego Torres', 'Miguel Bosé', 'RBD', 'Ricardo Arjona', 'Franco De Vita', 'Alejandro Sanz']

In [24]:
## en la lista json tenemos duplicados, por lo que no nos sirve

In [25]:
lista_artistas

[{'artista': 'Shakira',
  'oyentes': '4640737',
  'reproducciones': '168412816',
  'bio_resumen': 'Shakira Isabel Mebarak Ripoll is a Colombian singer. Born and raised in Barranquilla, She made her recording debut with Sony Music Colombia at the age of 13. Following the commercial failure of her first two albums, Magia (1991) and Peligro (1993), she rose to prominence in Hispanic countries with her next albums, Pies Descalzos (1995) and Dónde Están los Ladrones? (1998). She entered the English-language market with her fifth album, Laundry Service (2001), which sold over 13 million copies worldwide. <a href="https://www.last.fm/music/Shakira">Read more on Last.fm</a>'},
 {'artista': 'Morat',
  'oyentes': '287335',
  'reproducciones': '20750056',
  'bio_resumen': 'Morat is a Colombian band formed in the country\'s capital city, Bogotá. The band is formed by Juan Pablo Isaza (guitars and vocals), Juan Pablo Villamil (banjo and vocals) and the brothers Simón Vargas (bass and choruses) and Martín Vargas (percussion and choirs). Previously, until the end of 2016, drummer Alejandro Posada had been in the band, but the percussionist had to leave the project, being subsequently replaced by Martín Vargas.\n\nThey began to stand out internationally in 2015 <a href="https://www.last.fm/music/Morat">Read more on Last.fm</a>'}]

In [26]:
df_latin_pop_LastFm = pd.DataFrame(lista_artistas) 

df_latin_pop_LastFm.head()

,artista,oyentes,reproducciones,bio_resumen
0,Shakira,4640737,168412816,Shakira Isabel Mebarak Ripoll is a Colombian s...
1,Morat,287335,20750056,Morat is a Colombian band formed in the countr...

In [27]:
df_latin_pop_LastFm.to_csv("df_latin_pop_LastFm.csv", index=False, encoding="utf-8")

In [28]:
df = pd.read_csv('df_latin_pop.csv') ##leemos el df

In [29]:
df

,Artista,Género,Tipo,Nombre,Año,ID
0,La Oreja de Van Gogh,latin pop,track,Pop,2000,4FXSEdmbbeGmPIQltH27C8
1,Ricky Martin,latin pop,track,She Bangs - Spanish Version,2000,4ti5pZ0zs1PDf1eQswskFB
2,Rodrigo,latin pop,track,Como Le Digo,2000,4nH1lpWkgzQPpTYPPjWKaI
3,Thalia,latin pop,track,Entre El Mar Y Una Estrella,2000,2KNtKG2X0jpOIgVunVbAkQ
4,Rodrigo,latin pop,track,Fuego y Pasion,2000,0SBHkYiZh8ih1RHoOcDtHl
...,...,...,...,...,...,...
745,Miguel Bosé,latin pop,track,Habana (con Alejandro Fernández),2004,2qnSc14v8T5YSqNeeZls4k
746,RBD,latin pop,track,Cuando El Amor Se Acaba,2004,50y4eCnuuWIhJl5uuCqVa5
747,Ricardo Arjona,latin pop,track,Desnuda,2004,5WVsQTW7BE1ClEDCmDKzci
748,Franco De Vita,latin pop,track,Ay Dios,2004,0Sd0bKypMwcUTUgHH9TCov
749,Alejandro Sanz,latin pop,track,Y sólo se me ocurre amarte,2004,3zvnloMEkCiIFRsZDUJPaW

In [30]:
df.columns = df.columns.str.strip()

In [31]:
artistas = df['Artista'] ##accedemos a artistas

In [32]:
artistas

0      La Oreja de Van Gogh
1              Ricky Martin
2                   Rodrigo
3                    Thalia
4                   Rodrigo
               ...
745             Miguel Bosé
746                     RBD
747          Ricardo Arjona
748          Franco De Vita
749          Alejandro Sanz
Name: Artista, Length: 750, dtype: object

In [33]:
artistas_unicos = set(artistas) ## eliminamos duplicados

In [34]:
artistas_unicos

{'Alejandra Guzman',
 'Alejandro Fernández',
 'Alejandro Parreño',
 'Alejandro Sanz',
 'Aleks Syntek',
 'Alexandre Pires',
 'Ana Torroja',
 'Andrés Cepeda',
 'Andy Aguilera',
 'Armando Manzanero',
 'Bacanos',
 'Bacilos',
 'Banda XXI',
 'Belinda',
 'Benny',
 'Beny Moré',
 'Bertin Osborne',
 'Beto Quintanilla',
 'Cabas',
 'Carlos Jean',
 'Carlos Ponce',
 'Carlos Vives',
 'Celia Cruz',
 'Chayanne',
 'Chic Savanna',
 'Christina Aguilera',
 'Clave Cubana',
 'Cristian Castro',
 'Cubismo',
 'Damas Gratis',
 'Danni Ubeda',
 'David Bisbal',
 'David Calzado y su Charanga Habanera',
 'Debelah Morgan',
 'Diego Torres',
 'Donato Y Estefano',
 'Draco Rosa',
 'Edwin Bonilla',
 'El Cuarteto De Nos',
 'Enrique Iglesias',
 'Eros Ramazzotti',
 'Eydie Gormé',
 'Fey',
 'Francisco Céspedes',
 'Franco De Vita',
 'Geno',
 'Gloria Estefan',
 'Gloria Trevi',
 'Glup!',
 'Grupo Aliados',
 'Grupo Escuela del Amor',
 'Grupo Exterminador',
 'Guaraná',
 'Ha*Ash',
 'Huey Dunbar',
 'Issac Delgado',
 'Jarabe De Palo',
 'Jean Carlos',
 'Jennifer Lopez',
 'Jimmy Bosch',
 'Jimmy Gutierrez',
 'Jimmy Sabater',
 'Joaquín Sabina',
 'Jon Secada',
 'José José',
 'Juan Formell y Los Van Van',
 'Juanes',
 'Julieta Venegas',
 'Julio Iglesias',
 'KEMA',
 'LU',
 'La Barra',
 'La Fiesta',
 'La Gran Banda',
 'La Mona Jimenez',
 'La Mosca',
 'La Oreja de Van Gogh',
 'La Quinta Estacion',
 'La Retrocumbia',
 'La-33',
 'Latin Dreams',
 'Laura Miller',
 'Laura Pausini',
 'Lemon',
 'Los Cachorros de Juan Villarreal',
 "Los Chaque's",
 'Los Fachero´s',
 'Los Incomparables De Tijuana',
 'Los Legendarios',
 'Los Originales De San Juan',
 'Los Palmeras',
 'Los Playeros',
 'Los Razos',
 'Los Tigres Del Norte',
 'Los Tucanes De Tijuana',
 'Lucas Arnau',
 'Luis Alberto Posada',
 'Luis Fonsi',
 'Luis Miguel',
 'Luisito Muñoz',
 'Malú',
 'Marc Anthony',
 'Mauricio & PalodeAgua',
 'Melody',
 'Michael Bublé',
 'Miguel Bosé',
 'Miranda!',
 "Mo' Horizons",
 'Moises Angulo',
 'Monica Naranjo',
 'Murga Contrafarsa',
 'Natalia Lafourcade',
 'Nek',
 'Nika',
 'Noelia',
 'OBK',
 'Obie Bermudez',
 'Orquesta Tabaco Y Ron',
 'Paco Pineda y Su Grupo Tex Mex',
 'Papá Levante',
 'Patricia Manterola',
 'Paulina Rubio',
 'Pepe Aguilar',
 'Polo Montañez',
 'Qarto Aparte',
 'RBD',
 'Raul Paz',
 'Raulin Rodriguez',
 'Rey Ruiz',
 'Ricardo Arjona',
 'Ricardo Montaner',
 'Ricky Martin',
 'Rios De Gloria',
 'Rodrigo',
 'Sabroso',
 'Salsa Celtica',
 'Sandy e Junior',
 'Sebastian',
 'Shakira',
 'Shalim',
 'Sin Bandera',
 'Skeewiff',
 'Thalia',
 'Tiziano Ferro',
 'Tommy Torres',
 'Tranzas',
 'Tru La La',
 'Víctor Manuelle',
 'Wakal',
 'Walter Olmos',
 'Willie Bobo',
 'Yahir'}

In [35]:
 ## introducimos artistas unicos

In [36]:
artistas_unicos
lista_artistas = []
for nombre_artista in artistas_unicos:
    print(f"--- Consultando: {nombre_artista} ---")
    datos_artista = llamar_lastfm_api('artist.getinfo', nombre_artista, cliente)
    if datos_artista and 'artist' in datos_artista:
        artista_data = datos_artista['artist']
        oyentes = artista_data.get('stats', {}).get('listeners', 'arista no encontrado')
        reproducciones = artista_data.get('stats', {}).get('playcount', 'N/D')
        bio_content = artista_data.get('bio', {}).get('content', '')
        if not bio_content or bio_content.strip() == "":
            bio_resumen = 'biografia no encontrada'
        else:
            bio_resumen = artista_data.get('bio', {}).get('summary')
        lista_artistas_dict = {'artista': artista_data.get('name', nombre_artista),'oyentes': oyentes, 'reproducciones': reproducciones, 'bio_resumen': bio_resumen}
        lista_artistas.append(lista_artistas_dict)
        print(f"Datos de {nombre_artista} procesados y guardados.")
    else:
        print(f"No se pudo obtener información de {nombre_artista}")

--- Consultando: Jon Secada ---
Datos de Jon Secada procesados y guardados.
--- Consultando: Noelia ---
Datos de Noelia procesados y guardados.
--- Consultando: Los Legendarios ---
Datos de Los Legendarios procesados y guardados.
--- Consultando: Geno ---
Datos de Geno procesados y guardados.
--- Consultando: La Oreja de Van Gogh ---
Datos de La Oreja de Van Gogh procesados y guardados.
--- Consultando: Celia Cruz ---
Datos de Celia Cruz procesados y guardados.
--- Consultando: Draco Rosa ---
Datos de Draco Rosa procesados y guardados.
--- Consultando: Jimmy Sabater ---
Datos de Jimmy Sabater procesados y guardados.
--- Consultando: Raul Paz ---
Datos de Raul Paz procesados y guardados.
--- Consultando: Luis Miguel ---
Datos de Luis Miguel procesados y guardados.
--- Consultando: Andy Aguilera ---
Datos de Andy Aguilera procesados y guardados.
--- Consultando: Jarabe De Palo ---
Datos de Jarabe De Palo procesados y guardados.
--- Consultando: El Cuarteto De Nos ---
Datos de El Cuarteto De Nos procesados y guardados.
--- Consultando: Eydie Gormé ---
Datos de Eydie Gormé procesados y guardados.
--- Consultando: Grupo Escuela del Amor ---
No se pudo obtener información de Grupo Escuela del Amor
--- Consultando: Ricardo Montaner ---
Datos de Ricardo Montaner procesados y guardados.
--- Consultando: Bacanos ---
Datos de Bacanos procesados y guardados.
--- Consultando: Chayanne ---
Datos de Chayanne procesados y guardados.
--- Consultando: David Bisbal ---
Datos de David Bisbal procesados y guardados.
--- Consultando: Nika ---
Datos de Nika procesados y guardados.
--- Consultando: RBD ---
Datos de RBD procesados y guardados.
--- Consultando: Malú ---
Datos de Malú procesados y guardados.
--- Consultando: Rodrigo ---
Datos de Rodrigo procesados y guardados.
--- Consultando: Sebastian ---
Datos de Sebastian procesados y guardados.
--- Consultando: Andrés Cepeda ---
Datos de Andrés Cepeda procesados y guardados.
--- Consultando: Ricardo Arjona ---
Datos de Ricardo Arjona procesados y guardados.
--- Consultando: Marc Anthony ---
Datos de Marc Anthony procesados y guardados.
--- Consultando: Melody ---
Datos de Melody procesados y guardados.
--- Consultando: Aleks Syntek ---
Datos de Aleks Syntek procesados y guardados.
--- Consultando: Chic Savanna ---
Datos de Chic Savanna procesados y guardados.
--- Consultando: Raulin Rodriguez ---
Datos de Raulin Rodriguez procesados y guardados.
--- Consultando: La Quinta Estacion ---
Datos de La Quinta Estacion procesados y guardados.
--- Consultando: La Retrocumbia ---
Datos de La Retrocumbia procesados y guardados.
--- Consultando: Mauricio & PalodeAgua ---
Datos de Mauricio & PalodeAgua procesados y guardados.
--- Consultando: Monica Naranjo ---
Datos de Monica Naranjo procesados y guardados.
--- Consultando: La Fiesta ---
Datos de La Fiesta procesados y guardados.
--- Consultando: Wakal ---
Datos de Wakal procesados y guardados.
--- Consultando: Enrique Iglesias ---
Datos de Enrique Iglesias procesados y guardados.
--- Consultando: Carlos Jean ---
Datos de Carlos Jean procesados y guardados.
--- Consultando: Julieta Venegas ---
Datos de Julieta Venegas procesados y guardados.
--- Consultando: LU ---
Datos de LU procesados y guardados.
--- Consultando: Tranzas ---
Datos de Tranzas procesados y guardados.
--- Consultando: Banda XXI ---
Datos de Banda XXI procesados y guardados.
--- Consultando: OBK ---
Datos de OBK procesados y guardados.
--- Consultando: Ricky Martin ---
Datos de Ricky Martin procesados y guardados.
--- Consultando: Issac Delgado ---
Datos de Issac Delgado procesados y guardados.
--- Consultando: Los Tigres Del Norte ---
Datos de Los Tigres Del Norte procesados y guardados.
--- Consultando: Shakira ---
Datos de Shakira procesados y guardados.
--- Consultando: Qarto Aparte ---
Datos de Qarto Aparte procesados y guardados.
--- Consultando: Alejandro Sanz ---
Datos de Alejandro Sanz procesados y guardados.
--- Consultando: Skeewiff ---
Datos de Skeewiff procesados y guardados.
--- Consultando: Danni Ubeda ---
Datos de Danni Ubeda procesados y guardados.
--- Consultando: Shalim ---
Datos de Shalim procesados y guardados.
--- Consultando: La-33 ---
Datos de La-33 procesados y guardados.
--- Consultando: Eros Ramazzotti ---
Datos de Eros Ramazzotti procesados y guardados.
--- Consultando: Bertin Osborne ---
Datos de Bertin Osborne procesados y guardados.
--- Consultando: Huey Dunbar ---
Datos de Huey Dunbar procesados y guardados.
--- Consultando: La Mosca ---
Datos de La Mosca procesados y guardados.
--- Consultando: Los Playeros ---
Datos de Los Playeros procesados y guardados.
--- Consultando: Luis Alberto Posada ---
Datos de Luis Alberto Posada procesados y guardados.
--- Consultando: Alejandro Fernández ---
Datos de Alejandro Fernández procesados y guardados.
--- Consultando: Francisco Céspedes ---
Datos de Francisco Céspedes procesados y guardados.
--- Consultando: Guaraná ---
Datos de Guaraná procesados y guardados.
--- Consultando: Walter Olmos ---
Datos de Walter Olmos procesados y guardados.
--- Consultando: Luisito Muñoz ---
Datos de Luisito Muñoz procesados y guardados.
--- Consultando: Grupo Aliados ---
Datos de Grupo Aliados procesados y guardados.
--- Consultando: Los Tucanes De Tijuana ---
Datos de Los Tucanes De Tijuana procesados y guardados.
--- Consultando: Alexandre Pires ---
Datos de Alexandre Pires procesados y guardados.
--- Consultando: Glup! ---
Datos de Glup! procesados y guardados.
--- Consultando: Belinda ---
Datos de Belinda procesados y guardados.
--- Consultando: La Barra ---
Datos de La Barra procesados y guardados.
--- Consultando: Julio Iglesias ---
Datos de Julio Iglesias procesados y guardados.
--- Consultando: Diego Torres ---
Datos de Diego Torres procesados y guardados.
--- Consultando: Sin Bandera ---
Datos de Sin Bandera procesados y guardados.
--- Consultando: Armando Manzanero ---
Datos de Armando Manzanero procesados y guardados.
--- Consultando: Tommy Torres ---
Datos de Tommy Torres procesados y guardados.
--- Consultando: Lemon ---
Datos de Lemon procesados y guardados.
--- Consultando: Obie Bermudez ---
Datos de Obie Bermudez procesados y guardados.
--- Consultando: Los Originales De San Juan ---
Datos de Los Originales De San Juan procesados y guardados.
--- Consultando: Pepe Aguilar ---
Datos de Pepe Aguilar procesados y guardados.
--- Consultando: Jimmy Gutierrez ---
Datos de Jimmy Gutierrez procesados y guardados.
--- Consultando: Laura Miller ---
Datos de Laura Miller procesados y guardados.
--- Consultando: Salsa Celtica ---
Datos de Salsa Celtica procesados y guardados.
--- Consultando: Beny Moré ---
Datos de Beny Moré procesados y guardados.
--- Consultando: Jennifer Lopez ---
Datos de Jennifer Lopez procesados y guardados.
--- Consultando: Los Razos ---
Datos de Los Razos procesados y guardados.
--- Consultando: Michael Bublé ---
Datos de Michael Bublé procesados y guardados.
--- Consultando: Rios De Gloria ---
Datos de Rios De Gloria procesados y guardados.
--- Consultando: Grupo Exterminador ---
Datos de Grupo Exterminador procesados y guardados.
--- Consultando: Gloria Trevi ---
Datos de Gloria Trevi procesados y guardados.
--- Consultando: Los Chaque's ---
Datos de Los Chaque's procesados y guardados.
--- Consultando: Mo' Horizons ---
Datos de Mo' Horizons procesados y guardados.
--- Consultando: Jean Carlos ---
Datos de Jean Carlos procesados y guardados.
--- Consultando: Cristian Castro ---
Datos de Cristian Castro procesados y guardados.
--- Consultando: Juan Formell y Los Van Van ---
Datos de Juan Formell y Los Van Van procesados y guardados.
--- Consultando: Tiziano Ferro ---
Datos de Tiziano Ferro procesados y guardados.
--- Consultando: Beto Quintanilla ---
Datos de Beto Quintanilla procesados y guardados.
--- Consultando: Miranda! ---
Datos de Miranda! procesados y guardados.
--- Consultando: Polo Montañez ---
Datos de Polo Montañez procesados y guardados.
--- Consultando: Luis Fonsi ---
Datos de Luis Fonsi procesados y guardados.
--- Consultando: KEMA ---
Datos de KEMA procesados y guardados.
--- Consultando: Christina Aguilera ---
Datos de Christina Aguilera procesados y guardados.
--- Consultando: Patricia Manterola ---
Datos de Patricia Manterola procesados y guardados.
--- Consultando: Moises Angulo ---
Datos de Moises Angulo procesados y guardados.
--- Consultando: Papá Levante ---
Datos de Papá Levante procesados y guardados.
--- Consultando: Cubismo ---
Datos de Cubismo procesados y guardados.
--- Consultando: Fey ---
Datos de Fey procesados y guardados.
--- Consultando: Tru La La ---
Datos de Tru La La procesados y guardados.
--- Consultando: Murga Contrafarsa ---
Datos de Murga Contrafarsa procesados y guardados.
--- Consultando: La Gran Banda ---
Datos de La Gran Banda procesados y guardados.
--- Consultando: Alejandro Parreño ---
Datos de Alejandro Parreño procesados y guardados.
--- Consultando: Debelah Morgan ---
Datos de Debelah Morgan procesados y guardados.
--- Consultando: Latin Dreams ---
Datos de Latin Dreams procesados y guardados.
--- Consultando: Paco Pineda y Su Grupo Tex Mex ---
Datos de Paco Pineda y Su Grupo Tex Mex procesados y guardados.
--- Consultando: Joaquín Sabina ---
Datos de Joaquín Sabina procesados y guardados.
--- Consultando: Ha*Ash ---
Datos de Ha*Ash procesados y guardados.
--- Consultando: Willie Bobo ---
Datos de Willie Bobo procesados y guardados.
--- Consultando: Juanes ---
Datos de Juanes procesados y guardados.
--- Consultando: Los Fachero´s ---
Datos de Los Fachero´s procesados y guardados.
--- Consultando: Gloria Estefan ---
Datos de Gloria Estefan procesados y guardados.
--- Consultando: Alejandra Guzman ---
Datos de Alejandra Guzman procesados y guardados.
--- Consultando: Clave Cubana ---
Datos de Clave Cubana procesados y guardados.
--- Consultando: Natalia Lafourcade ---
Datos de Natalia Lafourcade procesados y guardados.
--- Consultando: Víctor Manuelle ---
Datos de Víctor Manuelle procesados y guardados.
--- Consultando: José José ---
Datos de José José procesados y guardados.
--- Consultando: Lucas Arnau ---
Datos de Lucas Arnau procesados y guardados.
--- Consultando: Carlos Ponce ---
Datos de Carlos Ponce procesados y guardados.
--- Consultando: Carlos Vives ---
Datos de Carlos Vives procesados y guardados.
--- Consultando: Los Incomparables De Tijuana ---
Datos de Los Incomparables De Tijuana procesados y guardados.
--- Consultando: La Mona Jimenez ---
Datos de La Mona Jimenez procesados y guardados.
--- Consultando: Ana Torroja ---
Datos de Ana Torroja procesados y guardados.
--- Consultando: Paulina Rubio ---
Datos de Paulina Rubio procesados y guardados.
--- Consultando: Franco De Vita ---
Datos de Franco De Vita procesados y guardados.
--- Consultando: Orquesta Tabaco Y Ron ---
Datos de Orquesta Tabaco Y Ron procesados y guardados.
--- Consultando: Sandy e Junior ---
Datos de Sandy e Junior procesados y guardados.
--- Consultando: Thalia ---
Datos de Thalia procesados y guardados.
--- Consultando: Edwin Bonilla ---
Datos de Edwin Bonilla procesados y guardados.
--- Consultando: Cabas ---
Datos de Cabas procesados y guardados.
--- Consultando: Yahir ---
Datos de Yahir procesados y guardados.
--- Consultando: Donato Y Estefano ---
Datos de Donato Y Estefano procesados y guardados.
--- Consultando: Nek ---
Datos de Nek procesados y guardados.
--- Consultando: Miguel Bosé ---
Datos de Miguel Bosé procesados y guardados.
--- Consultando: Los Palmeras ---
Datos de Los Palmeras procesados y guardados.
--- Consultando: Jimmy Bosch ---
Datos de Jimmy Bosch procesados y guardados.
--- Consultando: Rey Ruiz ---
Datos de Rey Ruiz procesados y guardados.
--- Consultando: Bacilos ---
Datos de Bacilos procesados y guardados.
--- Consultando: Sabroso ---
Datos de Sabroso procesados y guardados.
--- Consultando: Laura Pausini ---
Datos de Laura Pausini procesados y guardados.
--- Consultando: Benny ---
Datos de Benny procesados y guardados.
--- Consultando: David Calzado y su Charanga Habanera ---
Datos de David Calzado y su Charanga Habanera procesados y guardados.
--- Consultando: Los Cachorros de Juan Villarreal ---
Datos de Los Cachorros de Juan Villarreal procesados y guardados.
--- Consultando: Damas Gratis ---
Datos de Damas Gratis procesados y guardados.

In [37]:
len(lista_artistas)

151

In [38]:
df_artistas_latin_pop_LastFm = pd.DataFrame(lista_artistas)

In [39]:
df_artistas_latin_pop_LastFm

,artista,oyentes,reproducciones,bio_resumen
0,Jon Secada,253200,1780136,"Juan Francisco Secada (born October 4, 1962 in..."
1,Noelia,82084,458386,There are several artists who perform under th...
2,Los Legendarios,104518,843549,biografia no encontrada
3,Geno,1998,8425,"Geno is a g-funk artist from Chicago, IL. He r..."
4,La Oreja de Van Gogh,629390,18638355,La Oreja de Van Gogh (English: Van Gogh's Ear)...
...,...,...,...,...
146,Laura Pausini,555670,21836726,Laura Pausini is a five-time Grammy Award winn...
147,Benny,141803,1135285,There are multiple artist called Benny:\n\n1. ...
148,David Calzado Y Su Charanga Habanera,20640,258617,\n La Charanga Habanera y David Calzado Bio...
149,Los Cachorros De Juan Villarreal,11123,95580,biografia no encontrada
150,Damas Gratis,84912,1395783,Damas Gratis es un grupo musical de cumbia vil...

In [40]:
## convertimos nuevamente en df y en csv

In [41]:
df_artistas_latin_pop_LastFm.to_csv("artista_latin_pop.csv", index=False, encoding="utf-8")

In [42]:
## debemos enlazar en la consulta el país, y debe proceder de biografía

In [43]:
## generamos un diccionario BASE, formado por GENTILICIOS.

In [44]:
PAIS_A_GENTILICIO = {
    "Afghanistan": "Afghan",
    "Albania": "Albanian",
    "Algeria": "Algerian",
    "Argentina": "Argentinian",
    "Australia": "Australian",
    "Austria": "Austrian",
    "Belgium": "Belgian",
    "Bolivia": "Bolivian",
    "Brazil": "Brazilian",
    "Canada": "Canadian",
    "Chile": "Chilean",
    "China": "Chinese",
    "Colombia": "Colombian",
    "Costa Rica": "Costa Rican",
    "Cuba": "Cuban",
    "Denmark": "Dane",
    "Egypt": "Egyptian",
    "France": "French",
    "Germany": "German",
    "Greece": "Greek",
    "India": "Indian",
    "Indonesia": "Indonesian",
    "Ireland": "Irish",
    "Italy": "Italian",
    "Jamaica": "Jamaican",
    "Japan": "Japanese",
    "Mexico": "Mexican",
    "Netherlands": "Dutch",
    "New Zealand": "New Zealander",
    "Nigeria": "Nigerian",
    "Norway": "Norwegian",
    "Peru": "Peruvian",
    "Poland": "Pole",
    "Portugal": "Portuguese",
    "Russia": "Russian",
    "South Korea": "South Korean",
    "Spain": "Spaniard",
    "Sweden": "Swede",
    "Turkey": "Turk",
    "Ukraine": "Ukrainian",
    "United Kingdom": "Briton",
    "United States": "American",
    "United States_adj": "American",
    "United Kingdom_adj": "British",
    "France_adj": "French",
    "Germany_adj": "German",
    "Spain_adj": "Spanish"}

In [45]:
# DICCIONARIO INVERTIDO PARA BÚSQUEDA EFICIENTE
# Clave: Gentilicio (lo que busco en la bio), Valor: País
GENTILICIO_A_PAIS = {gentilicio.lower(): pais.replace('_adj', '')
    for pais, gentilicio in PAIS_A_GENTILICIO.items()}

In [46]:
def extraer_pais_de_biografia(bio_resumen, gentilicio_a_pais_map):
    bio_normalizada = bio_resumen.lower()
    for gentilicio, pais in gentilicio_a_pais_map.items():
        # Usamos ' ' + gentilicio + ' ' para buscar la palabra completa y evitar coincidencias parciales
        if f' {gentilicio} ' in bio_normalizada or bio_normalizada.startswith(f'{gentilicio} '):
            return pais
        
        if bio_normalizada.endswith(gentilicio):
             return pais
    return 'Unknown'

for artista_data in lista_artistas:
    bio = artista_data['bio_resumen']
    pais_encontrado = extraer_pais_de_biografia(bio, GENTILICIO_A_PAIS)
    artista_data['pais'] = pais_encontrado #aqui agregamos la clave pais en nuestro diccionario
print(lista_artistas)

[{'artista': 'Jon Secada', 'oyentes': '253200', 'reproducciones': '1780136', 'bio_resumen': 'Juan Francisco Secada (born October 4, 1962 in Havana, Cuba)  better known as Jon Secada is an Afro-Cuban singer and songwriter. Secada was born in Havana, Cuba, and raised in Hialeah, Florida. He has won two Grammy Awards and sold 20 million albums since his English-language debut album in 1992, made famous for his song Just Another Day. His music fuses funk, soul, pop and Latin percussion. Secada also has appeared as a songwriter for Gloria Estefan, Jennifer Lopez, Ricky Martin, Mandy Moore and other performers. <a href="https://www.last.fm/music/Jon+Secada">Read more on Last.fm</a>', 'pais': 'Unknown'}, {'artista': 'Noelia', 'oyentes': '82084', 'reproducciones': '458386', 'bio_resumen': 'There are several artists who perform under the name Noelia.\n\n 1.) Noelia Lorenzo, this International Latin Music Super Star was raised  in Miami, Florida, mostly known as Noelia, is a Puerto Rican pop singer who rose to fame in 1999. During her career she has had 10 Latin Billboard Top 40 hits, and has eighteen worldwide gold and nine worldwide multi-platinum -certified albums, along with one RIAA-certified Goldrecord in the United States. She has sold more than 4.5 million Albums worldwide.  <a href="https://www.last.fm/music/Noelia">Read more on Last.fm</a>', 'pais': 'Unknown'}, {'artista': 'Los Legendarios', 'oyentes': '104518', 'reproducciones': '843549', 'bio_resumen': 'biografia no encontrada', 'pais': 'Unknown'}, {'artista': 'Geno', 'oyentes': '1998', 'reproducciones': '8425', 'bio_resumen': 'Geno is a g-funk artist from Chicago, IL. He released album Unknown Lifestyle vol. 1 in 1999. <a href="https://www.last.fm/music/Geno">Read more on Last.fm</a>', 'pais': 'Unknown'}, {'artista': 'La Oreja de Van Gogh', 'oyentes': '629390', 'reproducciones': '18638355', 'bio_resumen': 'La Oreja de Van Gogh (English: Van Gogh\'s Ear) is a Spanish band. The name of the band references the Dutch painter Vincent Van Gogh who allegedly cut off his own ear. It was formed in Spain in 1996, when guitarist Pablo Benegas, bassist Álvaro Fuentes, keyboardist Xabi San Martín and drummer Haritz Garde met at university.\n\nSan Martin was the vocalist until Amaia Montero joined the band by request from Benegas, just after he met her at a dinner party. <a href="https://www.last.fm/music/La+Oreja+de+Van+Gogh">Read more on Last.fm</a>', 'pais': 'Netherlands'}, {'artista': 'Celia Cruz', 'oyentes': '547142', 'reproducciones': '4653151', 'bio_resumen': 'Celia Cruz (born as Úrsula Hilaria Celia de la Caridad Cruz Alfonso in La Habana, Cuba on 21 October 1925 – died 16 July 2003) was a Cuban-American and was one of the most successful salsa performers of the 20th century, having earned twenty-three gold albums. She was renowned internationally as the "Queen of Salsa" as well as "La Guarachera de Cuba.\n\nIn 1950, Cruz made her first major breakthrough, after the lead singer of the La Sonora Matancera, a renowned Cuban orchestra, left the group and Cruz was called to fill in. <a href="https://www.last.fm/music/Celia+Cruz">Read more on Last.fm</a>', 'pais': 'Cuba'}, {'artista': 'Draco Rosa', 'oyentes': '30274', 'reproducciones': '467579', 'bio_resumen': 'Born Robert Edward Rosa Suarez on June 27, 1969, Long Island, New York. As "Robby Rosa" he was a member of Menudo from Valentine\'s Day, 1984 to 1987. He replaced Johnny Lozada in Menudo and soon became another fan favorite. He sang such hits like Tu Sabes A Chocolate, Hold Me and Like A Cannonball, which was featured in Hollywood hit Cannonball Run 2. He was replaced in Menudo by Ruben Gomez after the band\'s manager denied Rosa the opportunity to contribute songs to the group. <a href="https://www.last.fm/music/+noredirect/Draco+Rosa">Read more on Last.fm</a>', 'pais': 'Unknown'}, {'artista': 'Jimmy Sabater', 'oyentes': '18066', 'reproducciones': '93965', 'bio_resumen': 'Jimmy Sabater (April 11, 1946 - February 8, 2012) was born in Harlem Hospital, New York City. The proud son of Nestor Sabater and Teresa Gonzalez of Ponce, Puerto Rico, Jimmy grew up in East Harlem, the Spanish Quarter of New York City known as “El Barrio”. Like most teenagers in the neighborhood, he played stickball, flew kites, and harmonized the tunes of the popular R&B groups and vocalists of the day such as Nat King Cole.\n   He was inspired by percussionists such as Willie Bobo <a href="https://www.last.fm/music/Jimmy+Sabater">Read more on Last.fm</a>', 'pais': 'Spain'}, {'artista': 'Raul Paz', 'oyentes': '62514', 'reproducciones': '356644', 'bio_resumen': 'Raul Paz was born in 1969 in Pinar del Rio, Cuba.  He left Cuba in 1996, travelled in South America, and eventually arrived in France, where he studied classical music at the Conservatoire de Paris and learned the violin, singing, harmony and conducting.\n\nSoon, at Paris clubs, such as the New Morning, Hot Brass, Bataclan, and Elysée Montmartre, he was sharing the spotlight with other Afro-Cuban musician passing through the city.  As member of the Latino and African musical community based in France <a href="https://www.last.fm/music/Raul+Paz">Read more on Last.fm</a>', 'pais': 'Unknown'}, {'artista': 'Luis Miguel', 'oyentes': '803817', 'reproducciones': '34484977', 'bio_resumen': 'Luis Miguel Gallego Basteri (born 19 April 1970) is a Mexican singer and icon in Latin America, often referred to as El Sol de México (The Sun of Mexico), which is the nickname his mother gave him as a child- "mi sol". He is widely regarded as the most successful artist in Latin American history, having successfully performed in a wide range of musical styles, including pop, ballads, boleros, tangos, jazz, big band and mariachi. Luis Miguel is also <a href="https://www.last.fm/music/Luis+Miguel">Read more on Last.fm</a>', 'pais': 'Mexico'}, {'artista': 'Andy Aguilera', 'oyentes': '2122', 'reproducciones': '13886', 'bio_resumen': 'biografia no encontrada', 'pais': 'Unknown'}, {'artista': 'Jarabe de Palo', 'oyentes': '563054', 'reproducciones': '9368286', 'bio_resumen': 'Jarabe de Palo (literally "Wooden Stick Syrup" or, after the Spanish expression "dar un jarabe de palo", i.e. a "hell of a beating"), was a Spanish rock band founded in 1996. The group was led by singer, songwriter, and guitarist Pau Donés, whose death in 2020 caused the band to break up.\n\nPau Donés, born and raised in Barcelona, worked for various groups before being able to take on his current project, Jarabe de Palo. He began at age 15 with his brother Marc, with whom he formed a group known as J. <a href="https://www.last.fm/music/Jarabe+de+Palo">Read more on Last.fm</a>', 'pais': 'Spain'}, {'artista': 'El Cuarteto De Nos', 'oyentes': '254672', 'reproducciones': '17636423', 'bio_resumen': 'El Cuarteto de Nos is an Uruguayan alternative rock band formed in 1984 in Montevideo. The band was originally comprised of the Musso brothers (Roberto and Riki Musso) and Santiago Tavella, who they had met in high school. In 1984 they released their debut album, a split LP with uruguayan candombe musician Alberto Wolf under the Ayuí / Tacuabé label. Leonardo Baroncini was hired to be a guest drummer on the record.\n\nIn March 1987 they released Soy una arveja <a href="https://www.last.fm/music/El+Cuarteto+De+Nos">Read more on Last.fm</a>', 'pais': 'Unknown'}, {'artista': 'Eydie Gormé', 'oyentes': '208596', 'reproducciones': '2831929', 'bio_resumen': 'Eydie Gormé (also spelled as Eydie Gorme; born August 16, 1928) is an American singer, specializing, with her husband, Steve Lawrence, in traditional pop music, in the form of ballads and breezy swing. She has earned numerous awards, including the Grammy and the Emmy. She retired as of 2009; husband and musical partner Steve Lawrence continues to perform as a solo act.\n\nGormé was born as Edith Garmezano in Bronx, New York in 1928, the daughter of Fortuna and Nessim Garmezano. <a href="https://www.last.fm/music/+noredirect/Eydie+Gorm%C3%A9">Read more on Last.fm</a>', 'pais': 'United States'}, {'artista': 'Ricardo Montaner', 'oyentes': '226930', 'reproducciones': '2556457', 'bio_resumen': 'Ricardo Montaner (born as Hector Eduardo Reglero Montaner on September 8, 1957) is an Argentine-Venezuelan singer and songwriter. Starting his career in the early 80s, he has already released more than 15 albums with numerous successful singles and over 7 million record worldwide.\n\nMontaner was born as Héctor Eduardo Reglero Montaner, in Valentín Alsina, Buenos Aires, Argentina. However, he moved to Venezuela when he was 6 years old. During his youth he performed in the church chorus in the city of Maracaibo. <a href="https://www.last.fm/music/Ricardo+Montaner">Read more on Last.fm</a>', 'pais': 'Unknown'}, {'artista': 'Bacanos', 'oyentes': '6358', 'reproducciones': '48121', 'bio_resumen': 'biografia no encontrada', 'pais': 'Unknown'}, {'artista': 'Chayanne', 'oyentes': '491155', 'reproducciones': '6824324', 'bio_resumen': 'Chayanne (born June 29, 1969)is a Latin Pop singer who was born as Elmer Figueroa de Arce in San Lorenzo, Puerto Rico.\n\nFigueroa began using the artistic name of "Chayanne" when he was a little kid. He auditioned for Menudo, but was told that at the time that he was too young for the group. He didn\'t give up and he heard that Titi Soto was trying to create a new group that would compete with Menudo, and so he went and tried out. He was chosen for the group and his meteoric rise to the top began. <a href="https://www.last.fm/music/Chayanne">Read more on Last.fm</a>', 'pais': 'Unknown'}, {'artista': 'David Bisbal', 'oyentes': '350787', 'reproducciones': '5099384', 'bio_resumen': '\nDavid Bisbal Ferre (born June 5, 1979 in Almería, Spain) is a Latin Grammy-winning Spanish pop singer. He gained his initial fame as a runner up on the interactive reality television show Operación Triunfo produced by Television Española.\n\nHe has since released five studio albums, all of which topped the Spanish Albums Chart, in addition to recording a number of live albums. He\'s toured throughout Europe and Latin America and is now considered to be a crossover international artist. <a href="https://www.last.fm/music/David+Bisbal">Read more on Last.fm</a>', 'pais': 'Spain'}, {'artista': 'Nika', 'oyentes': '13330', 'reproducciones': '103244', 'bio_resumen': '1. Nika (Mónica Rodríguez) - spanish singer-songwriter.\n2. Nika (Dominika Domczyk) - vocalist of polish punk rock band Post Regiment\n3. Nika - dutch dubstep DJ\n4. Nika - finnish r&b singer\n5. Nika (Mónika Veres) - Hungarian singer, vocalist\n6. Nika - Estonian pop singer \n7. NIKA (니카) - Korean-German singer, formerly known as Monika (모니카). <a href="https://www.last.fm/music/Nika">Read more on Last.fm</a>', 'pais': 'Netherlands'}, {'artista': 'RBD', 'oyentes': '500397', 'reproducciones': '41885274', 'bio_resumen': 'RBD (abbreviation for "ReBelDe", English: Rebel) was a Latin pop group formed in Mexico. The lineup was composed of Alfonso Herrera, Anahí, Christian Chávez, Christopher Von Uckermann, Dulce María and Maite Perroni.\n\nTheir discography composed of six studio albums, Rebelde (2004), Nuestro Amor (2005), Celestial (2006), Rebels (2006), Empezar Desde Cero (2007) and Para Olvidarte de Mí (2009), three albums with Portuguese versions, three live albums and five DVDs, having sold over 50 million copies. <a href="https://www.last.fm/music/RBD">Read more on Last.fm</a>', 'pais': 'Portugal'}, {'artista': 'Malú', 'oyentes': '78641', 'reproducciones': '1320406', 'bio_resumen': 'There are at least 4 singers named Malú or Malu.\n\n1.  María \'Malú\' Lucía Sánchez (born 15 March, 1982) is a singer from Madrid, Spain. Malú was discovered at the age of 15 when she was singing at a family party. She began the recording of her first album Aprendiz in January 1998. Malú is the niece of the flamenco singer-songwriter Paco de Lucía.\n\n2. Malu is a pop singer from Amsterdam, The Netherlands. There is no accent on the letter \'u\', but scrobbles of her songs end up here due to Last. <a href="https://www.last.fm/music/+noredirect/Mal%C3%BA">Read more on Last.fm</a>', 'pais': 'Unknown'}, {'artista': 'Rodrigo', 'oyentes': '117473', 'reproducciones': '1282948', 'bio_resumen': 'Rodrigo Alejandro Bueno (born 24/5/1973 in Córdoba, Argentina; died 24/6/2000 in Buenos Aires, Argentina), also known by his stage name Rodrigo or nickname "El Potro", was a very popular cuarteto singer from Argentina. He is considered one of the most important singers of cuarteto music, as he brought this genre from his birth place in Córdoba to big popularity throughout Argentina.\n\nIf you\'re listening to, or looking for, classical music by the Spanish composer, please then consider going to artist Joaquín Rodrigo. <a href="https://www.last.fm/music/Rodrigo">Read more on Last.fm</a>', 'pais': 'Spain'}, {'artista': 'Sebastian', 'oyentes': '659554', 'reproducciones': '10579992', 'bio_resumen': '1) SebastiAn (born Sebastian Akchoté) is a French electro house artist whose reputation started with his first releases on Ed Banger Records in 2005 entitled \'Smoking Kills\' & \'H.A.L.\'. A string of remixes followed including Annie, Daft Punk, Cut Copy, Revl9n & label-mate Uffie. Summer 2006 saw the release of the Ross Ross Ross EP, as well as a remix for Kelis. His remix of Kavinsky\'s Testarossa Autodrive, titled Testarossa (SebastiAn Remix), is featured in the video game GTA IV. <a href="https://www.last.fm/music/Sebastian">Read more on Last.fm</a>', 'pais': 'France'}, {'artista': 'Andrés Cepeda', 'oyentes': '93675', 'reproducciones': '2401850', 'bio_resumen': '\nAndrés Cepeda es uno de los artistas colombianos de mayor reconocimiento a nivel nacional e internacional, sus bellas composiciones lo han consagrado como uno de los cantautores mas versátiles de Latinoamérica.\n\nAndrés Cepeda nació en Bogotá el 7 de julio de 1973; es el menor de una familia de cinco hermanos.\nSu talento lo obtuvo desde niño con tan solo 5 años decide comenzar sus estudios musicales tocando el piano, luego en su adolescencia <a href="https://www.last.fm/music/+noredirect/Andr%C3%A9s+Cepeda">Read more on Last.fm</a>', 'pais': 'Unknown'}, {'artista': 'Ricardo Arjona', 'oyentes': '389390', 'reproducciones': '9705412', 'bio_resumen': 'Edgar Ricardo Arjona Morales, (born 19 January 1964, Jocotenango, Guatemala), known as Ricardo Arjona (pronounced /aɾ\'xona/), is a popular Guatemalan singer. He has won two Grammy Awards from three nominations: The 2007 Grammy for Best Latin Pop Album and the 2006 Latin Grammy for Best Male Pop Vocal Album, both for his album Adentro, (2005).\n\nHistory\n\nRicardo was born in the village of Jocotenango, near Antigua, Guatemala to Ricardo Arjona Moscoso and Noemí Morales de Arjona. <a href="https://www.last.fm/music/Ricardo+Arjona">Read more on Last.fm</a>', 'pais': 'Unknown'}, {'artista': 'Marc Anthony', 'oyentes': '783158', 'reproducciones': '10327514', 'bio_resumen': 'Marco Antonio Muñiz (born September 16, 1964), better known by his stage name Marc Anthony.\n A New Yorker born and raised, the product of a music-loving Puerto Rican family, his parents named him Marco Antonio Muñíz in honor of the great Mexican balladeer of the same name. \nBorn Marco Antonio Muñiz September 16, 1964 (age 52)\nNew York City, New York, U.S.\nNationality American Puerto Rican\nOccupation Singer songwriter actor record producer television producer <a href="https://www.last.fm/music/Marc+Anthony">Read more on Last.fm</a>', 'pais': 'Mexico'}, {'artista': 'Melody', 'oyentes': '289999', 'reproducciones': '4120501', 'bio_resumen': '1) Melodía Ruiz Gutiérrez (born 12 October 1990), best known by her stage name Melody, is a Spanish singer. Melody became famous at the age of 10 with her song "El baile del gorila", one of the biggest summer hits of 2001 in Spain. She has released six albums and numerous singles. She represented Spain at the Eurovision Song Contest 2025 with the song "Esa diva".\n\n2) Gabriella Abreu Severino (born February 4, 2007), known professionally by her stage name Melody, is a Brazilian singer, songwriter, and musician. <a href="https://www.last.fm/music/Melody">Read more on Last.fm</a>', 'pais': 'Brazil'}, {'artista': 'Aleks Syntek', 'oyentes': '289794', 'reproducciones': '3337656', 'bio_resumen': 'Mexican Aleks Syntek was born in September 29 of 1969. \n\nThis talented musician has been involved in many different projects from advertisements to TV shows and movies. \n\nBy the late \'80s, Syntek, along with two friends, decided to form an alternative band. Their first record, called Hey Tú, was released by EMI in 1990, followed by Más Fuerte De Lo Que Pensaba in 1993. The latter included a contribution from former The Doors Ray Manzarek who played in a song called "Nuestras Costumbres."  <a href="https://www.last.fm/music/Aleks+Syntek">Read more on Last.fm</a>', 'pais': 'Mexico'}, {'artista': 'Chic Savanna', 'oyentes': '9', 'reproducciones': '11', 'bio_resumen': 'biografia no encontrada', 'pais': 'Unknown'}, {'artista': 'Raulin Rodriguez', 'oyentes': '96029', 'reproducciones': '855433', 'bio_resumen': 'Born in San Fernando de Monte Cristi, Monte Cristi in the Dominican Republic on June 16, 1970,related to the Zapata family of Monte cristi is one of the first major bachata artists to have national success and popularize this style of music in his country. Born in the northwest coast of the island, he toured with Antony Santos as a guitar player at age fifteen, and then went on to own band. <a href="https://www.last.fm/music/Raulin+Rodriguez">Read more on Last.fm</a>', 'pais': 'Unknown'}, {'artista': 'La Quinta Estacion', 'oyentes': '240147', 'reproducciones': '3185856', 'bio_resumen': 'La 5a Estacion is group of three Spaniards that left their native country and moved to Mexico to pursue a Musical career. Their first hit was "Donde Iran?" a pop rock tune featured on the Mexican Soap opera "Clase 406." Their first album is titled "Primera Toma." This first album was immediately followed by "Flores De Alquiler" that featured hits such as "El Sol No Regresa," "Daria," "Algo Mas," and "Nina." this album also had a cover track in tribute to Hombres G titled "Si Yo Fuera Mujer. <a href="https://www.last.fm/music/+noredirect/La+Quinta+Estacion">Read more on Last.fm</a>', 'pais': 'Mexico'}, {'artista': 'La Retrocumbia', 'oyentes': '129', 'reproducciones': '1733', 'bio_resumen': 'biografia no encontrada', 'pais': 'Unknown'}, {'artista': 'Mauricio & PalodeAgua', 'oyentes': '10810', 'reproducciones': '78944', 'bio_resumen': 'Mauricio & Palodeagua is a Colombian band, influenced by Carlos Vives and Fonseca rythms. It\'s a very well known group in Colombia and some latinamerican countries. <a href="https://www.last.fm/music/Mauricio+&+PalodeAgua">Read more on Last.fm</a>', 'pais': 'Colombia'}, {'artista': 'Monica Naranjo', 'oyentes': '101871', 'reproducciones': '1793680', 'bio_resumen': 'This is a wrong tag for Mónica Naranjo, please fix your tags.\n\n\n\n\n\n\n\nMonica Naranjo Carrasco (born May 23, 1974 in Figueras, a village in Catalonia near Cadaques, Spain) - one of the most popular Spanish female singer.\nShe started singing at a very young age. Cristobal Sansano became her first producer. After signing with Sony Music, she recorded her debut album Mónica Naranjo in 1994, resulting in the hit songs "Sola", "El amor coloca" or "Oyeme". <a href="https://www.last.fm/music/+noredirect/Monica+Naranjo">Read more on Last.fm</a>', 'pais': 'Spain'}, {'artista': 'La Fiesta', 'oyentes': '10201', 'reproducciones': '71899', 'bio_resumen': 'There is more than one artist under this name:\n\n1. La Fiesta is a cuarteto band from Córdoba, Argentina founded and fronted by Cristian Amato.\n\n2. La Fiesta is four-member pop group from Spain. <a href="https://www.last.fm/music/La+Fiesta">Read more on Last.fm</a>', 'pais': 'Unknown'}, {'artista': 'Wakal', 'oyentes': '9818', 'reproducciones': '81111', 'bio_resumen': 'Wakal \n(Jorge

In [47]:
df_artistas_latin_pop_LastFm = pd.DataFrame(lista_artistas)

In [50]:
df_artistas_latin_pop_LastFm

,artista,oyentes,reproducciones,bio_resumen,pais
0,Jon Secada,253200,1780136,"Juan Francisco Secada (born October 4, 1962 in...",Unknown
1,Noelia,82084,458386,There are several artists who perform under th...,Unknown
2,Los Legendarios,104518,843549,biografia no encontrada,Unknown
3,Geno,1998,8425,"Geno is a g-funk artist from Chicago, IL. He r...",Unknown
4,La Oreja de Van Gogh,629390,18638355,La Oreja de Van Gogh (English: Van Gogh's Ear)...,Netherlands
...,...,...,...,...,...
146,Laura Pausini,555670,21836726,Laura Pausini is a five-time Grammy Award winn...,Italy
147,Benny,141803,1135285,There are multiple artist called Benny:\n\n1. ...,Belgium
148,David Calzado Y Su Charanga Habanera,20640,258617,\n La Charanga Habanera y David Calzado Bio...,Unknown
149,Los Cachorros De Juan Villarreal,11123,95580,biografia no encontrada,Unknown
150,Damas Gratis,84912,1395783,Damas Gratis es un grupo musical de cumbia vil...,Unknown

In [ ]:
df_artistas_latin_pop_LastFm.to_csv("artista_latin_pop.csv", index=False, encoding="utf-8")

In [ ]:
### finalmente obtenermos otro df_cvs con los datos necesarios para realizar nuestras consultas en my SQL