In [1]:
import requests

from PIL import Image
from io import BytesIO
import matplotlib.pyplot as plt
import pandas as pd
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

import json

import time

In [ ]:
cliente = '#######'

In [3]:
# Información que Devuelve artist.getinfo: 
# 1. **Biografía:** en el campo bio. 
# 2. **Popularidad y Estadísticas:** campos listeners (oyentes únicos) y playcount (número total de reproducciones). 
# 3. **Artistas Similares:** Se encuentran en una lista bajo el campo similar.

In [4]:
cliente

genero = 'latin pop' #--> separandolo solo hay que modificar esta variable, es un codigo más limpio que podemos usar todas

limite = 50

parametros = {'method':'tag.getTopArtists', 'tag':genero, 'api_key': cliente,'format':'json', 'limit':limite, 'page':1}

In [5]:
URL = 'http://ws.audioscrobbler.com/2.0/'

respuesta = requests.get(URL, params=parametros)

In [6]:
datos_last_fm = respuesta.json()

In [7]:
len(datos_last_fm['topartists'])

2

In [8]:
claves_top = datos_last_fm['topartists']

In [9]:
claves_top.keys() #attr contiene los metadatos (atributos) de la solicitud, incluyendo la  page.

dict_keys(['artist', '@attr'])

In [10]:
nombre_artista = ['Shakira', 'Morat']
url_api = "http://ws.audioscrobbler.com/2.0/"
lista_artistas = []

In [11]:
def llamar_lastfm_api(method, artist_name, cliente):
        params = {'method': method,'artist': artist_name,'api_key': cliente,'format': 'json'}
        response = requests.get(url_api, params=params)
        if response.status_code == 200:
            return response.json()
        else:
            print(f"Error {response.status_code}: No se pudo obtener la información para el método {method}")
            return
print(f"Obteniendo detalles de: {nombre_artista}")

Obteniendo detalles de: ['Shakira', 'Morat']

In [12]:
artistas_a_consultar = ["Shakira", "Morat"]
lista_artistas = []
for nombre_artista in artistas_a_consultar:
    print(f"--- Consultando: {nombre_artista} ---")
    datos_artista = llamar_lastfm_api('artist.getinfo', nombre_artista, cliente)
    if datos_artista and 'artist' in datos_artista:
        artista_data = datos_artista['artist']
        oyentes = artista_data.get('stats', {}).get('listeners', 'arista no encontrado')
        reproducciones = artista_data.get('stats', {}).get('playcount', 'N/D')
        bio_content = artista_data.get('bio', {}).get('content', '')
        if not bio_content or bio_content.strip() == "":
            bio_resumen = 'biografia no encontrada'
        else:
            bio_resumen = artista_data.get('bio', {}).get('summary')
        lista_artistas_dict = {'artista': artista_data.get('name', nombre_artista),'oyentes': oyentes, 'reproducciones': reproducciones, 'bio_resumen': bio_resumen}
        lista_artistas.append(lista_artistas_dict)
        print(f"Datos de {nombre_artista} procesados y guardados.")
    else:
        print(f"No se pudo obtener información de {nombre_artista}")

--- Consultando: Shakira ---
Datos de Shakira procesados y guardados.
--- Consultando: Morat ---
Datos de Morat procesados y guardados.

In [13]:
lista_artistas

[{'artista': 'Shakira',
  'oyentes': '4650484',
  'reproducciones': '168894003',
  'bio_resumen': 'Shakira Isabel Mebarak Ripoll is a Colombian singer. Born and raised in Barranquilla, She made her recording debut with Sony Music Colombia at the age of 13. Following the commercial failure of her first two albums, Magia (1991) and Peligro (1993), she rose to prominence in Hispanic countries with her next albums, Pies Descalzos (1995) and Dónde Están los Ladrones? (1998). She entered the English-language market with her fifth album, Laundry Service (2001), which sold over 13 million copies worldwide. <a href="https://www.last.fm/music/Shakira">Read more on Last.fm</a>'},
 {'artista': 'Morat',
  'oyentes': '288260',
  'reproducciones': '20864497',
  'bio_resumen': 'Morat is a Colombian band formed in the country\'s capital city, Bogotá. The band is formed by Juan Pablo Isaza (guitars and vocals), Juan Pablo Villamil (banjo and vocals) and the brothers Simón Vargas (bass and choruses) and Martín Vargas (percussion and choirs). Previously, until the end of 2016, drummer Alejandro Posada had been in the band, but the percussionist had to leave the project, being subsequently replaced by Martín Vargas.\n\nThey began to stand out internationally in 2015 <a href="https://www.last.fm/music/Morat">Read more on Last.fm</a>'}]

In [14]:
## quiero traer mi archivo json y leerlo aquí (load)

In [15]:
ruta_json = 'artistas_latin_pop.json'

In [16]:
# with open(ruta_json, 'r', encoding='utf-8') as archivo:
#         artistas_a_consultar = json.load(archivo)
#         print(f"Lista de artistas: {artistas_a_consultar}")

In [17]:
## en la lista json tenemos duplicados, por lo que no nos sirve

In [18]:
lista_artistas

[{'artista': 'Shakira',
  'oyentes': '4650484',
  'reproducciones': '168894003',
  'bio_resumen': 'Shakira Isabel Mebarak Ripoll is a Colombian singer. Born and raised in Barranquilla, She made her recording debut with Sony Music Colombia at the age of 13. Following the commercial failure of her first two albums, Magia (1991) and Peligro (1993), she rose to prominence in Hispanic countries with her next albums, Pies Descalzos (1995) and Dónde Están los Ladrones? (1998). She entered the English-language market with her fifth album, Laundry Service (2001), which sold over 13 million copies worldwide. <a href="https://www.last.fm/music/Shakira">Read more on Last.fm</a>'},
 {'artista': 'Morat',
  'oyentes': '288260',
  'reproducciones': '20864497',
  'bio_resumen': 'Morat is a Colombian band formed in the country\'s capital city, Bogotá. The band is formed by Juan Pablo Isaza (guitars and vocals), Juan Pablo Villamil (banjo and vocals) and the brothers Simón Vargas (bass and choruses) and Martín Vargas (percussion and choirs). Previously, until the end of 2016, drummer Alejandro Posada had been in the band, but the percussionist had to leave the project, being subsequently replaced by Martín Vargas.\n\nThey began to stand out internationally in 2015 <a href="https://www.last.fm/music/Morat">Read more on Last.fm</a>'}]

In [19]:
df_latin_pop_LastFm = pd.DataFrame(lista_artistas) 

df_latin_pop_LastFm.head()

,artista,oyentes,reproducciones,bio_resumen
0,Shakira,4650484,168894003,Shakira Isabel Mebarak Ripoll is a Colombian s...
1,Morat,288260,20864497,Morat is a Colombian band formed in the countr...

In [20]:
df_latin_pop_LastFm.to_csv("df_latin_pop_LastFm.csv", index=False, encoding="utf-8")

In [21]:
df = pd.read_csv('../../api_spotify/archivos_csv/df_latin_pop.csv') ##leemos el df

FileNotFoundError: [Errno 2] No such file or directory: '../../api_spotify/archivos_csv/df_latin_pop.csv'

In [ ]:
df

,Artista,Género,Tipo,Nombre,Año,ID
0,La Oreja de Van Gogh,latin pop,track,Pop,2000,4FXSEdmbbeGmPIQltH27C8
1,Thalia,latin pop,track,Entre El Mar Y Una Estrella,2000,2KNtKG2X0jpOIgVunVbAkQ
2,Ricky Martin,latin pop,track,She Bangs - Spanish Version,2000,4ti5pZ0zs1PDf1eQswskFB
3,Rodrigo,latin pop,track,Amor Clasificado,2000,5MK642wCaNr9hRDZ3kWyDX
4,Rodrigo,latin pop,track,Soy Cordobes,2000,5wG4J1UECH0c42YhMhSkcS
...,...,...,...,...,...,...
745,Carlos Vives,latin pop,track,La Maravilla,2004,5Jivv7trOtgHlnaNAiPEnN
746,Alejandro Sanz,latin pop,track,El alma al aire,2004,7s4ggtq4icIPCo9wLk5vss
747,Franco De Vita,latin pop,track,Ay Dios,2004,0Sd0bKypMwcUTUgHH9TCov
748,Damas Gratis,latin pop,track,Popurri / El Ganador - En Vivo,2004,2vVQgTGlENx1znBphTIX3Z
749,Alejandro Sanz,latin pop,track,Y sólo se me ocurre amarte,2004,3zvnloMEkCiIFRsZDUJPaW

In [ ]:
df.columns = df.columns.str.strip()

In [ ]:
artistas = df['Artista'] ##accedemos a artistas

In [ ]:
artistas

0      La Oreja de Van Gogh
1                    Thalia
2              Ricky Martin
3                   Rodrigo
4                   Rodrigo
               ...
745            Carlos Vives
746          Alejandro Sanz
747          Franco De Vita
748            Damas Gratis
749          Alejandro Sanz
Name: Artista, Length: 750, dtype: object

In [ ]:
artistas_unicos = set(artistas) ## eliminamos duplicados

In [ ]:
artistas_unicos

{'Alejandra Guzman',
 'Alejandro Fernández',
 'Alejandro Parreño',
 'Alejandro Sanz',
 'Aleks Syntek',
 'Alexandre Pires',
 'Amparanoia',
 'Ana Torroja',
 'Andrés Cepeda',
 'Andy Aguilera',
 'Armando Manzanero',
 'Bacanos',
 'Bacilos',
 'Banda XXI',
 'Belinda',
 'Benny',
 'Beny Moré',
 'Bertin Osborne',
 'Beto Quintanilla',
 'Cabas',
 'Carlos Ponce',
 'Carlos Vives',
 'Celia Cruz',
 'Chayanne',
 'Clave Cubana',
 'Cristian Castro',
 'Cubismo',
 'Damas Gratis',
 'Danni Ubeda',
 'David Bisbal',
 'David Calzado y su Charanga Habanera',
 'Debelah Morgan',
 'Diego Torres',
 'Donato Y Estefano',
 'Draco Rosa',
 'Edwin Bonilla',
 'El Cuarteto De Nos',
 'Enrique Iglesias',
 'Eydie Gormé',
 'Fey',
 'Francisco Céspedes',
 'Franco De Vita',
 'Geno',
 'Gloria Estefan',
 'Gloria Trevi',
 'Glup!',
 'Grupo Aliados',
 'Grupo Exterminador',
 'Guaraná',
 'Ha*Ash',
 'Huey Dunbar',
 'Issac Delgado',
 'Jarabe De Palo',
 'Jean Carlos',
 'Jennifer Lopez',
 'Jeremías',
 'Jimmy Bosch',
 'Jimmy Gutierrez',
 'Jimmy Sabater',
 'Joaquín Sabina',
 'Jon Secada',
 'José José',
 'Juan Formell y Los Van Van',
 'Juanes',
 'Julieta Venegas',
 'Julio Iglesias',
 'KEMA',
 'LU',
 'La Barra',
 'La Fiesta',
 'La Gran Banda',
 'La Mona Jimenez',
 'La Mosca',
 'La Oreja de Van Gogh',
 'La Quinta Estacion',
 'La Retrocumbia',
 'La-33',
 'Latin Dreams',
 'Laura Miller',
 'Laura Pausini',
 'Lemon',
 'Lorena',
 'Los Cachorros de Juan Villarreal',
 "Los Chaque's",
 'Los Fachero´s',
 'Los Incomparables De Tijuana',
 'Los Legendarios',
 'Los Originales De San Juan',
 'Los Palmeras',
 'Los Playeros',
 'Los Razos',
 'Los Tigres Del Norte',
 'Los Tucanes De Tijuana',
 'Lucas Arnau',
 'Luis Alberto Posada',
 'Luis Fonsi',
 'Luis Miguel',
 'Luisito Muñoz',
 'Mai Meneses',
 'Malú',
 'Marc Anthony',
 'Marcela Morelo',
 'María Bestar',
 'Mauricio & PalodeAgua',
 'Melody',
 'Michael Bublé',
 'Miguel Bosé',
 'Miranda!',
 "Mo' Horizons",
 'Moises Angulo',
 'Monica Naranjo',
 'Murga Contrafarsa',
 'Nek',
 'Nika',
 'Noelia',
 'OBK',
 'Obie Bermudez',
 'Orquesta Tabaco Y Ron',
 'Paco Pineda y Su Grupo Tex Mex',
 'Papá Levante',
 'Patricia Manterola',
 'Paulina Rubio',
 'Pepe Aguilar',
 'Plastilina Mosh',
 'Polo Montañez',
 'Qarto Aparte',
 'RBD',
 'Raul Paz',
 'Raulin Rodriguez',
 'Rey Ruiz',
 'Ricardo Arjona',
 'Ricardo Montaner',
 'Ricky Martin',
 'Rios De Gloria',
 'Rodrigo',
 'Sabroso',
 'Salsa Celtica',
 'Sebastian',
 'Shakira',
 'Shalim',
 'Sin Bandera',
 'Skeewiff',
 'Thalia',
 'Tiziano Ferro',
 'Tommy Torres',
 'Tranzas',
 'Tru La La',
 'Víctor Manuelle',
 'Wakal',
 'Walter Olmos',
 'Willie Bobo',
 'Yahir',
 'Yuri Buenaventura',
 'Yámana'}

In [ ]:
 ## introducimos artistas unicos

In [ ]:
artistas_unicos
lista_artistas = []
for nombre_artista in artistas_unicos:
    print(f"--- Consultando: {nombre_artista} ---")
    datos_artista = llamar_lastfm_api('artist.getinfo', nombre_artista, cliente)
    if datos_artista and 'artist' in datos_artista:
        artista_data = datos_artista['artist']
        oyentes = artista_data.get('stats', {}).get('listeners', 'arista no encontrado')
        reproducciones = artista_data.get('stats', {}).get('playcount', 'N/D')
        bio_content = artista_data.get('bio', {}).get('content', '')
        if not bio_content or bio_content.strip() == "":
            bio_resumen = 'biografia no encontrada'
        else:
            bio_resumen = artista_data.get('bio', {}).get('summary')
        lista_artistas_dict = {'artista': artista_data.get('name', nombre_artista),'oyentes': oyentes, 'reproducciones': reproducciones, 'bio_resumen': bio_resumen}
        lista_artistas.append(lista_artistas_dict)
        print(f"Datos de {nombre_artista} procesados y guardados.")
    else:
        print(f"No se pudo obtener información de {nombre_artista}")

--- Consultando: Joaquín Sabina ---
Datos de Joaquín Sabina procesados y guardados.
--- Consultando: Los Incomparables De Tijuana ---
Datos de Los Incomparables De Tijuana procesados y guardados.
--- Consultando: Luisito Muñoz ---
Datos de Luisito Muñoz procesados y guardados.
--- Consultando: Julieta Venegas ---
Datos de Julieta Venegas procesados y guardados.
--- Consultando: Beto Quintanilla ---
Datos de Beto Quintanilla procesados y guardados.
--- Consultando: Clave Cubana ---
Datos de Clave Cubana procesados y guardados.
--- Consultando: La Mosca ---
Datos de La Mosca procesados y guardados.
--- Consultando: Polo Montañez ---
Datos de Polo Montañez procesados y guardados.
--- Consultando: Beny Moré ---
Datos de Beny Moré procesados y guardados.
--- Consultando: Tranzas ---
Datos de Tranzas procesados y guardados.
--- Consultando: Bacilos ---
Datos de Bacilos procesados y guardados.
--- Consultando: Salsa Celtica ---
Datos de Salsa Celtica procesados y guardados.
--- Consultando: Los Tigres Del Norte ---
Datos de Los Tigres Del Norte procesados y guardados.
--- Consultando: Cubismo ---
Datos de Cubismo procesados y guardados.
--- Consultando: Rios De Gloria ---
Datos de Rios De Gloria procesados y guardados.
--- Consultando: Jimmy Bosch ---
Datos de Jimmy Bosch procesados y guardados.
--- Consultando: Mo' Horizons ---
Datos de Mo' Horizons procesados y guardados.
--- Consultando: Obie Bermudez ---
Datos de Obie Bermudez procesados y guardados.
--- Consultando: Los Tucanes De Tijuana ---
Datos de Los Tucanes De Tijuana procesados y guardados.
--- Consultando: La Retrocumbia ---
Datos de La Retrocumbia procesados y guardados.
--- Consultando: Skeewiff ---
Datos de Skeewiff procesados y guardados.
--- Consultando: Enrique Iglesias ---
Datos de Enrique Iglesias procesados y guardados.
--- Consultando: Carlos Ponce ---
Datos de Carlos Ponce procesados y guardados.
--- Consultando: Melody ---
Datos de Melody procesados y guardados.
--- Consultando: El Cuarteto De Nos ---
Datos de El Cuarteto De Nos procesados y guardados.
--- Consultando: Ana Torroja ---
Datos de Ana Torroja procesados y guardados.
--- Consultando: Willie Bobo ---
Datos de Willie Bobo procesados y guardados.
--- Consultando: Malú ---
Datos de Malú procesados y guardados.
--- Consultando: Luis Alberto Posada ---
Datos de Luis Alberto Posada procesados y guardados.
--- Consultando: José José ---
Datos de José José procesados y guardados.
--- Consultando: Jon Secada ---
Datos de Jon Secada procesados y guardados.
--- Consultando: Los Legendarios ---
Datos de Los Legendarios procesados y guardados.
--- Consultando: Paco Pineda y Su Grupo Tex Mex ---
Datos de Paco Pineda y Su Grupo Tex Mex procesados y guardados.
--- Consultando: Lemon ---
Datos de Lemon procesados y guardados.
--- Consultando: Yuri Buenaventura ---
Datos de Yuri Buenaventura procesados y guardados.
--- Consultando: Jarabe De Palo ---
Datos de Jarabe De Palo procesados y guardados.
--- Consultando: Gloria Estefan ---
Datos de Gloria Estefan procesados y guardados.
--- Consultando: Armando Manzanero ---
Datos de Armando Manzanero procesados y guardados.
--- Consultando: Bertin Osborne ---
Datos de Bertin Osborne procesados y guardados.
--- Consultando: Qarto Aparte ---
Datos de Qarto Aparte procesados y guardados.
--- Consultando: Aleks Syntek ---
Datos de Aleks Syntek procesados y guardados.
--- Consultando: Luis Miguel ---
Datos de Luis Miguel procesados y guardados.
--- Consultando: Raulin Rodriguez ---
Datos de Raulin Rodriguez procesados y guardados.
--- Consultando: OBK ---
Datos de OBK procesados y guardados.
--- Consultando: Ricardo Montaner ---
Datos de Ricardo Montaner procesados y guardados.
--- Consultando: Laura Miller ---
Datos de Laura Miller procesados y guardados.
--- Consultando: Ha*Ash ---
Datos de Ha*Ash procesados y guardados.
--- Consultando: Donato Y Estefano ---
Datos de Donato Y Estefano procesados y guardados.
--- Consultando: La Oreja de Van Gogh ---
Datos de La Oreja de Van Gogh procesados y guardados.
--- Consultando: Orquesta Tabaco Y Ron ---
Datos de Orquesta Tabaco Y Ron procesados y guardados.
--- Consultando: Bacanos ---
Datos de Bacanos procesados y guardados.
--- Consultando: Damas Gratis ---
Datos de Damas Gratis procesados y guardados.
--- Consultando: La Gran Banda ---
Datos de La Gran Banda procesados y guardados.
--- Consultando: Marcela Morelo ---
Datos de Marcela Morelo procesados y guardados.
--- Consultando: Paulina Rubio ---
Datos de Paulina Rubio procesados y guardados.
--- Consultando: Glup! ---
Datos de Glup! procesados y guardados.
--- Consultando: Shakira ---
Datos de Shakira procesados y guardados.
--- Consultando: Mauricio & PalodeAgua ---
Datos de Mauricio & PalodeAgua procesados y guardados.
--- Consultando: Rodrigo ---
Datos de Rodrigo procesados y guardados.
--- Consultando: Mai Meneses ---
Datos de Mai Meneses procesados y guardados.
--- Consultando: Ricky Martin ---
Datos de Ricky Martin procesados y guardados.
--- Consultando: Belinda ---
Datos de Belinda procesados y guardados.
--- Consultando: María Bestar ---
Datos de María Bestar procesados y guardados.
--- Consultando: Alexandre Pires ---
Datos de Alexandre Pires procesados y guardados.
--- Consultando: Jean Carlos ---
Datos de Jean Carlos procesados y guardados.
--- Consultando: Draco Rosa ---
Datos de Draco Rosa procesados y guardados.
--- Consultando: Los Playeros ---
Datos de Los Playeros procesados y guardados.
--- Consultando: Debelah Morgan ---
Datos de Debelah Morgan procesados y guardados.
--- Consultando: Banda XXI ---
Datos de Banda XXI procesados y guardados.
--- Consultando: Amparanoia ---
Datos de Amparanoia procesados y guardados.
--- Consultando: Andy Aguilera ---
Datos de Andy Aguilera procesados y guardados.
--- Consultando: Jimmy Sabater ---
Datos de Jimmy Sabater procesados y guardados.
--- Consultando: Wakal ---
Datos de Wakal procesados y guardados.
--- Consultando: Andrés Cepeda ---
Datos de Andrés Cepeda procesados y guardados.
--- Consultando: Fey ---
Datos de Fey procesados y guardados.
--- Consultando: Los Fachero´s ---
Datos de Los Fachero´s procesados y guardados.
--- Consultando: Jennifer Lopez ---
Datos de Jennifer Lopez procesados y guardados.
--- Consultando: Eydie Gormé ---
Datos de Eydie Gormé procesados y guardados.
--- Consultando: Juan Formell y Los Van Van ---
Datos de Juan Formell y Los Van Van procesados y guardados.
--- Consultando: Noelia ---
Datos de Noelia procesados y guardados.
--- Consultando: Papá Levante ---
Datos de Papá Levante procesados y guardados.
--- Consultando: La Mona Jimenez ---
Datos de La Mona Jimenez procesados y guardados.
--- Consultando: Los Palmeras ---
Datos de Los Palmeras procesados y guardados.
--- Consultando: LU ---
Datos de LU procesados y guardados.
--- Consultando: Edwin Bonilla ---
Datos de Edwin Bonilla procesados y guardados.
--- Consultando: Yámana ---
Datos de Yámana procesados y guardados.
--- Consultando: Thalia ---
Datos de Thalia procesados y guardados.
--- Consultando: Moises Angulo ---
Datos de Moises Angulo procesados y guardados.
--- Consultando: Los Razos ---
Datos de Los Razos procesados y guardados.
--- Consultando: Cabas ---
Datos de Cabas procesados y guardados.
--- Consultando: Diego Torres ---
Datos de Diego Torres procesados y guardados.
--- Consultando: Franco De Vita ---
Datos de Franco De Vita procesados y guardados.
--- Consultando: David Bisbal ---
Datos de David Bisbal procesados y guardados.
--- Consultando: Celia Cruz ---
Datos de Celia Cruz procesados y guardados.
--- Consultando: Guaraná ---
Datos de Guaraná procesados y guardados.
--- Consultando: La Fiesta ---
Datos de La Fiesta procesados y guardados.
--- Consultando: Walter Olmos ---
Datos de Walter Olmos procesados y guardados.
--- Consultando: Jimmy Gutierrez ---
Datos de Jimmy Gutierrez procesados y guardados.
--- Consultando: Víctor Manuelle ---
Datos de Víctor Manuelle procesados y guardados.
--- Consultando: Tru La La ---
Datos de Tru La La procesados y guardados.
--- Consultando: Luis Fonsi ---
Datos de Luis Fonsi procesados y guardados.
--- Consultando: Geno ---
Datos de Geno procesados y guardados.
--- Consultando: Benny ---
Datos de Benny procesados y guardados.
--- Consultando: Laura Pausini ---
Datos de Laura Pausini procesados y guardados.
--- Consultando: Chayanne ---
Datos de Chayanne procesados y guardados.
--- Consultando: Lucas Arnau ---
Datos de Lucas Arnau procesados y guardados.
--- Consultando: Alejandro Fernández ---
Datos de Alejandro Fernández procesados y guardados.
--- Consultando: Miguel Bosé ---
Datos de Miguel Bosé procesados y guardados.
--- Consultando: Sebastian ---
Datos de Sebastian procesados y guardados.
--- Consultando: Marc Anthony ---
Datos de Marc Anthony procesados y guardados.
--- Consultando: KEMA ---
Datos de KEMA procesados y guardados.
--- Consultando: Monica Naranjo ---
Datos de Monica Naranjo procesados y guardados.
--- Consultando: Sin Bandera ---
Datos de Sin Bandera procesados y guardados.
--- Consultando: Miranda! ---
Datos de Miranda! procesados y guardados.
--- Consultando: Pepe Aguilar ---
Datos de Pepe Aguilar procesados y guardados.
--- Consultando: Yahir ---
Datos de Yahir procesados y guardados.
--- Consultando: Nek ---
Datos de Nek procesados y guardados.
--- Consultando: Francisco Céspedes ---
Datos de Francisco Céspedes procesados y guardados.
--- Consultando: Tiziano Ferro ---
Datos de Tiziano Ferro procesados y guardados.
--- Consultando: La-33 ---
Datos de La-33 procesados y guardados.
--- Consultando: RBD ---
Datos de RBD procesados y guardados.
--- Consultando: La Barra ---
Datos de La Barra procesados y guardados.
--- Consultando: Julio Iglesias ---
Datos de Julio Iglesias procesados y guardados.
--- Consultando: Alejandro Sanz ---
Datos de Alejandro Sanz procesados y guardados.
--- Consultando: Ricardo Arjona ---
Datos de Ricardo Arjona procesados y guardados.
--- Consultando: La Quinta Estacion ---
Datos de La Quinta Estacion procesados y guardados.
--- Consultando: Issac Delgado ---
Datos de Issac Delgado procesados y guardados.
--- Consultando: Gloria Trevi ---
Datos de Gloria Trevi procesados y guardados.
--- Consultando: Grupo Aliados ---
Datos de Grupo Aliados procesados y guardados.
--- Consultando: Latin Dreams ---
Datos de Latin Dreams procesados y guardados.
--- Consultando: Michael Bublé ---
Datos de Michael Bublé procesados y guardados.
--- Consultando: Cristian Castro ---
Datos de Cristian Castro procesados y guardados.
--- Consultando: Huey Dunbar ---
Datos de Huey Dunbar procesados y guardados.
--- Consultando: Carlos Vives ---
Datos de Carlos Vives procesados y guardados.
--- Consultando: Los Chaque's ---
Datos de Los Chaque's procesados y guardados.
--- Consultando: Raul Paz ---
Datos de Raul Paz procesados y guardados.
--- Consultando: David Calzado y su Charanga Habanera ---
Datos de David Calzado y su Charanga Habanera procesados y guardados.
--- Consultando: Rey Ruiz ---
Datos de Rey Ruiz procesados y guardados.
--- Consultando: Alejandro Parreño ---
Datos de Alejandro Parreño procesados y guardados.
--- Consultando: Los Originales De San Juan ---
Datos de Los Originales De San Juan procesados y guardados.
--- Consultando: Alejandra Guzman ---
Datos de Alejandra Guzman procesados y guardados.
--- Consultando: Jeremías ---
Datos de Jeremías procesados y guardados.
--- Consultando: Juanes ---
Datos de Juanes procesados y guardados.
--- Consultando: Murga Contrafarsa ---
Datos de Murga Contrafarsa procesados y guardados.
--- Consultando: Plastilina Mosh ---
Datos de Plastilina Mosh procesados y guardados.
--- Consultando: Tommy Torres ---
Datos de Tommy Torres procesados y guardados.
--- Consultando: Danni Ubeda ---
Datos de Danni Ubeda procesados y guardados.
--- Consultando: Shalim ---
Datos de Shalim procesados y guardados.
--- Consultando: Nika ---
Datos de Nika procesados y guardados.
--- Consultando: Lorena ---
Datos de Lorena procesados y guardados.
--- Consultando: Patricia Manterola ---
Datos de Patricia Manterola procesados y guardados.
--- Consultando: Grupo Exterminador ---
Datos de Grupo Exterminador procesados y guardados.
--- Consultando: Sabroso ---
Datos de Sabroso procesados y guardados.
--- Consultando: Los Cachorros de Juan Villarreal ---
Datos de Los Cachorros de Juan Villarreal procesados y guardados.

In [ ]:
len(lista_artistas)

154

In [ ]:
df_artistas_latin_pop_LastFm = pd.DataFrame(lista_artistas)

In [ ]:
df_artistas_latin_pop_LastFm

,artista,oyentes,reproducciones,bio_resumen
0,Joaquín Sabina,231870,7438578,"Joaquín Ramón Martínez Sabina (Úbeda, Jaén, Sp..."
1,Los Incomparables De Tijuana,13277,88900,A Norteño Group Formed in Tijuana México in 19...
2,LUISITO MUÑOZ,4458,40482,biografia no encontrada
3,Julieta Venegas,771261,19578941,"Julieta Venegas (born November 24, 1970) is a ..."
4,Beto Quintanilla,31943,476522,"Norberto ""Beto"" Quintanilla Iracheta (May 23, ..."
...,...,...,...,...
149,Lorena,17584,189660,There are more than one female artist named LO...
150,Patricia Manterola,19916,124238,"Singer, actress and host, Patricia Manterola i..."
151,Grupo Exterminador,62441,504018,Hablar del GRUPO EXTERMINADOR es hablar de ori...
152,Sabroso,11549,119500,biografia no encontrada
153,Los Cachorros De Juan Villarreal,11147,95971,biografia no encontrada

In [ ]:
## convertimos nuevamente en df y en csv

In [ ]:
df_artistas_latin_pop_LastFm.to_csv("artista_latin_pop.csv", index=False, encoding="utf-8")

In [ ]:
## debemos enlazar en la consulta el país, y debe proceder de biografía

In [ ]:
## generamos un diccionario BASE, formado por GENTILICIOS.

In [ ]:
PAIS_A_GENTILICIO = {
    "Afghanistan": "Afghan",
    "Albania": "Albanian",
    "Algeria": "Algerian",
    "Argentina": "Argentinian",
    "Australia": "Australian",
    "Austria": "Austrian",
    "Belgium": "Belgian",
    "Bolivia": "Bolivian",
    "Brazil": "Brazilian",
    "Canada": "Canadian",
    "Chile": "Chilean",
    "China": "Chinese",
    "Colombia": "Colombian",
    "Costa Rica": "Costa Rican",
    "Cuba": "Cuban",
    "Denmark": "Dane",
    "Egypt": "Egyptian",
    "France": "French",
    "Germany": "German",
    "Greece": "Greek",
    "India": "Indian",
    "Indonesia": "Indonesian",
    "Ireland": "Irish",
    "Italy": "Italian",
    "Jamaica": "Jamaican",
    "Japan": "Japanese",
    "Mexico": "Mexican",
    "Netherlands": "Dutch",
    "New Zealand": "New Zealander",
    "Nigeria": "Nigerian",
    "Norway": "Norwegian",
    "Peru": "Peruvian",
    "Poland": "Pole",
    "Portugal": "Portuguese",
    "Russia": "Russian",
    "South Korea": "South Korean",
    "Spain": "Spaniard",
    "Sweden": "Swede",
    "Turkey": "Turk",
    "Ukraine": "Ukrainian",
    "United Kingdom": "Briton",
    "United States": "American",
    "United States_adj": "American",
    "United Kingdom_adj": "British",
    "France_adj": "French",
    "Germany_adj": "German",
    "Spain_adj": "Spanish"}

In [ ]:
# DICCIONARIO INVERTIDO PARA BÚSQUEDA EFICIENTE
# Clave: Gentilicio (lo que busco en la bio), Valor: País
GENTILICIO_A_PAIS = {gentilicio.lower(): pais.replace('_adj', '')
    for pais, gentilicio in PAIS_A_GENTILICIO.items()}

In [ ]:
def extraer_pais_de_biografia(bio_resumen, gentilicio_a_pais_map):
    bio_normalizada = bio_resumen.lower()
    for gentilicio, pais in gentilicio_a_pais_map.items():
        # Usamos ' ' + gentilicio + ' ' para buscar la palabra completa y evitar coincidencias parciales
        if f' {gentilicio} ' in bio_normalizada or bio_normalizada.startswith(f'{gentilicio} '):
            return pais
        
        if bio_normalizada.endswith(gentilicio):
             return pais
    return ''

for artista_data in lista_artistas:
    bio = artista_data['bio_resumen']
    pais_encontrado = extraer_pais_de_biografia(bio, GENTILICIO_A_PAIS)
    artista_data['pais'] = pais_encontrado #aqui agregamos la clave pais en nuestro diccionario
print(lista_artistas)

[{'artista': 'Joaquín Sabina', 'oyentes': '231870', 'reproducciones': '7438578', 'bio_resumen': 'Joaquín Ramón Martínez Sabina (Úbeda, Jaén, Spain, 12 February 1949), known artistically as Joaquín Sabina, is a singer - songwriter, and poet. He has released fourteen studio albums, two live albums, and three compilation albums. He has collaborated and composed songs for Ana Belén and Miguel Ríos amongst others.\n\nJoaquín Sabina, is the second son of Adela Sabina del Campo and Jerónimo Martinez Gallego, which was a policeman. He attended <a href="https://www.last.fm/music/+noredirect/Joaqu%C3%ADn+Sabina">Read more on Last.fm</a>', 'pais': ''}, {'artista': 'Los Incomparables De Tijuana', 'oyentes': '13277', 'reproducciones': '88900', 'bio_resumen': 'A Norteño Group Formed in Tijuana México in 1984 and similar to Los Tucanes De Tijuana <a href="https://www.last.fm/music/Los+Incomparables+De+Tijuana">Read more on Last.fm</a>', 'pais': ''}, {'artista': 'LUISITO MUÑOZ', 'oyentes': '4458', 'reproducciones': '40482', 'bio_resumen': 'biografia no encontrada', 'pais': ''}, {'artista': 'Julieta Venegas', 'oyentes': '771261', 'reproducciones': '19578941', 'bio_resumen': 'Julieta Venegas (born November 24, 1970) is a successful Mexican singer and songwriter of Latin music. She was born in Long Beach, California, but raised in Tijuana, Baja California and has a twin sister Yvonne who is a photographer. She was a former member of the band "Tijuana No". Julieta plays numerous instruments including acoustic guitar, accordion, and keyboard. She won the 2004 Latin Grammy for Best Vocal Rock Album (Sí).\nAlbums. She is radicated in Mexico City <a href="https://www.last.fm/music/Julieta+Venegas">Read more on Last.fm</a>', 'pais': 'Mexico'}, {'artista': 'Beto Quintanilla', 'oyentes': '31943', 'reproducciones': '476522', 'bio_resumen': 'Norberto "Beto" Quintanilla Iracheta (May 23, 1948 – March 18, 2007) was a Regional Mexican singer and songwriter. He was known as "El Mero León del Corrido" (The Lion of the Corrido)\n\nBiography:\nBeto Quintanilla was originally from General Terán, a small town in Nuevo León. The date of his birth is unknown, but was some time around 1948. As a child, Quintanilla composed poems or odes to his mother, his teacher, his school, and his country. He <a href="https://www.last.fm/music/Beto+Quintanilla">Read more on Last.fm</a>', 'pais': 'Mexico'}, {'artista': 'Clave Cubana', 'oyentes': '693', 'reproducciones': '3981', 'bio_resumen': 'biografia no encontrada', 'pais': ''}, {'artista': 'La Mosca', 'oyentes': '75882', 'reproducciones': '464821', 'bio_resumen': 'Si bien la formación actual del grupo se consolida en marzo de 1995, la historia de la banda se remonta a comienzos de los noventa con "La Reggae & Roll Band", quienes hacían covers y algunos temas propios en la zona de Ramallo. Simultáneamente existían otras bandas entre las que se destacaba "Damas gratis" liderada por Guillermo Novellis.\nTras la disolución de "Damas gratis", Fernando Castro, que era el baterista y uno de los fundadores (de La Reggae)  <a href="https://www.last.fm/music/+noredirect/La+Mosca">Read more on Last.fm</a>', 'pais': ''}, {'artista': 'Polo Montañez', 'oyentes': '50260', 'reproducciones': '346448', 'bio_resumen': 'Polo Montañez (June 5, 1955 - November 26, 2002) was a Cuban singer and songwriter\nMontañez was born Fernando Borrego Linares in Sierra del Rosario, Pinar del Río, in a farm known as El Brujito. At an early age he worked various jobs including driving a tractor, milking cows, making coal, assisting on the family farm, and as a lumberjack. In his spare time, Montañez would go from house to house singing and later began to sing in local parties and family gatherings. <a href="https://www.last.fm/music/+noredirect/Polo+Monta%C3%B1ez">Read more on Last.fm</a>', 'pais': 'Cuba'}, {'artista': 'Beny Moré', 'oyentes': '138009', 'reproducciones': '818679', 'bio_resumen': 'Beny Moré (sometimes Benny Moré, Benny More or Beny More) (August 24, 1919 – February 19, 1963) is considered by many fans of Cuban music as the greatest Cuban singer of all time.\nHe was gifted with an innate musicality and fluid tenor voice which he colored and phrased with great expressivity. Moré was a master of all the genres of Cuban music, including son montuno, mambo, guaracha, guajira, cha cha cha, afro, canción, guaguancó, and bolero. <a href="https://www.last.fm/music/+noredirect/Beny+Mor%C3%A9">Read more on Last.fm</a>', 'pais': 'Cuba'}, {'artista': 'Tranzas', 'oyentes': '79371', 'reproducciones': '600246', 'bio_resumen': 'Tranzas is an Ecuatorian music band. <a href="https://www.last.fm/music/Tranzas">Read more on Last.fm</a>', 'pais': ''}, {'artista': 'Bacilos', 'oyentes': '358611', 'reproducciones': '4301899', 'bio_resumen': 'Bacilos is a latin music group based in Miami, Florida, United States.\n\nThe band was formed in 1995 by three students of the University of Miami and was named after the Spanish word for bacillus. Originally a quartet, the band drew influences from Cuban folk singer Silvio Rodríguez and Argentinian rock singer Fito Páez. The band eventually became a trio consisting of Colombian singer and guitarist Jorge Villamizar, bassist André Lopes and percussionist José Javier Freire before releasing an independent album Madera in 1999. <a href="https://www.last.fm/music/Bacilos">Read more on Last.fm</a>', 'pais': 'Argentina'}, {'artista': 'Salsa Celtica', 'oyentes': '23762', 'reproducciones': '193695', 'bio_resumen': 'Salsa Celtica - an 11 piece world music fusion band coming from Edinburgh, Scotland, formed in 1995. They have released four studio albums so far. <a href="https://www.last.fm/music/Salsa+Celtica">Read more on Last.fm</a>', 'pais': ''}, {'artista': 'Los Tigres Del Norte', 'oyentes': '287874', 'reproducciones': '6205860', 'bio_resumen': 'Mexican Norteño Grammy-winning legendary group, best known for (re)starting the "corrido" genre in the late 20th Century, as a milestone of its latest incarnation, known on one side as "narcocorrido" (ballads on smugglers) and on the other, the new brew of socially-committed lyrics that have succeeded in being truly popular.\n\nMembers:\n· Jorge Hernández: director, lead vocals and accordion \n· Hernán Hernández: electric bass, vocals\n· Eduardo Hernández: accordion, saxophone, 6-string bass, vocals <a href="https://www.last.fm/music/Los+Tigres+Del+Norte">Read more on Last.fm</a>', 'pais': 'Mexico'}, {'artista': 'Cubismo', 'oyentes': '13048', 'reproducciones': '83541', 'bio_resumen': 'Cubismo is a group that plays energetic dance music based on afro-Cuban rhythms but in its own unique and recognizable style. Besides salsa and Latin-jazz Cubismo has also been influenced by the elements of jazz, hip-hop, funk and rock music. The band members come from Croatia , Slovenia , Cuba and Ecuador . Cubismo is the leading group for such type of music in Croatia and this part of Europe .\nThe band has so far released 6 CDs, the majority of which has been internationally distributed. <a href="https://www.last.fm/music/Cubismo">Read more on Last.fm</a>', 'pais': ''}, {'artista': 'Rios De Gloria', 'oyentes': '1792', 'reproducciones': '13944', 'bio_resumen': 'Rios De Gloria is a Spanish Pop Dance band consisting of Gloria Gómez and Javier Rios, who was later replaced by Michel Lara.\nThis project released the albums "Rios De Gloria", "Dos" and "Desafiame". <a href="https://www.last.fm/music/Rios+De+Gloria">Read more on Last.fm</a>', 'pais': 'Spain'}, {'artista': 'Jimmy Bosch', 'oyentes': '41465', 'reproducciones': '172809', 'bio_resumen': 'Jimmy Bosch, who was born to parents from Arecibo, Puerto Rico, was raised in Hoboken, NJ, lived in the Bronx, NY for twenty years, played in Salsa bands from the age of 13, and continuously re-invents the music of a culture with roots in many parts of the world. Tropical Music with a New York edge is unlike any musical experience anywhere. Once exposed to the Jimmy Bosch experience, there is no turning back to anything less. This is commonly the <a href="https://www.last.fm/music/Jimmy+Bosch">Read more on Last.fm</a>', 'pais': ''}, {'artista': "Mo' Horizons", 'oyentes': '474062', 'reproducciones': '4698698', 'bio_resumen': 'Mo\' Horizons are the producers, musicians and DJ\'s Ralf Droesemeyer and Mark \'Foh\' Wetzler. Their first album, Come Touch the Sun, which features Mo\'s first two 12"s \'Yes Baby Yes (Sally Said) and Foto Viva, melts together influences ranging from the soulful fifties, sixties & funky seventies straight to the nineties. Integrating modern production techniques and a handful of talented live-musicians and vocalists they create a sound that varies in mood and style but is still homogenous and therefore can easily be identified as Mo\' Horizons. <a href="https://www.last.fm/music/Mo%27+Horizons">Read more on Last.fm</a>', 'pais': ''}, {'artista': 'Obie Bermudez', 'oyentes': '64665', 'reproducciones': '396162', 'bio_resumen': 'Obie Bermúdez es un cantante y compositor puertorriqueño. Nació el 10 de enero de 1980, en la zona cálida y montañosa de Aibonito, (Puerto Rico). De abuelo músico y de padre fundador de una banda de rock, desde los 12 años de edad su familia se traslada a New York (EE.UU.), lugar donde nació el padre de Obie.\n\nFue allí donde empezó su carrera artística. Primeramente cuenta que, para ganarse el pan de cada día, trabajaba en una lavandería <a href="https://www.last.fm/music/+noredirect/Obie+Bermudez">Read more on Last.fm</a>', 'pais': ''}, {'artista': 'Los Tucanes de Tijuana', 'oyentes': '310580', 'reproducciones': '4028010', 'bio_resumen': 'Los Tucanes de Tijuana is a Mexican band founded on 13 April 1987 by Mario Quintero Lara and a group of talented friends in Tijuana, Baja California, Mexico. From humble beginnings, starting their musical career by playing at nightclubs they rose to become the most successful and sought after Norteño band in Mexico, Latin America and the United States. They are by far the global ambassadors of Norteña music and Corrido ballads.\n\n\nLos Tucanes esta formado de cinco mexicanos originarios de Sinaloa México. <a href="https://www.last.fm/music/Los+Tucanes+de+Tijuana">Read more on Last.fm</a>', 'pais': 'Mexico'}, {'artista': 'La Retrocumbia', 'oyentes': '129', 'reproducciones': '1738', 'bio_resumen': 'biografia no encontrada', 'pais': ''}, {'artista': 'Skeewiff', 'oyentes': '123369', 'reproducciones': '1303906', 'bio_resumen': 'UK based DJ, musicians and production duo Alex Rizzo and Elliot ireland whose cheeky humour and dancefloor production skills create a unique sound.\n\nEssentially an electronic breakbeat act, they include elements of jazz and particularly lounge music into their style. They also draw on other styles such as big band and Indian. The result is a contemporary, often instrumental music that is much used by Games, Film and TV producers (FIFA, Adidas etc) and consequently many Skeewiff tracks will be subliminally familiar to a wide audience... <a href="https://www.last.fm/music/Skeewiff">Read more on Last.fm</a>', 'pais': ''}, {'artista': 'Enrique Iglesias', 'oyentes': '2595578', 'reproducciones': '51695841', 'bio_resumen': 'Enrique Miguel Iglesias Preysler (born 8 May 1975) is a Spanish singer and songwriter. He started his recording career in the mid-1990s on the Mexican label Fonovisa and became the bestselling Spanish-language act of the decade. By the turn of the millennium, he made a successful crossover into the mainstream English-language market. He signed a multi-album deal with Universal Music Group for US$68 million with Universal Music Latino to release his Spanish albums and Interscope Records to release English albums. <a href="https://www.last.fm/music/Enrique+Iglesias">Read more on Last.fm</a>', 'pais': 'Mexico'}, {'artista': 'Carlos Ponce', 'oyentes': '27605', 'reproducciones': '148631', 'bio_resumen': 'Carlos Ponce (born September 4, 1972) is a Puerto Rican actor, singer, composer and television personality. Ponce began his acting career by participating in Spanish language soap operas for Televisa and Telemundo. Ponce continued to expand his acting career by participating in various American television series. He did not limit himself solely to a career in television. Ponce, who is also a singer, is also active in the American movie industry as a character actor. <a href="https://www.last.fm/music/Carlos+Ponce">Read more on Last.fm</a>', 'pais': 'United States'}, {'artista': 'Melody', 'oyentes': '290331', 'reproducciones': '4127780', 'bio_resumen': '1) Melodía Ruiz Gutiérrez (born 12 October 1990), best known by her stage name Melody, is a Spanish singer. Melody became famous at the age of 10 with her song "El baile del gorila", one of the biggest summer hits of 2001 in Spain. She has released six albums and numerous singles. She represented Spain at the Eurovision Song Contest 2025 with the song "Esa diva".\n\n2) Gabriella Abreu Severino (born February 4, 2007), known professionally by her stage name Melody, is a Brazilian singer, songwriter, and musician. <a href="https://www.last.fm/music/Melody">Read more on Last.fm</a>', 'pais': 'Brazil'}, {'artista': 'El Cuarteto De Nos', 'oyentes': '255475', 'reproducciones': '17701574', 'bio_resumen': 'El Cuarteto de Nos is an Uruguayan alternative rock band formed in 1984 in Montevideo. The band was originally comprised of the Musso brothers (Roberto and Riki Musso) and Santiago Tavella, who they had met in high school. In 1984 they released their debut album, a split LP with uruguayan candombe musician Alberto Wolf under the Ayuí / Tacuabé label. Leonardo Baroncini was hired to be a guest drummer on the record.\n\nIn March 1987 they released Soy una arveja <a href="https://www.last.fm/music/El+Cuarteto+De+Nos">Read more on Last.fm</a>', 'pais': ''}, {'artista': 'Ana Torroja', 'oyentes': '129214', 'reproducciones': '1289579', 'bio_resumen': 'Ana Torroja is a Spanish vocalist, and was the lead singer of the million-selling trio Mecano. Daughter of a noted engineer, she was born in Madrid on December 28, 1959, and met José María Cano while studying economics at university. The two became good friends, and José María soon introduced Ana to his younger brother Nacho. Upon hearing Ana singing along to his brother\'s compositions on the guitar, Nacho suggested that the three should form a band, and in 1981 Mecano was born. <a href="https://www.last.fm/music/Ana+Torroja">Read more on Last.fm</a>', 'pais': 'Spain'}, {'artista': 'Willie Bobo', 'oyentes': '223148', 'reproducciones': '1216022', 'bio_resumen': 'Willie Bobo was the stage name of William Correa (February 28, 1934 – September 15, 1983),[1] a Latin and jazz percussionist of Puerto Rican ancestry.\nHis youngest son, Eric Bobo (Eric Correa), is a percussionist with crew Cypress Hill. He also performed on the Beastie Boys\' 1994 album Ill Communication, as well as doing the 1994 Lollapalooza tour with the group\n\nHis grandson William Valen Correa, son of Bobo\'s first son William Gill Correa, is Co-Founder of the music-based non-profit organization HNDP Los Angeles. <a href="https://www.last.fm/music/Willie+Bobo">Read more on Last.fm</a>', 'pais': ''}, {'artista': 'Malú', 'oyentes': '78751', 'reproducciones': '1322893', 'bio_resumen': 'There are at least 4 singers named Malú or Malu.\n\n1.  María \'Malú\' Lucía Sánchez (born 15 March, 1982) is a singer from Madrid, Spain. Malú was discovered at the age of 15 when she was singing at a family party. She began the recording of her first album Aprendiz in January 1998. Malú is the niece of the flamenco singer-songwriter Paco de Lucía.\n\n2. Malu is a pop singer from Amsterdam, The Netherlands. There is no accent on the letter \'u\', but scrobbles of her songs end up here due to Last. <a href="https://www.last.fm/music/+noredirect/Mal%C3%BA">Read more on Last.fm</a>', 'pais': ''}, {'artista': 'Luis Alberto Posada', 'oyentes': '8402', 'reproducciones': '109185', 'bio_resumen': 'biografia no encontrada', 'pais': ''}, {'artista': 'José José', 'oyentes': '314289', 'reproducciones': '14267933', 'bio_resumen': 'José José (José Rómulo Sosa Ortiz, Mexico City, Mexico, February 17, 1948 — September 28, 2019)  was a Mexican singer, musician and occasional actor. \n\nBorn into a family of musicians and raised in Mexico City, José began his musical career in his early teens playing guitar and singing in serenades. He later joined a jazz and bossa nova trio where he sang and played bass and double bass. José found success as a solo artist in the early 1970s. <a href="https://www.last.fm/music/+noredirect/Jos%C3%A9+Jos%C3%A9">Read more on Last.fm</a>', 'pais': 'Mexico'}, {'artista': 'Jon Secada', 'oyentes': '253532', 'reproducciones': '1783117', 'bio_resumen': 'Juan Francisco Secada (born October 4, 1962 in Havana, Cuba)  better known as Jon Secada is an Afro-Cuban singer and songwriter. Secada was born in Havana, Cuba, and raised in Hialeah, Florida. He has won two Grammy Awards and sold 20 million albums since his English-language debut album in 1992, made famous for his song Just Another Day. His music fuses funk, soul, pop and Latin percussion. Secada also has appeared as a songwriter for Gloria Estefan, Jennifer Lopez, Ricky Martin, Mandy Moore and other performers. <a href="https://www.last.fm/music/Jon+Secada">Read more on Last.fm</a>', 'pais': ''}, {'artista': 'Los Legendarios', 'oyentes': '104629', 'reproducciones': '844861', 'bio_resumen': 'biografia no encontrada', 'pais': ''}, {'artista': 'paco pineda y su grupo tex mex', 'oyentes': '122', 'reproducciones': '1306', 'bio_resumen': 'biografia no encontrada', 'pais': ''}, {'artista': 'Lemon', 'oyentes': '137243', 'reproducciones': '2473743', 'bio_resumen': 'There are various groups with the name Lemon.\n\n1) Who are they? Polish band. Lemon is a brainchild of Igor Herbut. He founded the band right after he’d gotten to know that he had been accepted as the contestant of Must Be the Music talent show. He partook in the auditions with his cousin Adam after the night they spent at a wedding party as vocal performers. That’s what Igor has to say about this unusual experience: When we got to know we could <a href="https://www.last.fm/music/Lemon">Read more on Last.fm</a>', 'pais': ''}, {'artista': 'Yuri Buenaventura', 'oyentes': '58273', 'reproducciones': '311023', 'bio_resumen': 'Yuri Buenaventura - Colombian salsa singer.\n\nOne of Colombia\'s most talented salsa singers that emerge from the salsa circles of Cali. Yuri currently resides in France. \n\n With “Vagabundo”, Colombian singer Yuri Buenaventura reveals himself as the “brightest new star from South America”. From the irresistibly swingy ‘Guajiro del Monte’, with its expansive and golden big-band dance sound to the pared-back and poignant ‘Donde Estas?’ – it’s always clear that we’re in completely assured hands. <a href="https://www.last.fm/music/Yuri+Buenaventura">Read more on Last.fm</a>', 'pais': 'Colombia'}, {'artista': 'Jarabe de Palo', 'oyentes': '563796', 'reproducciones': '9382639', 'bio_resumen': 'Jarabe de Palo (literally "Wooden Stick Syrup" or, after the Spanish expression "dar un jarabe de palo", i.e. a "hell of a beating"), was a Spanish rock band founded in 1996. The group was led by singer, songwriter, and guitarist Pau Donés, whose death in 2020 caused the band to break up.\n\nPau Donés, born and raised in Barcelona, worked for various groups before being able to take on his current project, Jarabe de Palo. He began at age 15 with his brother Marc, with whom he formed a group known as J. <a href="https://www.last.fm/music/Jarabe+de+Palo">Read more on Last.fm</a>', 'pais': 'Spain'}, {'artista': 'Gloria Estefan', 'oyentes': '752353', 'reproducciones': '7645626', 'bio_resumen': 'Gloria Estefan (born Gloria María Fajardo, September 1, 1957, in Havana, Cuba) is a seven-time Grammy Award-winning singer-songwriter, actress and social activist. Known as the "Queen of Latin Pop", she in the top 100 best-selling

In [ ]:
df_artistas_latin_pop_LastFm = pd.DataFrame(lista_artistas)

In [ ]:
df_artistas_latin_pop_LastFm

,artista,oyentes,reproducciones,bio_resumen,pais
0,Joaquín Sabina,231870,7438578,"Joaquín Ramón Martínez Sabina (Úbeda, Jaén, Sp...",
1,Los Incomparables De Tijuana,13277,88900,A Norteño Group Formed in Tijuana México in 19...,
2,LUISITO MUÑOZ,4458,40482,biografia no encontrada,
3,Julieta Venegas,771261,19578941,"Julieta Venegas (born November 24, 1970) is a ...",Mexico
4,Beto Quintanilla,31943,476522,"Norberto ""Beto"" Quintanilla Iracheta (May 23, ...",Mexico
...,...,...,...,...,...
149,Lorena,17584,189660,There are more than one female artist named LO...,United States
150,Patricia Manterola,19916,124238,"Singer, actress and host, Patricia Manterola i...",Mexico
151,Grupo Exterminador,62441,504018,Hablar del GRUPO EXTERMINADOR es hablar de ori...,
152,Sabroso,11549,119500,biografia no encontrada,
153,Los Cachorros De Juan Villarreal,11147,95971,biografia no encontrada,

In [ ]:
df_artistas_latin_pop_LastFm.to_csv("artista_latin_pop.csv", index=False, encoding="utf-8")

In [ ]:
### finalmente obtenermos otro df_cvs con los datos necesarios para realizar nuestras consultas en my SQL