In [1]:
import json
import pandas as pd
import requests

In [ ]:
cliente = "xxxxx"

nombre_artista = ['Five For Fighting', 'The Smashing Pumpkins', 'The Beatles', 'Deftones'] 
#prueba con artistas aleatorios

url_api = "http://ws.audioscrobbler.com/2.0/"

lista_artistas = []

def llamar_lastfm_api(method, artist_name, cliente):
        params = {'method': method,'artist': artist_name,'api_key': cliente,'format': 'json'}
        response = requests.get(url_api, params=params)
        if response.status_code == 200:
            return response.json()
        else:
            print(f"Error {response.status_code}: No se pudo obtener la información para el método {method}")
            return

print(f"Obteniendo detalles de: {nombre_artista}")

Obteniendo detalles de: ['Five For Fighting', 'The Smashing Pumpkins', 'The Beatles', 'Deftones']

In [3]:
artistas_a_consultar = ["Gigi D'Agostino", "Pink Floyd", "Led Zeppelin", "Queen", "The Beatles"] 
#prueba con artistas aleatorios

lista_artistas = []

for nombre_artista in artistas_a_consultar:
    print(f"--- Consultando: {nombre_artista} ---")
    datos_artista = llamar_lastfm_api('artist.getinfo', nombre_artista, cliente)

    if datos_artista and 'artist' in datos_artista:
        artista_data = datos_artista['artist']
        oyentes = artista_data.get('stats', {}).get('listeners', 'arista no encontrado')
        reproducciones = artista_data.get('stats', {}).get('playcount', 'N/D')
        bio_content = artista_data.get('bio', {}).get('content', '')

        if not bio_content or bio_content.strip() == "":
            bio_resumen = 'biografia no encontrada'

        else:
            bio_resumen = artista_data.get('bio', {}).get('summary')

        lista_artistas_dict = {'artista': artista_data.get('name', nombre_artista),'oyentes': oyentes, 'reproducciones': reproducciones, 'bio_resumen': bio_resumen}
        lista_artistas.append(lista_artistas_dict)
        print(f"Datos de {nombre_artista} procesados y guardados.")

    else:
        print(f"No se pudo obtener información de {nombre_artista}")

--- Consultando: Gigi D'Agostino ---
Datos de Gigi D'Agostino procesados y guardados.
--- Consultando: Pink Floyd ---
Datos de Pink Floyd procesados y guardados.
--- Consultando: Led Zeppelin ---
Datos de Led Zeppelin procesados y guardados.
--- Consultando: Queen ---
Datos de Queen procesados y guardados.
--- Consultando: The Beatles ---
Datos de The Beatles procesados y guardados.

In [4]:
lista_artistas

[{'artista': "Gigi D'Agostino",
  'oyentes': '975118',
  'reproducciones': '14317355',
  'bio_resumen': 'Luigino Celestino di Agostino (born 17 December 1967), known professionally as Gigi D\'Agostino, is an Italian DJ and music producer. He began his career in 1986 as a DJ specialising in Italo disco. His most successful releases include "Bla Bla Bla," "Another Way," his cover of Nik Kershaw\'s "The Riddle," "La Passion," "Super," and "L\'Amour Toujours," all released between 1999 and 2000. The melody of "L\'Amour Toujours" was later used in the 2018 remix and mashup "In My Mind." <a href="https://www.last.fm/music/Gigi+D%27Agostino">Read more on Last.fm</a>'},
 {'artista': 'Pink Floyd',
  'oyentes': '5351208',
  'reproducciones': '584234256',
  'bio_resumen': 'Pink Floyd was an English rock band formed in London in 1965. Gaining an early following as one of the first British psychedelic groups, they were distinguished by their extended compositions, sonic experimentation, philosophical lyrics and elaborate live shows. They became a leading band of the progressive rock genre, cited by some as the greatest progressive rock band of all time.\n\nPink Floyd were founded in 1965 by Syd Barrett (guitar, lead vocals) <a href="https://www.last.fm/music/Pink+Floyd">Read more on Last.fm</a>'},
 {'artista': 'Led Zeppelin',
  'oyentes': '4801073',
  'reproducciones': '330860092',
  'bio_resumen': 'Led Zeppelin were a hard rock band formed in London in 1968. The group comprised vocalist Robert Plant, guitarist Jimmy Page, bassist and keyboardist John Paul Jones, and drummer John Bonham. With a heavy, guitar-driven sound, they are cited as one of the progenitors of hard rock and heavy metal, although their style drew from a variety of influences, including blues and folk music. Led Zeppelin have been credited as significantly impacting the nature of the music industry <a href="https://www.last.fm/music/Led+Zeppelin">Read more on Last.fm</a>'},
 {'artista': 'Queen',
  'oyentes': '6992639',
  'reproducciones': '407038982',
  'bio_resumen': 'Queen are a British rock band formed in London in 1970 by Freddie Mercury (lead vocals, piano), Brian May (guitar, vocals), and Roger Taylor (drums, vocals), later joined by John Deacon (bass). Their earliest works were influenced by progressive rock, hard rock, and heavy metal, but the band gradually ventured into more conventional and radio-friendly styles by incorporating elements of arena rock and pop rock.\n\nBefore forming Queen, May and Taylor had played together in the band Smile. <a href="https://www.last.fm/music/Queen">Read more on Last.fm</a>'},
 {'artista': 'The Beatles',
  'oyentes': '6300464',
  'reproducciones': '1047875551',
  'bio_resumen': 'The Beatles was an English rock band formed in Liverpool, Lancashire in 1960. With the line-up comprising John Lennon, Paul McCartney,  George Harrison, and Ringo Starr, they are regarded as the most popular and influential band of all time. The group were integral to the development of 1960s counterculture and popular music\'s recognition as an art form. Rooted in skiffle, beat and 1950s rock and roll, their sound incorporated elements of classical <a href="https://www.last.fm/music/The+Beatles">Read more on Last.fm</a>'}]

In [ ]:
# Código funciona. Ahora, pasamos nuestra lista de artistas de spotify a una lista de artistas únicos (no repetidos):

In [5]:
df = pd.read_csv("df_electronica.csv")

In [6]:
df

,Artista,Género,Tipo,Nombre,Año,ID
0,Gigi D'Agostino,electronic,track,L'Amour Toujours (Tanzen Vision RMX),2000,0Cjl6YCM4JQSgdg3xaFPxk
1,A Touch Of Class,electronic,track,My Heart Beats Like A Drum (Dam Dam Dam) - Rad...,2000,0hRFDhaHRJt6cz69n78G3f
2,Morcheeba,electronic,track,Rome Wasn't Built in a Day,2000,6lsumzVFKP9SnfKcuGwqVp
3,Air,electronic,track,Highschool Lover,2000,6JBDPZ0DOmc5mBJprphQc8
4,Vengaboys,electronic,track,Kiss (When The Sun Don't Shine),2000,0CZWUolHfpM91zjjH6sJBN
...,...,...,...,...,...,...
745,DJ KRUSH,electronic,track,Beyond Raging Waves,2004,0vsgbzsEf6AkJoUxxrO1fg
746,ATB,electronic,track,Collides with Beauty,2004,1qFSEJG7buRP2sn6fEaM7N
747,Boom Bip,electronic,track,Last Walk Around Mirror Lake - Boards of Canad...,2004,4agMFZlZVMPvXcpLewP2tS
748,Nathan Fake,electronic,track,The Sky Was Pink - Holden Remix,2004,2oeEq7M17OE5rqcYYYHZet
749,Scooter,electronic,track,One (Always Hardcore),2004,04frI4TPBnmvaYXHeqELQL

In [7]:
df['Artista']

0       Gigi D'Agostino
1      A Touch Of Class
2             Morcheeba
3                   Air
4             Vengaboys
             ...
745            DJ KRUSH
746                 ATB
747            Boom Bip
748         Nathan Fake
749             Scooter
Name: Artista, Length: 750, dtype: object

In [8]:
artista = df['Artista']

In [9]:
artistas_unicos = set(artista)

In [10]:
artistas_unicos

{'2 Eivissa',
 '666',
 '9 Lazy 9',
 'A Touch Of Class',
 'ATB',
 'AYA',
 'Ai-Ai delas Alas',
 'Aim',
 'Air',
 'Alcazar',
 'Alex C.',
 'Alice Deejay',
 'Alison Crockett',
 'Amon Tobin',
 'Amp Fiddler',
 'Andreid',
 'Andrew E.',
 'Ann Lee',
 'Aphex Twin',
 'Aqua',
 'Aquarious',
 'Archive',
 'Bambee',
 'Barcode Brothers',
 'Bayani Agbayani',
 "Beauty's Confusion",
 'Benny Benassi',
 'Beth Gibbons',
 'Beverlei Brown',
 'Big Muff',
 'Björk',
 'Blockhead',
 'Blue Foundation',
 'Blue States',
 'Blur',
 'Boards of Canada',
 'Bob Baldwin',
 "Bomfunk MC's",
 'Bonobo',
 'Boom Bip',
 'Boozoo Bajou',
 'Bowery Electric',
 'C21',
 'Calibre',
 'Caramell',
 'Casino Versus Japan',
 'Catrien',
 'Celldweller',
 'Charanjit Singh',
 'Chateau Flight',
 'Clara Hill',
 'Clazziquai',
 'Club des Belugas',
 'Clubringer',
 'Conjure One',
 "D'Sound",
 'DJ Aligator',
 'DJ BoBo',
 'DJ Cam',
 'DJ Encore',
 'DJ KRUSH',
 'DJ Lhasa',
 'DJ Marky',
 'DJ Nu-Mark',
 'DJ Sammy',
 'DJ Satomi',
 'DJ Shadow',
 'DJ Toxic',
 'DJ Volume',
 'DJs@Work',
 'DVS1',
 'Da Hool',
 'Daddy DJ',
 'Daft Punk',
 'Danzel',
 'Darude',
 'De-Phazz',
 'Death In Vegas',
 'Delerium',
 'Devics',
 'Divinorum',
 'Dizzee Rascal',
 'Doctor Rockit',
 'Dzihan & Kamien',
 'E-Type',
 'Eddy Wata',
 'Eiffel 65',
 'Elsa',
 'Enigma',
 'Eric Prydz',
 'Erika',
 'Erykah Badu',
 'Etro Anime',
 'FC Kahuna',
 'Faithless',
 'Fantasy Project feat. NDA',
 'Fatboy Slim',
 'Fila Brazillia',
 'Fingathing',
 'Fischerspooner',
 'Floorfilla',
 'Flunk',
 'Four Tet',
 'French Affair',
 'Frou Frou',
 'Funki Porcini',
 'GAS',
 'Gabin',
 'Gabry Ponte',
 'Gaya Band',
 'Georg Levin',
 'Gerardo Frisina',
 "Gigi D'Agostino",
 'Gladys and the Boxers',
 'Goldfrapp',
 'Gorillaz',
 'Gotan Project',
 'Greyboy',
 'Groove Armada',
 'Groove Collective',
 'Groove Coverage',
 'Günther',
 'Haddaway',
 'Handsome Boy Modeling School',
 'Harry Corpuz',
 'Herbert',
 'Highland',
 'Hird',
 'Hooverphonic',
 'Hybrid',
 'Ian Brown',
 'Idris Muhammad',
 'In-Grid',
 'Incognito',
 'Infernal',
 'Infinity',
 'J-Walk',
 'James',
 'Jamiroquai',
 'Jan Jelinek',
 'Jan Wayne',
 'Jazzamor',
 'Jazzanova',
 'Jazztronik',
 'Joachim Garraud',
 'John The Whistler',
 'Jolina Magdangal',
 'Jon Kennedy',
 'Kate Ryan',
 'Kim Lukas',
 'Klubbhoppers',
 'Koop',
 'Kraftwerk',
 'Kylie Minogue',
 'Kyoto Jazz Massive',
 'LFO',
 'LTJ Bukem',
 'La Bouche',
 'Labelle',
 'Lamb',
 'Lasgo',
 'Lemon Jelly',
 'Lewis Taylor',
 'Llorca',
 'Lollipop',
 'Lou Bega',
 'Louie Austen',
 'Mandalay',
 'Mariah Carey',
 'Marilyn Manson',
 'Mark Rae',
 'Martina Topley-Bird',
 'Masculados',
 'Massive Attack',
 'Micatone',
 'Missing Heart',
 "Mo' Horizons",
 'Moby',
 'Mocean Worker',
 'Modjo',
 'Mondo Grosso',
 'Morcheeba',
 'Morrissey',
 'Nathan Fake',
 'Nathaniel Merriweather',
 'New Order',
 'Nicola Conte',
 'Nightmares On Wax',
 'Nils Petter Molvær',
 'Nina Simone',
 'Nine Inch Nails',
 'Novaspace',
 'O-Zone',
 'Oasis',
 'Ocean Colour Scene',
 'Ochre',
 'Omar',
 'Opto',
 'Orbital',
 'Orgy',
 'Oscar G & Ralph Falcon',
 'Paffendorf',
 'Paul Kalkbrenner',
 'Paul Oakenfold',
 'Paul van Dyk',
 'Pauline London',
 'Peaches',
 'Pet Shop Boys',
 'Plaid',
 'Povo',
 'Praise Cats',
 'Prefuse 73',
 'Prezioso',
 'Quantic',
 'RJD2',
 'Radioactive Man',
 'Reflekt',
 'Richard Hall',
 'Rimini Project',
 'Rollergirl',
 'Roni Size',
 'Ronny Jordan',
 'Rouge Rouge',
 'Roxie',
 'Röyksopp',
 'S-Tone Inc',
 'SMiLE.dk',
 'Safri Duo',
 'Saint Privat',
 'Sandee Chan',
 'Sasha',
 'Scatman John',
 'Schmoov!',
 'Scooter',
 'ScubaZ',
 'Seek',
 'Sexbomb Girls',
 'Shakedown',
 'Shazz',
 'Skalpel',
 'Soel',
 'Solid Base',
 'Solsonics',
 'Soulsearcher',
 'Soulstice',
 'Special D.',
 'Squarepusher',
 'St Germain',
 'Static-X',
 'Summer Love',
 'Sweet Trip',
 'TM Juke',
 'Takkyu Ishino',
 'Telefon Tel Aviv',
 'The Chemical Brothers',
 'The Cinematic Orchestra',
 'The Crystal Method',
 'The Dining Rooms',
 'The Karminsky Experience Inc.',
 'The Mighty Bop',
 'The Prodigy',
 'The RH Factor',
 'The Underdog Project',
 'Thievery Corporation',
 'Tiësto',
 'Tom & Joy',
 'Tortured Soul',
 'Tosca',
 'Twinset',
 'Two Lone Swordsmen',
 'Télépopmusik',
 'UNKLE',
 'Underworld',
 'Urbs & Cutex',
 'Us3',
 'Variety Lab',
 'Vengaboys',
 'Vhen Bautista',
 'Vhong Navarro',
 'Visage',
 'Wagon Christ',
 'Wax Poetic',
 'Way Out West',
 'Yonderboi',
 'Zero 7',
 '[re:jazz]',
 'alva noto',
 'edIT',
 'm.o.v.e',
 'noonday underground',
 'paris match',
 'sora',
 'weirdo girl'}

In [11]:
len(artistas_unicos)

293

In [13]:
df_electronica_3 = pd.DataFrame(artistas_unicos)

df_electronica_3

                          0
0    Oscar G & Ralph Falcon
1                    Enigma
2                 Jan Wayne
3                   TM Juke
4                       AYA
..                      ...
288           Dizzee Rascal
289            Scatman John
290        Telefon Tel Aviv
291            Paul van Dyk
292          Marilyn Manson

[293 rows x 1 columns]

In [25]:
df_electronica_3.to_csv('artistas_electronica.csv', index=False, encoding="utf-8")

In [14]:
artistas_a_consultar = artistas_unicos #comprobamos que funciona
lista_artistas = []
for nombre_artista in artistas_a_consultar:
    
    datos_artista = llamar_lastfm_api('artist.getinfo', nombre_artista, cliente)
    if datos_artista and 'artist' in datos_artista:
        artista_data = datos_artista['artist']
        oyentes = artista_data.get('stats', {}).get('listeners', 'arista no encontrado')
        reproducciones = artista_data.get('stats', {}).get('playcount', 'N/D')
        bio_content = artista_data.get('bio', {}).get('content', '')
        if not bio_content or bio_content.strip() == "":
            bio_resumen = 'biografia no encontrada'
        else:
            bio_resumen = artista_data.get('bio', {}).get('summary')
        lista_artistas_dict = {'artista': artista_data.get('name', nombre_artista),'oyentes': oyentes, 'reproducciones': reproducciones, 'bio_resumen': bio_resumen}
        lista_artistas.append(lista_artistas_dict)
       
    else:
        print(f"No se pudo obtener información de {nombre_artista}")

In [15]:
# --- 1. DICCIONARIO BASE (PAÍS: GENTILICIO) ---
# Usamos el diccionario que generamos previamente:
PAIS_A_GENTILICIO = {
    "Afghanistan": "Afghan",
    "Albania": "Albanian",
    "Algeria": "Algerian",
    "Argentina": "Argentinian",
    "Australia": "Australian",
    "Austria": "Austrian",
    "Belgium": "Belgian",
    "Bolivia": "Bolivian",
    "Brazil": "Brazilian",
    "Canada": "Canadian",
    "Chile": "Chilean",
    "China": "Chinese",
    "Colombia": "Colombian",
    "Costa Rica": "Costa Rican",
    "Cuba": "Cuban",
    "Denmark": "Dane",
    "Egypt": "Egyptian",
    "France": "French",
    "Germany": "German",
    "Greece": "Greek",
    "India": "Indian",
    "Indonesia": "Indonesian",
    "Ireland": "Irish",
    "Italy": "Italian",
    "Jamaica": "Jamaican",
    "Japan": "Japanese",
    "Mexico": "Mexican",
    "Netherlands": "Dutch",
    "New Zealand": "New Zealander",
    "Nigeria": "Nigerian",
    "Norway": "Norwegian",
    "Peru": "Peruvian",
    "Poland": "Pole",
    "Portugal": "Portuguese",
    "Russia": "Russian",
    "South Korea": "South Korean",
    "Spain": "Spaniard",
    "Sweden": "Swede",
    "Turkey": "Turk",
    "Ukraine": "Ukrainian",
    "United Kingdom": "Briton",
    "United States": "American",
    "United States_adj": "American",
    "United Kingdom_adj": "British",
    "France_adj": "French",
    "Germany_adj": "German",
    "Spain_adj": "Spanish"}
# --- 2. DICCIONARIO INVERTIDO PARA BÚSQUEDA EFICIENTE ---
# Clave: Gentilicio (lo que busco en la bio), Valor: País
GENTILICIO_A_PAIS = {gentilicio.lower(): pais.replace('_adj', '')
    for pais, gentilicio in PAIS_A_GENTILICIO.items()}

In [16]:
def extraer_pais_de_biografia(bio_resumen, gentilicio_a_pais_map):
    bio_normalizada = bio_resumen.lower()
    for gentilicio, pais in gentilicio_a_pais_map.items():
        # Usamos ' ' + gentilicio + ' ' para buscar la palabra completa y evitar coincidencias parciales
        if f' {gentilicio} ' in bio_normalizada or bio_normalizada.startswith(f'{gentilicio} '):
            return pais
        # Caso especial para "is an American rock band" (no tiene espacio antes)
        if bio_normalizada.endswith(gentilicio):
             return pais
    return ' '

In [17]:
for artista_data in lista_artistas:
    bio = artista_data['bio_resumen']
    pais_encontrado = extraer_pais_de_biografia(bio, GENTILICIO_A_PAIS)
    artista_data['pais'] = pais_encontrado #aqui agregamos la clave pais en nuestro diccionario

In [18]:
lista_artistas

[{'artista': 'Oscar G & Ralph Falcon',
  'oyentes': '5757',
  'reproducciones': '24033',
  'bio_resumen': 'biografia no encontrada',
  'pais': ' '},
 {'artista': 'Enigma',
  'oyentes': '1378807',
  'reproducciones': '51184245',
  'bio_resumen': 'There is more than one artist with the name Enigma:\n\n1)  Enigma is a German electronic musical project founded by Michael Cretu (Romanian musician), David Fairstein and Frank Peterson in 1990. Cretu, who based his recording studio A.R.T. Studios in Ibiza, Spain in the early 1990s is both the composer and the producer of the project. His former wife Sandra often provided vocals on Enigma tracks. Jens Gad co-produced and played guitar on three of the Enigma albums.  <a href="https://www.last.fm/music/Enigma">Read more on Last.fm</a>',
  'pais': 'Germany'},
 {'artista': 'Jan Wayne',
  'oyentes': '185108',
  'reproducciones': '1274461',
  'bio_resumen': 'Jan Wayne (German pronunciation: [ˌjan ˈvɛɪn] (born Jan Christiansen, January 1974, Husum, Schleswig-Holstein) is a German electronic dance music DJ and producer.\n\nDiscography\nAlbums\n2002 - Back Again\n2003 - Gonna Move Ya\n\nSingles\n2001 - "Total Eclipse of the Heart" - UK #28 (in 2003)\n2002 - "Because the Night" - UK #14\n2002 - "Only You" (Cover of Yazoo\'s song)\n2002 - "More Than a Feeling"\n2003 - "Love Is a Soldier"\n2003 - "1,2,3 (Keep the Spirit Alive)" <a href="https://www.last.fm/music/Jan+Wayne">Read more on Last.fm</a>',
  'pais': 'Germany'},
 {'artista': 'TM Juke',
  'oyentes': '292266',
  'reproducciones': '2736136',
  'bio_resumen': 'TM Juke, real name Al Cowan, aka Artist Formerly Known As Al Stylus and The Man Juke, is a producer from Brighton, UK, signed to Tru Thoughts. Merging his training in classical and jazz guitar with digitised sampling and first class guest vocalists, TM Juke\'s music draws on funk, soul, hip-hop and jazz influences.\n\nTM Juke produced Alice Russell\'s second solo album, My favourite Letters.\nHe has also released two solo albums on Tru Thoughts: Maps From the Wilderness and in 2006 Forward a more dancefloor based affair. <a href="https://www.last.fm/music/TM+Juke">Read more on Last.fm</a>',
  'pais': ' '},
 {'artista': 'Aya',
  'oyentes': '164581',
  'reproducciones': '1761488',
  'bio_resumen': 'There are multiple artists that have recorded under the name Aya.\n\n1. Aya (full name: Aya Sinclair) is a British electronic artist who until late 2019 recorded as Loft. She runs the label called YCO alongside BFTT. \n\n2. Aya is the stage name of Lysa Aya Trenier who released the album Strange Flower in 2004.\n\n3. AYA is a British minimal pop sister duo produced by Andrew Barlow of Lamb. They released five singles in 2017 and 2018, one of which was Heal Me Now. <a href="https://www.last.fm/music/Aya">Read more on Last.fm</a>',
  'pais': 'United Kingdom'},
 {'artista': 'Ian Brown',
  'oyentes': '600348',
  'reproducciones': '10613854',
  'bio_resumen': 'Ian Brown (born February 20th 1963 in Warrington, England) was the lead singer in former British band The Stone Roses and following their split in 1996 has gone on to have a successful solo career releasing a total of six studio albums, with one greatest hits compilation, and remixes disc. He is considered to be an influential artist with followers such as Oasis, The Verve, Blur, Kasabian, Arctic Monkeys and many more. He has had twelve UK top 40 singles and has sold over 9 million albums as a solo artist. <a href="https://www.last.fm/music/Ian+Brown">Read more on Last.fm</a>',
  'pais': 'United Kingdom'},
 {'artista': 'Labelle',
  'oyentes': '265715',
  'reproducciones': '1175389',
  'bio_resumen': 'LaBelle is an American R&B/soul group from Philadelphia, Pennsylvania, USA, who successfully melded dance music with funk and glam rock. Mostly active in the 60s and 70s disband but reformed in 2005. Their most recognised song is "Lady Marmalade". The group was led by Patti LaBelle, who later had a successful solo career. Nona Hendryx, Sarah Dash and Cindy Birdsong rounded out the group, with Hendryx especially notable as a prolific songwriter.\n\nIn 1961 <a href="https://www.last.fm/music/Labelle">Read more on Last.fm</a>',
  'pais': 'United States'},
 {'artista': 'DJ Krush',
  'oyentes': '683620',
  'reproducciones': '15231978',
  'bio_resumen': 'DJ Krush (Hideaki Ishi) was born in 1962 in Tokyo. Gifted producer & DJ with a superb sense in mixing and composing his sound who\'s been greatly received in the international club scene. At an early age, Ishii dropped out of school, and joined a local gang, and a few years later, Yakuza. It was the movie "Wild Style" that got him into hip hop in the early 80\'s, and in 1987, he formed Krush Posse which made numerous appearances in various media as the best hip hop act in Japan. <a href="https://www.last.fm/music/DJ+Krush">Read more on Last.fm</a>',
  'pais': ' '},
 {'artista': 'Gas',
  'oyentes': '246741',
  'reproducciones': '6982349',
  'bio_resumen': 'Several artists have released recordings under the name of Gas: two electronic music composers, Wolfgang Voigt and Mat Jarvis, furthermore a Japanese hardcore band, a rock band from Germany, and lastly an industrial band from Sweden.\n\n1) GAS is the project of Wolfgang Voigt of Kompakt Records, Cologne, who created hypnotic, bass-driven ambient/minimal techno on the German label Mille Plateaux.  Says Voigt of his music:  \'(This is) music without beginning and without end <a href="https://www.last.fm/music/Gas">Read more on Last.fm</a>',
  'pais': 'Germany'},
 {'artista': 'Povo',
  'oyentes': '71248',
  'reproducciones': '667504',
  'bio_resumen': 'Povo (meaning "people" in Portuguese) is a Danish jazz duo consisting of Anders Andreasen and Lars Vissing. Anders and Lars bring together the best of both worlds with Anders\' experience as a club promoter and DJ and Lars\' musical talent. Both are jazz afficionados with unique ear for extraordinary music. Their debut album "We Are Povo" features their successful take on the classic "Uam Uam". The follow-up album "The Yellow of the Sun in You", featuring for example legendary Andy Bey <a href="https://www.last.fm/music/Povo">Read more on Last.fm</a>',
  'pais': ' '},
 {'artista': 'Bonobo',
  'oyentes': '2036857',
  'reproducciones': '110488731',
  'bio_resumen': '\nSimon Green, known by his stage name Bonobo, is a British musician, producer and DJ based in Los Angeles.\n\nBonobo\'s first album - 2000\'s Animal Magic - was released via Tru Thoughts before being picked up by Ninja Tune. It announced him as a serious talent; able to bring a musician\'s edge to electronic music, with all the freedom that skill allowed. His subsequent albums for Ninja, Dial \'M\' for Monkey and Days to Come, developed his sensibility, won him fans across the globe <a href="https://www.last.fm/music/Bonobo">Read more on Last.fm</a>',
  'pais': 'United Kingdom'},
 {'artista': 'Nine Inch Nails',
  'oyentes': '3477786',
  'reproducciones': '305442806',
  'bio_resumen': 'Nine Inch Nails, commonly abbreviated as NIN (stylized as NIИ), is an American industrial rock band formed in 1988 in Cleveland, Ohio. Singer, songwriter, multi-instrumentalist, and producer Trent Reznor was the only permanent member of the band until the official addition of English musician Atticus Ross in 2016. \n\nReznor chose the name "Nine Inch Nails" because it "abbreviated easily" rather than for "any literal meaning". Other rumored explanations have circulated <a href="https://www.last.fm/music/Nine+Inch+Nails">Read more on Last.fm</a>',
  'pais': 'United States'},
 {'artista': 'Gabry Ponte',
  'oyentes': '440133',
  'reproducciones': '5751697',
  'bio_resumen': 'Gabriele Ponte (or Gabry Ponte) (b. April 20th, 1973) is an Italian DJ best known for his membership in the Italian dance group Eiffel 65. Ponte has been involved with the Bliss Team, DJ Gundam, and Sangwara. With Eiffel 65\'s rise to fame in the late 1990\'s, his celebrity (or semi-celebrity) status was established, and he later went on to produce the Italian hits "Geordie" (A cover of Fabrizio de André`s song by the same name) and "La Danza delle Streghe". <a href="https://www.last.fm/music/Gabry+Ponte">Read more on Last.fm</a>',
  'pais': 'Italy'},
 {'artista': 'Nicola Conte',
  'oyentes': '439657',
  'reproducciones': '5345431',
  'bio_resumen': 'Nicola Conte is a DJ and producer from Bari, Italy known for introducing an innovative style of acid jazz that incorporates bossa nova themes, melodies drawn from Italian film scores of the 1960\'s, easy listening themes, and ethnic Indian music.\n\nConte, a classically-trained musician, is mastermind of a collective of acid jazz revivalists, "The Fez collective" (and originally a member of the group Fez Combo), based in the Italian town of Bari, and the Schema label, their record label for promoting their distinctly Italian approach to acid jazz. <a href="https://www.last.fm/music/Nicola+Conte">Read more on Last.fm</a>',
  'pais': 'India'},
 {'artista': 'm.o.v.e',
  'oyentes': '70568',
  'reproducciones': '2138789',
  'bio_resumen': 'm.o.v.e (formerly known as move) was a 3-member Japanese musical group. The group consists of yuri (益田祐里, Masuda Yuri, vocalist), motsu (瀬川素公, Segawa Mototaka, rapper) and t-kimura (木村貴志, Kimura Takashi, producer).\n\nIn 1996, after the break up of t-kimura\'s previous project Favorite Blue, he formed the band move and, by 1997, they released their first single ROCK IT DOWN. They however truly achieved fame when their followup single, around the world, was used as the opening theme for the anime Initial D (頭文字D). <a href="https://www.last.fm/music/m.o.v.e">Read more on Last.fm</a>',
  'pais': 'Japan'},
 {'artista': 'Saint Privat',
  'oyentes': '151373',
  'reproducciones': '2273270',
  'bio_resumen': 'Saint Privat is a project begun by Austrian electronic musician Klaus Waldeck (best known as Waldeck), in 2004. Waldeck combined his sounds with the voice of lead singer Valérie Sajdik (aka Valerie), who was born near Vienna, then grew-up in Moscow and France, speaking German, French, English and Russian. The name of the project stems from the commune of Saint-Privat, in southern France, where Valérie lives.\n\nsaint privat ist ein Wiener Band-Projekt des DJs und Produzenten Klaus Waldeck. <a href="https://www.last.fm/music/Saint+Privat">Read more on Last.fm</a>',
  'pais': 'Austria'},
 {'artista': 'Etro Anime',
  'oyentes': '127220',
  'reproducciones': '1448329',
  'bio_resumen': 'Etro Anime is an electronic band from New York City formed in 1998. Musical genres used by the band include drum and bass, deep house, trip hop, and breakbeat. The name "Etro Anime" means "to be infinite in spirit."\n\nThe band currently is a collective featuring Anais Alonso on vocals.   Led by producer Ted Birkey, the two collaborated with writer/producers Jeff Baldwin, Dave Fisher, John Kanselaar, Keith Schweitzer, Joe Tagliareni, and Malik Worthy to release Etro Anime\'s second full-length album, "Spreading Silence. <a href="https://www.last.fm/music/Etro+Anime">Read more on Last.fm</a>',
  'pais': ' '},
 {'artista': 'Ann Lee',
  'oyentes': '185838',
  'reproducciones': '917026',
  'bio_resumen': 'Ann Lee was born on 12-11-1972 in Sheffield, England. She went to Italy a few years ago. There, in a discotheque, she started to sing to share a laugh with some friends. She was spotted by a talent scout who invited her to an audition where they were looking for session singers and vocalists.\n\nShe passed the audition with flying colours and began doing session work. She also decided that great food and sunshine were a good reason to stay in Italy. <a href="https://www.last.fm/music/Ann+Lee">Read more on Last.fm</a>',
  'pais': ' '},
 {'artista': 'Soel',
  'oyentes': '40479',
  'reproducciones': '266870',
  'bio_resumen': 'The way trumpeter Pascal Ohsé sees it, R&B, soul, and jazz are "the closest thing we have to a universal musical language." The longtime St. Germain associate also believes it is a language that needs an update once in a while, something his Soel project set out to do from the start. Touring with the jazz and electronica-blending St. Germain meant Ohsé had access to St. Germain leader Ludovic Navarre\'s enormous collection of vintage vinyl. Digging dusty grooves during the day and playing contemporary <a href="https://www.last.fm/music/Soel">Read more on Last.fm</a>',
  'pais': ' '},
 {'artista': 'Blockhead',
  'oyentes': '698760',
  'reproducciones': '16055816',
  'bio_resumen': 'There are multiple artists artists using the name Blockhead\n\n1) A trip-hop artist from New York City\n2) A Swiss darkwave band\n3) A Japanese punk band\n4) A hardcore punk band from Washington, DC\n5) A hardcore punk band from Vancouver, BC, Canada with members of Koszmar / SNØB \n\n1) Blockhead grew up in downtown New York City. The son of an artist, early on he found his passion was for music. A fan of a whole range of sounds, especially hip-hop, Blockhead steadily built a tremendous collection of tapes and later CDs from innumerable artists. <a href="https://www.last.fm/music/Blockhead">Read more on Last.fm</a>',
  'pais': 'Japan'},
 {'artista': 'Ochre',
  'oyentes': '196867',
  'reproducciones': '3392669',
  'bio_resumen': 'Ochre is the work of Christopher Leary, originally from England, currently based in Den Haag, Netherlands. He has been writing intricate electronic music since 2001, and has released on Toytronic, Benbecula Records, Village Green, Tramworks, Shipwrec, Lapsus, and Mystic and Quantum, in addition to his own Aura Materia imprint.\n\nStylistically, his music is often highly melodic, described by the NME as being “full of shimmering electronics, crunchy <a href="https://www.last.fm/music/Ochre">Read more on Last.fm</a>',
  'pais': ' '},
 {'artista': 'Calibre',
  'oyentes': '232011',
  'reproducciones': '4219190',
  'bio_resumen': 'Dominick Martin aka Calibre is the 1st exclusively Irish Drum and Bass artist.\n\nClassically trained in violin, he dropped this for drums and began playing in various bands, before finding early Detroit techno and house. His inspiration around that time is said to wander around the likes of Kenny Larkin, Carl Craig, Juan Atkins, the Orb.\n\nHis brother introduced Calibre to drum and bass and jungle, which at first he couldn’t follow the pattern as he felt it was too relentless and \'beaty\' <a href="https://www.last.fm/music/Calibre">Read more on Last.fm</a>',
  'pais': 'Ireland'},
 {'artista': 'TOM & JOY',
  'oyentes': '12592',
  'reproducciones': '59320',
  'bio_resumen': 'biografia no encontrada',
  'pais': ' '},
 {'artista': 'Günther',
  'oyentes': '146459',
  'reproducciones': '1249609',
  'bio_resumen': 'There are at least three very different artists that go by the name Günther. One is a highly-sexualized Swedish pop singer (pictured left), the second is a symphonic rock trio from Calgary whose "Rock digs deep into an abyss of tonal expanses and constructs an impenetrable wall of resonance and covetous frequencies" and finally Gunther from Lebanon who\'s an Electronic music DJ. The beginning of this article focuses on the former, and for more on the latter visit http://guntherrock.ca. <a href="https://www.last.fm/music/+noredirect/G%C3%BCnther">Read more on Last.fm</a>',
  'pais': ' '},
 {'artista': 'Groove Collective',
  'oyentes': '127742',
  'reproducciones': '913207',
  'bio_resumen': 'New York City\'s Groove Collective transcends musical categories with one goal in mind: to move listeners\' minds and feet. For more than a decade, this legendary group of musicians has improvised and refined the stylistic crosspollination of funk, jazz, house, Latin, hip hop, rock and every party-inducing sound in between. The pioneering members of Groove Collective are fluent in the international language of "groove." In-the-pocket drum and bass, colorful and vibrant horns <a href="https://www.last.fm/music/Groove+Collective">Read more on Last.fm</a>',
  'pais': ' '},
 {'artista': 'UNKLE',
  'oyentes': '1380231',
  'reproducciones': '39390244',
  'bio_resumen': '\nUNKLE, a musical outfit founded in 1994 in London, England, United Kingdom. Originally categorized as trip-hop, the group once included producer DJ Shadow and has employed a variety of guest artists and producers.\n\nFrom the sleeve notes for the latest release End Titles...Stories For Film released in July 2008, the current line-up is stated as James Lavelle and Pablo Clements, also a member of the Psychonauts.\n\nThe original line-up was James Lavelle, Tim Goldsworthy (now a member of DFA) and Kudo (Major Force West, Skylab). <a href="https://www.last.fm/music/UNKLE">Read more on Last.fm</a>',
  'pais': ' '},
 {'artista': 'Roxie',
  'oyentes': '29006',
  'reproducciones': '283687',
  'bio_resumen': 'There is more than one artist with that name:\n\n1. Roksana Węgiel (born 11 January 2005) sometimes known as Roxie, is a Polish singer. She represented Poland in the Junior Eurovision Song Contest 2018 with the song "Anyone I Want to Be", and went on to win the competition. She is the first Polish entrant to win the Junior Eurovision Song Contest.\n\nRoksana Węgiel has received numerous accolades, including MTV Europe Music Award for Best Polish Act 2019, nomination for Kids\' Choice Award and Polish awards Fryderyk. <a href="https://www.last.fm/music/Roxie">Read more on Last.fm</a>',
  'pais': ' '},
 {'artista': 'ScubaZ',
  'oyentes': '88109',
  'reproducciones': '525746',
  'bio_resumen': 'biografia no encontrada',
  'pais': ' '},
 {'artista': 'DJ Cam',
  'oyentes': '531340',
  'reproducciones': '6314608',
  'bio_resumen': 'Parisian hip-hop devotee Laurent Daumail is one of a few but growing number of French artists updating hip-hop for the chill-out crowd, drawing on the beats\'n\'samples groundwork of producers such as Rakim, DJ Premier, and Prince Paul and combining it with broad, impressionistic strokes of dub, jazz, and soundtrack-y ambience. Like countrymen the Mighty Bop and la Funk Mob, Cam is stylistically closest to Mo\'Wax artists such as DJ Shadow and DJ Krush; minimalist <a href="https://www.last.fm/music/DJ+Cam">Read more on Last.fm</a>',
  'pais': 'France'},
 {'artista': 'Mariah Carey',
  'oyentes': '4803037',
  'reproducciones': '238804260',
  'bio_resumen': 'Mariah Carey (born March 27, 1969, Huntington, New York, USA) is an American singer, songwriter, actress, record producer, and #1 New York Times bestselling author. Carey is one of the best-selling music artists of all time, with over 220 million records sold worldwide. She holds the record for the most Billboard Hot 100 number-one singles by a solo artist (19), a female songwriter (18), and a female producer (15). Referred to as the "Songbird Supreme" <a href="https://www.last.fm/music/Mariah+Carey">Read more on Last.fm</a>',
  'pais': 'United States'},
 {'artista': 'edIT',
  'oyentes': '220097',
  'reproducciones': '4678187',
  'bio_resumen': 'Born and raised in Weston, Massachussetts, Edward Ma, now known to the world as edIT, began his music career as "The Con Artist" just before the turn of the millennium. As a resident DJ at the now defunct Konkrete Jungle Los Angeles, he shared the stage with Hive, Daddy Kev, James Tai and mic rockers Busdriver, P.E.A.C.E. and Mikah 9. Konkrete Jungle marked the golden age of indie hip-hop in Los Angeles, and was the bridge between the jungle and b-boy massives. <a href="https://www.last.fm/music/edIT">Read more on Last.fm</a>',
  'pais': ' '},
 {'artista': 'Gabin',
  'oyentes': '299902',
  'reproducciones': '3512989',

In [19]:
#dataframe de la lista final extraida de lastfm (con paises)
df_electronica_2 = pd.DataFrame(lista_artistas)

df_electronica_2

,artista,oyentes,reproducciones,bio_resumen,pais
0,Oscar G & Ralph Falcon,5757,24033,biografia no encontrada,
1,Enigma,1378807,51184245,There is more than one artist with the name En...,Germany
2,Jan Wayne,185108,1274461,Jan Wayne (German pronunciation: [ˌjan ˈvɛɪn] ...,Germany
3,TM Juke,292266,2736136,"TM Juke, real name Al Cowan, aka Artist Former...",
4,Aya,164581,1761488,There are multiple artists that have recorded ...,United Kingdom
...,...,...,...,...,...
288,Dizzee Rascal,1284387,25234995,"Dylan Mills, known professionally as Dizzee Ra...",
289,Scatman John,626202,4907903,"John Paul Larkin (born March 13, 1942 in El Mo...",
290,Telefon Tel Aviv,419935,10490499,Telefon Tel Aviv is a Los Angeles-based group ...,
291,Paul van Dyk,892714,14252965,Matthias Paul (born 16 December 1971 in Eisenh...,Germany
292,Marilyn Manson,3108306,192782063,Marilyn Manson is an American rock band formed...,United States

In [ ]:
df_electronica_2.to_csv('artistas_electronica.csv', index=False, encoding="utf-8")